#!/usr/bin/env python

deps = [
	'Newtonsoft.Json.dll',
	'NLog.dll',
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Peach.Pro.Test.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

app = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'pitc.exe',
	ver_product = 'Peach Pit Compiler',
)
