[[Publishers_FilePerIteration]]

// Reviewed:
//  - 02/13/2014: Seth & Adam: Outlined
// Params are good
// discuss format string format for filename and how it appends the number, give examples!
// give full put to run for example
// Updated:
// - 02/14/2014: Jordyn
// Added full example
// Added description of format string for filename and how it appends the number with examples

== FilePerIteration Publisher

The _FilePerIteration_ publisher will create an output file for every iteration the fuzzer performs.  This is useful when pre-generating fuzzing cases. 
Peach will append the iteration number to the fuzzed files name when generating the fuzzed files.  For a file name format of "fuzzed_{0}.bin" the {0} will be replaced with the current iteration number which produces the following filenames: fuzzed_1.bin, fuzzed_2.bin, fuzzed_3.bin, fuzzed_4.bin, etc.

=== Parameters

  * _FileName_ -- Name of file to create.  Filename must contain "\{0\}" which will be substituted with the iteration count.

=== Actions

  * xref:Action_open[open]  -- Open file for reading/writing.
  * xref:Action_close[close]  -- Close file stream.
  * xref:Action_output[output]  -- Data to be written to file
  * xref:Action_input[input]  -- Read data from file.

=== Examples

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="TheDataModel">
    <Number name="Magic" size="8" value="47" token="true"/>
    <Number name="Length" size="8">
      <Relation type="size" of="Data"/>
    </Number>
    <Blob name="Data"/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="TheDataModel" />
        <Data fileName="file.bin"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="FilePerIteration">
      <Param name="FileName" value="fuzzed_{0}.bin" />
    </Publisher>
  </Test>
</Peach>
----
