<<<
[[Publishers_Http]]
== Http Publisher

// 02/13/2014: Seth & Adam: Outlined
//  Params are good
//  give full put to run for example
//  examples to show, fuzzing a get with an input action!
//  examples: setting cookies for a get
//  example: doing a post

// 02/14/2014: Jordyn
//   Added full examples for post,cookie and input

_Http_ publisher sends data over HTTP via a valid HTTP method type.

_Http_ supports the following features:

 * Authentication via Basic, Digest, or Windows integrated
 * Definable method type
 * Fuzzing and dynamic setting of headers (both key and value)
 * Fuzzing and dynamic setting of query strings
 * Optional cookie support
 * SSL

=== Syntax

[source,xml]
----
<Publisher class="Http">
    <Param name="Method" value="POST" />
    <Param name="Url" value="http://foo/user/create" />
</Publisher>
----

=== Parameters

_Required:_

Method:: HTTP Method type (like GET and POST)
Url:: URL of target

_Optional:_

BaseUrl:: Base URL is used by some authentication types
Username:: Username for authentication
Domain:: Domain for authentication
Cookies:: Enable cookie support. Defaults to true.
CookiesAcrossIterations:: Track cookies across iterations. Defaults to false.
Timeout:: How long to wait in milliseconds for data/connection. Defaults to 3,000.
IgnoreCertErrors:: Allow HTTPS regardless of cert status. Defaults to false.

=== Actions

xref:Action_call[call]::
	Special method names used to fuzz the querystring or a specific header.
	+
	[horizontal]
	Query;; Specify as the method name for a call action, the first parameter is the query string
	Header;; Specify as the method name for a call action, the first parameter is the header name, the second is the value

xref:Action_start[start]:: Implicit Action to start the Publisher.
xref:Action_stop[stop]:: Implicit Action to stop the Publisher.
xref:Action_open[open]:: Open and initialize the socket.
xref:Action_close[close]:: Close and clean up the socket.
xref:Action_output[output]:: Data sent via output is written to the open socket.
xref:Action_input[input]:: Data received via input is read from the open socket.

=== Examples

.HTTP POST Request
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="PostBody">
    <String name="Username" value="username=user"/>
    <String name="Comma" value=","/>
    <String name="Password" value="password=admin"/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="PostBody" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="POST" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================

.HTTP GET Request
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
     <Blob/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="input" >
          <DataModel ref="TheDataModel" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="GET" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================

.Fuzzing HTTP GET Request Query String
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

 <DataModel name="QueryModel">
   <String value="key"/>
   <String value="=" token="true" />
   <String value="value"/>
  </DataModel>

  <DataModel name="GetInputModel">
    <Blob/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="call" method="Query">
        <Param>
          <DataModel ref="QueryModel" />
        </Param>
      </Action>

      <Action type="input">
        <DataModel ref="GetInputModel"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="GET" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================

.Fuzzing Cookie Value in Header
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="HeaderKey">
   <String value="Cookie" />
  </DataModel>

  <DataModel name="HeaderValue">
     <String value="user=newuesr" />
  </DataModel>

  <DataModel name="GetInputModel">
    <Blob/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="call" method="Header">
        <Param>
          <DataModel ref="HeaderKey" />
        </Param>
        <Param>
          <DataModel ref="HeaderValue" />
        </Param>
      </Action>

      <Action type="input">
        <DataModel ref="GetInputModel"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="GET" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================
