<<<
[[Publishers_RawEther]]
== RawEther Publisher

// Reviewed:
//  - 02/13/2014: Seth & Adam: Outlined
// Params are good
// give full put to run for example
// name is name not ip
// Give full enumeration of Ethernet protocols supported
// Talk about MTU setProperty for fuzzing MTU
// Updated:
// - 02/14/2014: Jordyn
// Added full example w/ mtu fuzzing
// Added full enum list for Ethernet protocol
// Added short description about fuzzing mtu

The _RawEther_ publisher allows sending raw IPv6 packets with IP headers.

NOTE: This publisher only runs on Linux with root privileges.

=== Syntax

[source,xml]
----
<Publisher class="RawEther">
	<Param name="Interface" value="lo" />
	<Param name="Protocol" value="ETH_P_ALL" />
</Publisher>
----

=== Parameters

_Required:_

Interface:: Name of interface to bind too

_Optional:_

Protocol::
	Ethernet protocol to use. Default is ETH_P_ALL.  +
	_Supported Ethernet Protocol Enum Values:_  +
	ETH_P_LOOP;; Ethernet Loopback packet
	ETH_P_PUP;; Xerox PARC Universal Packet (Pup)
	ETH_P_PUPAT;; Xerox Pup Address Translation
	ETH_P_IP;; Internet Protocol
	ETH_P_X25;; CCITT X.25 Protocol. Note that CCITT is now ITU-T 
	ETH_P_ARP;; Address Resolution Protocol
	ETH_P_BPQ;; G8BPQ AX.25 Ethernet Packet (not an officially registered ID)
	ETH_P_IEEEPUP;; Xerox IEEE802.3 Pup
	ETH_P_IEEEPUPAT Xerox IEEE802.3 Pup Address Translation
	ETH_P_DEC;; DEC Assigned
	ETH_P_DNA_DL;; DEC DNA Dump/Load
	ETH_P_DNA_RC;; DEC DNA Remote Console
	ETH_P_DNA_RT;; DEC DNA Routing
	ETH_P_LAT;; DEC Local Area Transport
	ETH_P_DIAG;; DEC Diagnostics
	ETH_P_CUST;; DEC Customer Use
	ETH_P_SCA;; DEC Systems Comms Arch
	ETH_P_TEB;; Transparent Ethernet Bridging
	ETH_P_RARP;; Reverse Address Resolution
	ETH_P_ATALK;; AppleTalk Datagram Delivery Protocol
	ETH_P_AARP;; AppleTalk Address Resolution Protocol
	ETH_P_8021Q;; 802.1Q Virtual LAN Extended Header
	ETH_P_IPX;; IPX over DIX
	ETH_P_IPV6;; IPv6 over bluebook
	ETH_P_PAUSE;; IEEE Pause Frames
	ETH_P_SLOW;; Slow Protocols (IEEE 802.3)
	ETH_P_WCCP;; Web Cache Coordination Protocol
	ETH_P_PPP_DISC;; Point-to-Point Protocol over Ethernet (PPPoE) Discovery Messages
	ETH_P_PPP_SES;; PPPoE Session Messages
	ETH_P_MPLS_UC;; Multiprotocol Label Switching (MPLS) Unicast Traffic
	ETH_P_MPLS_MC;; MPLS Multicast Traffic
	ETH_P_ATMMPOA;; MultiProtocol Encapsulation Over ATM
	ETH_P_LINK_CTL;; HomePNA (formerly HPNA), WLan Link Local Tunnel
	ETH_P_ATMFATE;; Frame based ATM Transport over Ethernet
	ETH_P_PAE;; Port Access Entity (IEEE 802.1X)
	ETH_P_AOE;; ATA over Ethernet
	ETH_P_8021AD;; 802.1ad Service VLAN
	ETH_P_1588;; IEEE 1588 Timesync
	ETH_P_FCOE;; Fibre Channel over Ethernet
	ETH_P_TDLS;; TDLs
	ETH_P_FIP;; FCoE Initialization Protocol
	ETH_P_QINQ1;; Deprecated - QinQ VLAN
	ETH_P_QUINQ2;; Deprecated - QinQ VLAN
	ETH_P_QINQ3;; Deprecated - QinQ VLAN
	ETH_P_EDSA;; Ethertype DSA
	ETH_P_AF_IUCV;; IBM af_iucv
	ETH_P_802_3;; Dummy type for 802.3 frames
	ETH_P_AX25;; Dummy protocol ID for AX.25
	ETH_P_ALL;; Every packet
	ETH_P_802_2;; 802.2 Frames
	ETH_P_SNAP;; Internal only
	ETH_P_DDCMP;; DEC DDCMP: Internal only
	ETH_P_WAN_PPP;; Dummy type for WAN PPP Frames
	ETH_P_PPP_MP;; Dummy type for PPP MP Frames
	ETH_P_LOCALTALK;; Localtalk pseudo type
	ETH_P_CAN;; Controller Area Network
	ETH_P_PPPTALK;; Dummy type for AppleTalk over PPP
	ETH_P_TR_802_2;; IEEE 802.2 Frames
	ETH_P_MOBITEX;; Mobitex
	ETH_P_CONTROL;; Card Specific Control Frames
	ETH_P_IRDA;; Linux-IrDA (IrDA - Infrared Data Association)
	ETH_P_ECONET;; Acorn Econet
	ETH_P_HDLC;; HDLC Frames
	ETH_P_ARCNET;; 1A for ArcNet
	ETH_P_DSA;; Distributed Switch Architecture
	ETH_P_TRAILER;; Trailer Switch Tagging
	ETH_P_PHONET;; Nokia Phonet Frames
	ETH_P_IEE802154;; IEEE 802.15.4 Frame
	ETH_P_CAIF;; ST-Ericsson CAIF 

ProtocolTimeout:: Amount of time, in milliseconds, to wait for data or for a connection. The default value is 3,000.
MinMTU:: Minimum packet size to transmit. The smallest value is 1280, which is the default value.
MaxMTU:: maximum packet size to transmit. The largest value is 131070, which is the default value.
Filter::
    Filters the received frames using a libpcap-style filter string. For more information
    about libpcap style filters, see http://www.tcpdump.org/manpages/pcap-filter.7.html[this page].

=== Actions

xref:Action_start[start]:: Implicit Action to start the Publisher.
xref:Action_stop[stop]:: Implicit Action to stop the Publisher.
xref:Action_open[open]:: Open and initialize the socket.
xref:Action_close[close]:: Close and clean up the socket.
xref:Action_output[output]:: Writes data through output to the open socket.
xref:Action_input[input]:: Reads data through input from the open socket.

=== Examples

.Sending data
===============
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <Defaults>
    <Number endian="big"/>
  </Defaults>

  <DataModel name="TheDataModel">
    <Blob name="Dest" valueType="hex" mutable="false" length="6" value="FFFFFFFFFFFF"/>
    <Blob name="Src" valueType="hex" mutable="false" length="6" value="FFFFFFFFFFFF"/>
    <Number name="TypeOrLen" size="16" token="true"  valueType="hex" value="0806"/>
    <Block name="Payload">
      <String name="name" value="Deja vu"/>
    </Block>
  </DataModel>

  <DataModel name="propertySize">
    <Number size="32" value="1500"/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="setProperty" property="MaxMTU">
        <DataModel ref="propertySize"/>
      </Action>

      <Action type="setProperty" property="MinMTU">
        <DataModel ref="propertySize"/>
      </Action>

      <Action type="output">
        <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
  <Publisher class="RawEther">
    <Param name="Interface" value="lo" />
    <Param name="Protocol" value="ETH_P_ALL" />
  </Publisher>
  </Test>
</Peach>
----
===============
