[[Publishers_RawV4]]

// Reviewed:
//  - 02/13/2014: Seth & Adam: Outlined
// Params are good
// give full put to run for example
// Mention that recv includes ip header but send does not
// Give full enumeration of ethernet protocols supported
// Talk about mtu setProperty for fuzzing mtu
// Updated:
// - 02/17/2014: Jordyn
// Added full example using UDP
// Added supported protocol numbers and their corresponding protocol names
// Added MTU description
// Added information about when receiving input
// Added get/setProperty actions


== RawV4 Publisher

The _RawV4_ publisher allows sending raw IPv4 packets without IP header. When receiving input, the IPv4 header is included in the received data. The maximum and minimum MTU size of the publisher can be fuzzed by using the publisher's _setProperty_ action.

NOTE: This publisher runs best on Linux and requires root privileges.

*_Supported Protocol Values_
	** 1:: ICMP
	** 2:: IGMP
	** 6:: TCP
	** 17:: UDP
	** 41:: ENCAP
	** 89:: OSPF
	** 132:: SCTP


=== Parameters

Host:: Hostname or IP address of remote host
Interface:: IP of interface to bind too (optional)
Protocol:: IP protocol to use (e.g. TCP)
Timeout:: How long to wait in milliseconds for data/connection (optional, default 3,000)
MaxMTU:: Maximum allowable MTU property value (optional, default 131,070)
MinMTU:: Minimum allowable MTU property value (optional, default 1,280)

=== Actions

	* xref:Action_start[start]  -- Implicit Action to start the Publisher.
	* xref:Action_stop[stop]  -- Implicit Action to stop the Publisher.
	* xref:Action_open[open]  -- Open and initialize the socket.
	* xref:Action_close[close]  -- Close and clean up the socket.
	* xref:Action_output[output]  -- Data sent via output is written to the open socket.
	* xref:Action_input[input]  -- Data received via input is read from the open socket.
	* xref:Action_getProperty[getProperty] -- Get a property value
	* xref:Action_setProperty[setProperty] -- Set a property value

=== Examples

.Sending data
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="propertySize">
    <Number size="32" value="1500"/>
  </DataModel>

  <DataModel name="Data">
    <String name="Start" value="Start"/>
    <Blob name="Data" valueType="hex" value="BEEFEA7E41"/>
    <String name="Stop" value="Stop"/>
  </DataModel>

  <DataModel name="Packet">
    <Block name="Header">
      <Number name="SrcPort"  size="16" endian="big" value="31337"/>
      <Number name="DestPort" size="16" endian="big" value="31337"/>
      <Number name="Length"   size="16" endian="big">
        <Relation type="size" of="Packet"/>
      </Number>
      <Number name="Checksum" size="16" endian="big">
        <Fixup class="UDPChecksumFixup">
          <Param name="ref" value="Packet"/>
          <Param name="src" value="127.0.0.1"/>
          <Param name="dst" value="127.0.0.1"/>
        </Fixup>
      </Number>
    </Block>
    <Block name="UdpPayload" ref="Data"/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
    	<Action type="setProperty" property="MaxMTU">
        <DataModel ref="propertySize"/>
      </Action>

      <Action type="output">
        <DataModel ref="Packet" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="RawV4">
      <Param name="Host" value="127.0.0.1" />
     <Param name="Protocol" value="17" />
    </Publisher>
  </Test>
</Peach>
----
