<<<
[[Publishers_Rest]]
== Rest Publisher

The _Rest_ Publisher  is an I/O adapter that communicates using the Representational State Transfer (REST) architecture. This publisher communicates using HTTP as the underlying transport.

This publisher shupports sending body data as:

 * JSON when models contain the Json element.
 * XML when models contain XmlElement
 * As raw binary data when a custom content type is provided

Additionally, the publisher encodes the data model into JSON before transmitting it to the server.

TIP: SSL/TLS is supported, just use +https+ as the protocol in the URL.

=== Syntax

[source,xml]
----
<Publisher class="Rest"/>

<!-- Custom content type header -->
<Publisher class="Rest">
    <Param name="ContentType" value="application/octet-stream" />
</Publisher>
----

=== Parameters

_Required:_

There are no required parameters.

_Optional:_

ContentType:: Value for content-type header.  Set this to allow sending of binary data.
BaseUrl:: Base URL is used by some authentication types
Username:: Username for authentication
Password:: Optional password associated with the Username in authentication
Domain:: Domain for authentication
Cookies:: Enable cookie support. The default value is true.
CookiesAcrossIterations:: Track cookies across iterations. The default value is false.
Timeout:: How long to wait in milliseconds for data/connection. the default value is 3,000.
IgnoreCertErrors:: Allow HTTPS regardless of cert status. The default value is true.

=== Actions

xref:Action_call[call]::
+
Call actions are used to perform REST calls.

The method attribute contains both the HTTP method (GET, POST, etc.) and the URL.
The URL portion of the method attribute can contain parameter substitution tokens. 
These tokens are replaced with the parameters provided. 
One additional parameter can be provided that is used for the body of the request. 

* The format of the method attribute is: +METHOD URL+
* This example places a call that expects to receive a single parameter: +GET /product/{0}+
* This example places a call that expects to receive two parameters: +GET /invoices?start_date={0}&end_date={1}+


=== Example

.Calling Rest Services

The following example provides three fragments using the GET and POST methods.

[source,xml]
----

<DataModel name="PostData">
    <Json>
        <String name="Name" value="Widget" />
        <Double name="Price" value="1.99" />
        <Number name="Quantify" value="1" />
    </Json>
</DataModel>


<Action type="call" method="GET http://www.example.com/product/{0}">
    <!-- {0} -->
    <Param name="Id">
        <DataModel ref="Id" />
    </Param>
</Action>

<Action type="call" method="GET http://www.example.com/invoices?start_date={0}&end_data={1}">
    <!-- {0} -->
    <Param name="StartDate">
        <DataModel ref="StartDate" />
    </Param>
    <!-- {1} -->
    <Param name="EndDate">
        <DataModel ref="EndDate" />
    </Param>
</Action>

<Action type="call" method="POST http://www.example.com/product/{0}">
    <!-- {0} -->
    <Param name="Id">
        <DataModel ref="Id" />
    </Param>
    
    <!-- POST Body -->
    <Param name="PostData">
        <DataModel ref="PostData" />
    </Param>
</Action>
----

.Posting XML

The following example provides three fragments using the GET and POST methods.

[source,xml]
----

<DataModel name="PostData">
    <XmlElement elementName="Product">
        <XmlAttribute attributeName="Name">
            <String value="Widget" />
        </XmlAttribute>
        <XmlAttribute attributeName="Price">
            <Double value="1.99" />
        </XmlAttribute>
        <XmlAttribute attributeName="Quantity">
            <Number value="1" />
        </XmlAttribute>
    </XmlElement>
</DataModel>


<Action type="call" method="POST http://www.example.com/product/{0}">
    <!-- {0} -->
    <Param name="Id">
        <DataModel ref="Id" />
    </Param>
    
    <!-- POST Body -->
    <Param name="PostData">
        <DataModel ref="PostData" />
    </Param>
</Action>
----


.Posting Binary

The following example provides three fragments using the GET and POST methods.

[source,xml]
----

<DataModel name="PostData">
    <Blob />
</DataModel>

<Action type="call" method="POST http://www.example.com/product/{0}/image">
    <!-- {0} -->
    <Param name="Id">
        <DataModel ref="Id" />
    </Param>
    
    <!-- POST Body -->
    <Param name="PostData">
        <DataModel ref="PostData" />
        <Data fileName="image.png" />
    </Param>
</Action>

<Test name="Default">

    <Publisher class="Rest">
        <Param name="ContentType" value="application/octet-stream" />
    </Publisher>

</Test>
----


