<<<
[[Publishers_Rest]]
== Rest Publisher

The _Rest_ Publisher enables a pit to communicate to a TCP socket using the Secure Socket Layer (SSL) protocol. Peach uses _Ssl_ to fuzz protocols (such as HTTPS) that are built inside an SSL encrypted channel.

Since it is easy to confuse _Ssl_ and _SslListner_, here's the difference:

* The _SslListner_ Publisher accepts incoming (inward) connections, as one that listens.
* The _Ssl_ Publisher connects outbound communications. 

=== Syntax

[source,xml]
----
<Publisher class="Rest">
    <Param name="Method" value="GET"/>
    <Param name="Url" value="" />
</Publisher>
----

[source,xml]
----
<Action type="call" method="GET /product/{0}">
    <!-- {0} -->
    <Param name="Id">
        <DataModel ref="Id" />
    </Param>
</Action>

<Action type="call" method="GET /invoices?start_date={0}&end_data={1}">
    <!-- {0} -->
    <Param name="StartDate">
        <DataModel ref="StartDate" />
    </Param>
    <!-- {1} -->
    <Param name="EndDate">
        <DataModel ref="EndDate" />
    </Param>
</Action>

<Action type="call" method="POST /product/{0}">
    <!-- {0} -->
    <Param name="Id">
        <DataModel ref="Id" />
    </Param>
    
    <!-- POST Body -->
    <Param name="PostData">
        <DataModel ref="PostData" />
    </Param>
</Action>
----

=== Parameters

_Required:_

There are no required parameters.
    
_Optional:_

BaseUrl:: Base URL is used by some authentication types
Username:: Username for authentication
Domain:: Domain for authentication
Cookies:: Enable cookie support. The default value is true.
CookiesAcrossIterations:: Track cookies across iterations. The default value is false.
Timeout:: How long to wait in milliseconds for data/connection. the default value is 3,000.
IgnoreCertErrors:: Allow HTTPS regardless of cert status. The default value is false.

=== Actions

xref:Action_call[call]::
+
Call actions are used to perform REST calls.

The method attribute contains both the HTTP method (GET, POST, etc.) and the URL.
The URL portion of the method attribute can contain parameter substitution tokens. 
These tokens are replaced with the parameters provided. 
One additional parameter can be provided that is used for the body of the request. 

* The format of the method attribute is: +METHOD URL+
* This example places a call that expects to receive a single parameter: +GET /product/{0}+
* This example places a call that expects to receive two parameters: +GET /invoices?start_date={0}&end_date={1}+

///////////////////////////
=== Examples

.Calling Rest Services
[source,xml]
----
TODO -- Call public rest API (google?)
----

///////////////////////////
