[[Publishers_Ssl]]

// Updates:
// 2/17/2014: Mick
// added description
// added params and actions
// added example


== Ssl Publisher

The _Ssl_ Publisher enables a pit to communicate via an SSL over TCP socket.
This is used to fuzz protocol built inside an SSL encrypted channel, such as HTTPS.

=== Parameters

	* _Host_ -- Hostname to connect to.
    * _Port_ -- Port to connect to.
    * _ConnectTimeout_ -- Max milliseconds to wait for connection (default 10000). default="10000"
    * _Sni_ -- Sni to use for SSL connection. Will use Host by default. default=""
    * _Timeout_ -- How many milliseconds to wait for data (default 3000). default="3000"
    * _VerifyServer_ -- Verify the server certificate. default="false"

=== Actions

	* xref:Action_start[start]  -- Implicit Action to start the Publisher.
	* xref:Action_stop[stop]  -- Implicit Action to stop the Publisher.
	* xref:Action_open[open]  -- Open and initialize the SSL connection.
	* xref:Action_close[close]  -- Close and clean up the SSL connection.
	* xref:Action_output[output]  -- Data sent via output is written to the SSL stream.
	* xref:Action_input[input]  -- Data received via input is read from the SSL input buffer.

=== Examples

.Sending and receiving data
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="OutModel">
		<Block name="Headers">
			<String value="POST /testsslpage.html HTTP/1.0\r\n" />
			<String value="User-Agent: TestAgent/1.0\r\n"/>
			<String value="Content-Length:   " /> 
			<String name="ContentLen">
				<Relation of="Data" type="size"/> 
			</String>
			<String value="\r\n\r\n"/>     
			<String name="Data"/> 
		</Block>	
	</DataModel>

	<DataModel name="InModel">
		<String value="{" token="true" />
		<String />
		<String value="}" token="true" />
	</DataModel>

	<StateModel name="State" initialState="First">
		<State name="First">
			<Action type="output">
				<DataModel ref="OutModel">
			</Action>
			<Action type="input">
				<DataModel ref="InModel">
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="State"/>
    
		<Publisher class="Ssl">
			<Param name="Host" value="localhost"/>
			<Param name="Port" value="31337"/>
			<Param name="Timeout" value="3000"/>
		</Publisher>
		 
		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

