[[Publishers_SslListener]]

// Updates:
// 2/17/2014: Mick
// added description
// added params and actions
// added example

== SslListener Publisher

The _Ssl_ Publisher enables a pit to communicate via an SSL over TCP socket.
This is used to fuzz protocol built inside an SSL encrypted channel, such as HTTPS.
The SslListener is similar to the TcpListener because both will accept connections over a TCP port and block until a connection has been established.

=== Parameters

	* _Interface_ -- IP of interface to bind to.
	* _Port_ -- Local port to listen on.
	* _ServerCertPath_ -- Path to server certificate file.
	* _AcceptTimeout_ -- How many milliseconds to wait for a connection (default 3000). default="3000"
	* _CheckCertRevocation_ -- Check revocation of certificate. default="false"
	* _ClientCertRequired_ -- Require client to auth via certificate. default="false"
	* _ServerCertPass_ -- Password for cert file. default=""
	* _Timeout_ -- How many milliseconds to wait for data. default="3000"

=== Actions

	* xref:Action_start[start]  -- Implicit Action to start the Publisher.
	* xref:Action_stop[stop]  -- Implicit Action to stop the Publisher.
	* xref:Action_open[open]  -- Open and initialize the SSL connection.
	* xref:Action_close[close]  -- Close and clean up the SSL connection.
	* xref:Action_accept[accept] -- Block until an incoming SSL connection has been received.
	* xref:Action_output[output]  -- Data sent via output is written to the SSL stream.
	* xref:Action_input[input]  -- Data received via input is read from the SSL input buffer.

=== Examples

.Sending and receiving data
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="OutModel">
		<Block name="Headers">
			<String value="{" />
			<String value="key1" />
			<String value="," />
			<String value="value1" />
			<String value="}" />
		</Block>	
	</DataModel>

	<DataModel name="InModel">
		<String value="GET /testsslpage.html HTTP/1.0\r\n" />
	</DataModel>

	<StateModel name="State" initialState="First">
		<State name="First">
			<Action type="accept" />
			<Action type="input">
				<DataModel ref="InModel">
			</Action>
			<Action type="output">
				<DataModel ref="OutModel">
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="State"/>
    
		<Publisher class="SslListener">
			<Param name="Interface" value="0.0.0.0"/>
			<Param name="Port" value="31337"/>
			<Param name="Timeout" value="3000"/>
			<Param name="AcceptTimeout" value="3000"/>
			<Param name="ServerCertPath" value="cert.pfx" />
		</Publisher>
		 
		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

