[[Publishers_Udp]]

// Reviewed:
//  - 02/13/2014: Seth & Adam: Outlined
// Params are good
// give full pit to run for example
// Examples: - Udp "listner" w/srcport and interface
//           - Udp "connect" w/host and port
//           - Multicast example

== Udp Publisher

The _Udp_ publisher is able to send and receive UDP packets.

=== Parameters

Host:: Host or IP address or remote host
Port:: Destination port number (optional when first packet is sent by target)
SrcPort:: Source port (optional)
Interface:: IP of interface to bind to (optional)
Timeout:: How long to wait in milliseconds for data/connection (optional, default 3,000)
MaxMTU:: Maximum allowable MTU property value (optional, default 131,070)
MinMTU:: Minimum allowable MTU property value (optional, default 1,280)

=== Actions

 * link:../Action.html#\_output[_output_] -- Send data to remote host
 * link:../Action.html#\_input[_input_] -- Receive data from remote host

=== Examples

.Connect
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="TheDataModel">
		<String name="value" length="4" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="TheDataModel"/>
				<Data>
					<Field name="value" value="mike" />
				</Data>
			</Action>

			<!-- receive 4 bytes -->
			<Action type="input">
				<DataModel ref="TheDataModel"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent"/>

	<Test name="Default">
		<Agent ref="TheAgent"/>
		<StateModel ref="TheState"/>
		<Publisher class="Udp">
			<Param name="Host" value="127.0.0.1" />
			<Param name="Port" value="8000" />
		</Publisher>

	</Test>
</Peach>
----

.Listener
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="TheDataModel">
		<String name="value" length="4" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="open"/>
			<Action type="output">
				<DataModel ref="TheDataModel"/>
				<Data>
					<Field name="value" value="mike" />
				</Data>
			</Action>

			<!-- receive 4 bytes -->
			<Action type="input">
				<DataModel ref="TheDataModel"/>
			</Action>
			<Action type="close"/>
		</State>
	</StateModel>

	<Agent name="TheAgent"/>

	<Test name="Default">
		<Agent ref="TheAgent"/>
		<StateModel ref="TheState"/>
		<Publisher class="Udp">
			<Param name="Host" value="127.0.0.1" />
			<Param name="Interface" value="127.0.0.1" />
			<Param name="SrcPort" value="8000" />
			<Param name="Port" value="8001" />
		</Publisher>

	</Test>
</Peach>
----

.Multicast
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="TheDataModel">
		<String name="value" length="4" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="open"/>
			<Action type="output">
				<DataModel ref="TheDataModel"/>
				<Data>
					<Field name="value" value="mike" />
				</Data>
			</Action>

			<!-- receive 4 bytes -->
			<Action type="input">
				<DataModel ref="TheDataModel"/>
			</Action>
			<Action type="close"/>
		</State>
	</StateModel>

	<Agent name="TheAgent"/>

	<Test name="Default">
		<Agent ref="TheAgent"/>
		<StateModel ref="TheState"/>
    <Publisher class="Udp" name="LisentenPublisher">
      <Param name="Host" value="224.0.0.1"/>
      <Param name="Port" value="8000"/>
      <Param name="SrcPort" value="8001"/>
      <Param name="Interface" value="127.0.0.1"/>
    </Publisher>
	</Test>
</Peach>
----
