[[IssueTracker]]
== Issue Tracker Integration

WARNING: This section is still under construction.
Information provided is partial and may be out of date.

Peach Web can automatically submit security findings into an issue tracking system such as JIRA or Bugzilla.
Submitted tickets can then be reviewed by the engineering team and go through a typical issue workflow.
Peach Web supports two ticketing systems out of the box, JIRA and Bugzilla.  
Other systems can be supported by modifying one of the example Python scripts.

Issue tracker integrations are provided as python scripts.
These scripts can be used in two ways with Peach Web:

CI Runner::
Launched by the CI integration runner.
In this method the generic CI runner or CI plugin is configured to launch the issue tracker integration script
when the testing has completed.
+
The issue tracker integration scripts use the +PEACH_API+ and +PEACH_API_TOKEN+ environment variables to specify the Peach Web instance to query for fault data.
+
This is the recommended solution when integrating into a CI system.

    
External Entity/By Hand::
    Launched by an external actor or by hand.
    An external automation tool is configured to run the issue tracker integration script.
    Peach must be running but finished testing when the script is run, as it uses
    Peaches API to extract the fault data.

=== JIRA

The script is located in _SDK/tools/peach2jira_.

Core features:

* Single issue per bucket
** Add comment when reproduced
* Optional custom field needed for best operation
* Apply zero or more labels to created issues

==== Configuration

. Install Python v2.7
. Install dependencies +pip install -r requirements.txt+
. Configure JIRA
. Update +settings.json+ file with configuration

===== _JIRA Configuration_

. Create a user with access to project and REST API.

.Add custom bucket field (optional)

To enable single issue per-bucket a custom issue field is required.

. Add custom field (Admin -> Project -> Fields -> Custom fields -> Add Custom Field)
.. Text Field (single line)
.. Name: Peach Bucket
. Add field to Issue type "Bug"

=== Bugzilla

The script is located in _SDK/tools/peach2bugzilla_.

Core features:

* Single ticket per bucket
** Add comment when reproduced
** Re-open resolved issues when re-found
* Optional custom field needed for best operation

==== Configuration

. Install Python v2.7
. Install dependencies +pip install -r requirements.txt+
. Configure Bugzilla
. Update +settings.json+
. Test integration with existing job

===== Bugzilla Configuration

. Create a user with access to project and REST API.
. Create an API key for the user and update +settings.json+ file

.Add custom bucket field (optional)

To enable single issue per-bucket a custom issue field is required.

. Add custom field (Admin -> Custom Fields -> Add a new custom field)
.. Name: cf_peach
.. Description: Peach
.. Type: Free Text
