#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'SharpPcap.dll',
	'Peach.Core.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'Godel.Core.dll',
	'Peach.Enterprise.dll',
	'Peach.Enterprise.Test.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PitTester.exe',
	ut_cwd = bld.path.find_node('../pits/pro').abspath(),
	ut_args = '.',
	ide_path = 'Peach Enterprise',
)
