<<<
[[Transformers_ApacheMd5Crypt]]
== ApacheMd5Crypt

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / action supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output

// Updated:
// 2/20/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Cryptography

_ApacheMd5Crypt_ hashes data with the MD5 Crypt, using the method described in the Apache HTTP Server Documentation.
The first two bytes are used as the salt with the value $apr1$ prepended. 

This xref:Transformer[Transformer] can only be applied to outgoing data because hashes are one-way operations.

=== Parameters

None.

=== Attributes

None.

=== Actions Supported

xref:Action_output[output]:: On output, this transformer hashes the outgoing data.

=== Examples

.Simple Console Example
==========================
This example uses ApacheMd5Crypt on an inline value and writes the transformed value to the console.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<Block name="Main">
			<String name="TransformMe" value="superdoopersecret">
				<Transformer class="ApacheMd5Crypt" />
			</String>
		</Block>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Hashed Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>
	</Test>
</Peach>
----

Output from this example.

----
> peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Peach Fuzzer LLC

[*] Test 'Default' starting with random seed 10921.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(31 bytes)
00000000   24 61 70 72 31 24 73 75  24 35 65 78 54 74 42 71   $apr1$su$5exTtBq
00000010   56 41 51 77 55 31 2F 47  4D 6C 79 61 7A 45 2F      VAQwU1/GMlyazE/
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================
