#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Xml.dll',
	'System.Xml.Linq.dll',
	'RabbitMQ.Client.dll',
	'PeachFarm.Common.dll',
	'Ionic.Zip.Reduced.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PeachFarm.Admin.dll',
)
