#!/usr/bin/env python

deps = [
	'BouncyCastle.Crypto.dll',

	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Peach.Pro.Test.dll',
	'Peach.Pro.WebApi2.dll',

	'System.dll',
	'System.Core.dll',
	'System.Net.Http.dll',
	'System.Net.Http.WebRequest.dll',
	'System.Web.dll',
	'System.Xml.dll',

	'Titanium.Web.Proxy.dll',
]

pkgs = [
	'Autofac.WebApi2.Owin',
	'Microsoft.AspNet.WebApi.Client',
	'Microsoft.Owin.Host.HttpListener',
	'Microsoft.Owin.StaticFiles',
	'Microsoft.Owin.Testing',
	'Moq',
	'NLog',
	'NUnit',
	'vtortola.WebSocketListener',
]

bld(
	name = 'Peach.Pro.Test.WebProxy.exe',
	features = 'cs test paket',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = ['net45', 'net40', 'portable-net45+win8+wpa81'],
	),
	source = bld.path.ant_glob('**/*.cs'),
	resource = bld.path.ant_glob('**/*.json **/*.yml'),
	csdoc = False,
	csflags = [
		# The following are remapped in Peach's app.config:
		# System.Web.Http v5.2.2 -> v5.2.3
		# System.Net.Http.Formatting v5.2.2 -> v5.2.3
		# Microsoft.Owin v2.0.2 -> v3.0.1
		'/nowarn:1701', # The two assembly references have differing build and/or revision numbers
		'/nowarn:1702', # The two assembly references have differing build and/or revision numbers
	],
)
