#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'Godel.Core.dll',
	'Peach.Pro.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.Test.dll',
	'Ionic.Zip.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PitTester.exe',
)

internal = [
	# Peach
	'Peach.exe',
	'Peach.Pro.Web',

	# Peach Platform Suppoort
	'Peach.Pro.OS.Windows.dll',
	'Peach.Pro.OS.Linux.dll',
	'Peach.Pro.OS.OSX.dll',

	# Include sample programs so sample pits work
	'CrashableServer',
	'CrashingFileConsumer',
	'CrashingProgram',
	'ComTest',

	# Linux core file monitor
	'PeachLinuxCrashHandler.exe',

	# Windows side-process helpers
	'Peach.Pro.ComContainer.exe',
	'Peach.Pro.WindowsDebugInstance.exe',

	'IronPython.StdLib', # Python Standard Library
	'VMware-VIX',        # VMWare VIX API
	'CrashWrangler',     # CrashWrangler

	# Internal pit testing tools
	'nunit-console',
	'PitTester.exe',
	'Godel.Tests.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.Test.dll',
	'Peach.Pro.Test.OS.Linux.dll',
	'Peach.Pro.Test.OS.OSX.dll',
	'Peach.Pro.Test.OS.Windows.dll',
	'Peach.Pro.Test.WebApi.dll',
	'UseAfterFree',
	'CrashTest',
	'CrashTestDummy.exe',
]

variant = bld.variant \
	.replace('debug', 'internal') \
	.replace('release', 'internal')

tgt = '-'.join([ 'peach-pro', bld.env.BUILDTAG, variant ])

bld(
	features = 'zip',
	name = tgt,
	use = internal,
)
