#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'SharpPcap.dll',
	'Peach.Core.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'Godel.Core.dll',
	'Peach.Pro.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.Test.dll',
	'Ionic.Zip.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PitTester.exe',
)
