#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'SharpPcap.dll',
	'Peach.Core.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'Godel.Core.dll',
	'Peach.Pro.dll',
	'Peach.Pro.Test.dll',
]

def run_test(self):
	if self.env.CS_NAME == 'mono':
		self.ut_exec.insert(0, 'mono')

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PitTester.exe',
	ut_cwd = bld.path.find_node('../../../pits/pro').abspath(),
	ut_args = '.',
	ut_fun = run_test,
)
