language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  # Rubinius broken with "OpenURI is not a module, but a Autoload"
  #- rbx-2.1.1
#script: rake test test_us_ascii
notifications:
  email: false
  irc: "irc.freenode.org#asciidoctor"
