= Peach Professional Development

This is the current bleeding edge repo for Peach Professional.

== Current Repo's:

peach-pro:: Peach Professional Master
peach-core::
  INVISIBLE DO NOT DIRECTLY MODIFY.
  This repo is mapped into peach-pro/core. All edits and changes should be made to the peach-pro repo.
  Only Seth is allowed to migrate changes to peach-core.
pits:: 
  This repo is for all pit related work.  Contains Peach Pro Pits, internal pits and client pits.
  
epeach::
  DEPRECATED. End of life with feature-14Q2 release.
  Starting with feature-14Q3, make use of peach-pro repo.

peach::
  master -- new repo layout with peach-core mapped to master/core
  v3.1 -- sub-module of epeach. DEPRECATED.


== Submitting Pull Requests

*Guide Lines*

. Code must be owned by Deja vu Security or Peach Fuzzer, LLC. In the case of work for hire contract this may not be possible.
. Copyright must be granted to Peach Fuzzer, LLC
. Unit tests must be provided with pull request
. Correct use of logging
. All pull requests will go through a source code review

Make sure the Peach Team and specifically Michael Eddington is aware of any deadlines for getting 
pull requests accepted. For instance, if delivery of the fuzzers to an end client requires the pull request 
being accepted and a new build pushed.  It's not uncommon for pull requests to take several months to be 
accepted otherwise.

=== Logging

Peach uses NLog for logging of debug/trace messages.

Debug:: Debug messages should be used sparringly. Customers make use of --debug to identify issues in their pits. It's critical to keep this output sussinct, with only information needed by the end user displaying.
Trace:: This is the log level that should be used for output mostly wanted by Peach developers or when diagnosing a possible problem, but not something the customer would want to always see.

=== Unit Tests

All pull requests are required to have unit tests that provide reasonable coverage of all features.  NUnit is our unit testing
framework.  Prior to submitting a pull request verify all Peach unit tests are passing.  If you have a question about a 
unit test failure (is it expected or not) contact Seth or Frank on the Peach development team.

=== Documentation

All shipping code features require product documentation. This could be new documentation for a fixup or similar being added
or an update to existing documentation.  This should be co-ordinated with Mike and Richard.


