[[Brand_new_items]]
== What's new in Peach Platform v4.0 (2016 Q2)

This is our second release of 2016.
It includes a good mix of new features, improvements, and new Pits.
The new Pits are available for licensing singularly or as part of a Pit Pack.
If you are interested in using a new Pit that has been added to an existing Pit Pack already licensed,
re-download Peach Fuzzer by visiting https://dl.peachfuzzer.com.

=== Fuzzing Definitions (Pits)

Descriptions of the new Pits follow:

/////
==== DTLS Server (SSL)

DTLS is a derivation of SSL protocol.
It provides the same security services (integrity, authentication and confidentiality) as SSL/TLS but under the UDP protocol.
This pit is available as part of SSL.
/////

=== Professional/Enterprise

Descriptions of new features and improvements for Professional and Enterprise follow:

==== New Major Version

This release marks a new major version number for Peach.
It includes a number of breaking changes and deprecated elements/features.
Make sure to checkout the Breaking Changes section of Whats New.

==== PitTool

TODO

==== Fragmented Protocol Support

TODO

==== Improvements to HTTP and REST Publishers

TODO

==== APC Power Monitor

TODO

==== SNMP Power Monitor

TODO

==== Swagger Analyzer

TODO

==== Postman Analyzer

TODO

==== GDB Server Monitor

Specific support for the GDB Server protocol.
See xref:Monitors_GdbServer[GdbServer] monitor for more information.

==== GDB Script Exposed

Both GDB monitors now support changing the script used to drive GDB during fuzzing.
See xref:Monitors_Gdb[Gdb] and xref:Monitors_GdbServer[GdbServer] for more information.


=== Breaking Changes

TODO

==== Plugins Folder

TODO

==== Sample Ninja

TODO



// end
