[[Brand_new_items]]
== What's new in Peach Platform v4.0 (2016 Q2)

This is our second release of 2016.
It includes a good mix of new features, improvements, and new Pits.
The new Pits are available for licensing singularly or as part of a Pit Pack.
If you are interested in using a new Pit that has been added to an existing Pit Pack already licensed,
re-download Peach Fuzzer by visiting https://dl.peachfuzzer.com.

=== Fuzzing Definitions (Pits)

Descriptions of the new/updated Pits follow:

==== HL7 v2 XML

TODO

==== HL7 Network

TODO

==== DICOM Updates

TODO

==== SSL/TLS Expanded Cipher Support

The cipher suites supported by the SSL/TLS pits have been expanded in this release. 
The following table shows the current list of supported ciphers:

[options="header",cols="1,2,1,1,1,1,1"]
|========
|ID        | Cipher Suite                       | Prot   |Key Ex | Au   | Enc        | Mac
|0xC0,0xAC |ECDHE_ECDSA_WITH_AES_128_CCM        |TLSv1.2 |ECDH   |ECDSA |AESCCM(128) |AEAD
|0xC0,0xAE |ECDHE_ECDSA_WITH_AES_128_CCM_8      |TLSv1.2 |ECDH   |ECDSA |AESCCM(128) |AEAD
|0xC0,0xAD |ECDHE_ECDSA_WITH_AES_256_CCM        |TLSv1.2 |ECDH   |ECDSA |AESCCM(128) |AEAD
|0xC0,0xAF |ECDHE_ECDSA_WITH_AES_256_CCM_8      |TLSv1.2 |ECDH   |ECDSA |AESCCM(128) |AEAD
|0xC0,0x23 |ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 |TLSv1.2 |ECDH   |ECDSA |AES(128)    |SHA256
|0xC0,0x09 |ECDHE_ECDSA_WITH_AES_128_CBC_SHA    |TLSv1.0 |ECDH   |ECDSA |AES(128)    |SHA1
|0xC0,0x27 |ECDHE_RSA_WITH_AES_128_CBC_SHA256   |TLSv1.2 |ECDH   |RSA   |AES(128)    |SHA256
|0xC0,0x13 |ECDHE_RSA_WITH_AES_128_CBC_SHA      |TLSv1.0 |ECDH   |RSA   |AES(128)    |SHA1
|0x00,0x9C |AES128-GCM-SHA256                   |TLSv1.2 |RSA    |RSA   |AESGCM(128) |AEAD
|0x00,0x3C |AES128-SHA256                       |TLSv1.2 |RSA    |RSA   |AES(128)    |SHA256
|0x00,0x3D |AES256-SHA256                       |TLSv1.2 |RSA    |RSA   |AES(256)    |SHA256
|0x00,0x2F |AES128-SHA                          |TLSv1.0 |RSA    |RSA   |AES(128)    |SHA1
|0x00,0x35 |AES256-SHA                          |TLSv1.0 |RSA    |RSA   |AES(256)    |SHA1
|========

=== Professional/Enterprise

Descriptions of new features and improvements for Professional and Enterprise follow:

==== New Major Version

This release marks a new major version number for Peach.
It includes a number of breaking changes and deprecated elements/features.
Make sure to checkout the Breaking Changes section of Whats New.

==== PitTool

TODO

==== Fragmented Protocol Support

This release instroduces a new element and two new action types allowing fragmented protocols to be easily modeled and fuzzed.  The _Frag_ element, _outfrag_ action type, and _infrag_ action type have been added.  For more information about modeling fragmented protocols see the _Frag_ element documentation in the developer guide.

==== APC Power Monitor

The _APC Power_ monitor switches outlets on an APC power distribution unit (PDU) on and off via SNMPv1.
This monitor is useful for automatically power cycling devices during a fuzzing session.
APC's Switched Rack Power Distribution Unit (AC7900) is known to work with this monitor.

==== SNMP Power Monitor

The _SNMP Power_ monitor switches outlets on a power distribution unit (PDU) on and off via SNMPv1.
This monitor is useful for automatically power cycling devices during a fuzzing session.

==== Web Fuzzing/RESTful Fuzzing Improvments

In this release we continue to add features related to web fuzzing and specifically RESTful service fuzzing.
Changes include new analyzers to speed up creation of fuzzing definitions and also changes to the related publishers to enable fault detection on return status codes.

===== Improvements to HTTP and REST Publishers

Both the HTTP and REST publishers have been updated this release cycle:

* Fault on HTTP status code.  Status codes can be configured.
* Fail on HTTP status code. Status codes can be configured.
* Expose Headers collection for easy modification from Python scripts.

===== Swagger Analyzer

This analyzer converts Swagger API JSON into Peach Pits for fuzzing REST style web service endpoints.

link:http://swagger.io[Swagger] is a popular method for representing your RESTful API, especially for documentation purposes. Many frameworks can export Swagger API representations which can then be converted into partial pits using this analyzer.

===== Postman Analyzer

This analyzer converts Postman Collections into Peach Pits for fuzzing REST style web service endpoints.

link:https://www.getpostman.com[Postman] is a popular app used during development and testing of REST style web services. APIs are organized into Collections which can be converted into fuzzers using this analyzer.

==== GDB Server Monitor

Specific support for the GDB Server protocol.
See xref:Monitors_GdbServer[GdbServer] monitor for more information.

==== GDB Script Exposed

Both GDB monitors now support changing the script used to drive GDB during fuzzing.
See xref:Monitors_Gdb[Gdb] and xref:Monitors_GdbServer[GdbServer] for more information.

=== Breaking Changes

TODO

==== Plugins Folder

TODO

==== Sample Ninja

TODO



// end
