[[Brand_new_items]]
== What's new in Peach Platform v{VER_MAJOR}.{VER_MINOR} (2016 Q3)

This is our third release of 2016.
This release focuses on adding Web API testing capabilities. If you are interested in using a new feature that has been added to an existing license,
re-download Peach Fuzzer by visiting https://dl.peachfuzzer.com.

=== Peach FuzzFlex Licensing Model

Peach Fuzzer’s FuzzFlex solution allows organizations to scale Peach Fuzzer to meet their needs and budget. FuzzFlex users experience the full power of the platform: unlimited concurrencies, access to a library of over 100 off-the-shelf Peach Pits, developer access to support custom protocols. FuzzFlex users purchase test cases in batches of 100k.
Each test case that Peach executes is considered one 'use' of the Peach license against the
total number of test cases purchased.

Please contact sales@peachfuzzer.com for more information about this new licensing model.

=== Peach Download Site

A new download site has been deployed that supports both our existing licensing system for Professional and Enterprise users as well as our new FuzzFlex licensing system.
The new download site improves the download speed and responsiveness of the site.

=== Peach Professional/Enterprise

Descriptions of new features and improvements for Professional and Enterprise follow:

==== Web Action

A new action 'web' has been added in this release allowing for much easier modeling
of web api requests.  This action can only be used with the new WebApi publishers.
See the developer guide for more information.

==== WebApi Publisher

A new publisher has been added that supports the new 'web' action type.
See the developer guide for more information.

==== Updated Swagger Analyzer

The Swagger analyzer has been updated to generate web actions.
See the developer guide for more information.

==== Updated Postman Analyzer

The Postman analyzer has been updated to generate web actions.
See the developer guide for more information.

==== Updated WindowsDebugger Monitor

The WindowsDebugger monitor has been updated with new options to ignore first chance read A/V exceptions.
This facilitates easier usage with targets that host the JVM.
See the developer guide for more information.

==== Scripts Folder

A new top level folder +Scripts+ has been added that contains global python modules.
A new peach.webproxy module has been added to enable scripting extensions for the web proxy feature.

// end
