#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Web.dll',
]

content = [
	'bower.json',
	'Gruntfile.coffee',
	'package.json',
	'README.adoc',
	'tsd.json',
] + bld.path.ant_glob('public/ts/test/**/*.ts')

public = bld.path.ant_glob('public/**/*', excl = [
	'public/tests.html',
	'public/js/app/*',
	'public/js/test/*',
	'public/**/*.ts',
])

bld(
	features = 'tsc',
	name ='Peach.Pro.Web',
	source = 'public/ts/app/app.ts',
	install_path = '${BINDIR}',
	install_644 = public,
	ide_source = 'ReverseProxy.cs',
	ide_content = content,
	ide_aspnet = True,
	use = deps,
)
