#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Web.dll',
]

content = [
	'bower.json',
	'Gruntfile.coffee',
	'package.json',
	'README.adoc',
	'tsd.json',
]

public = bld.path.ant_glob('public/**/*', excl = [
	'public/js/app/app.js*',
	'public/js/test/test.js*',
	'public/**/*.ts',
])

bld(
	features = 'tsc',
	name ='Peach.Pro.Web',
	source = 'public/ts/app/app.ts',
	install_path = '${BINDIR}',
	install_644 = public,
	ide_source = 'ReverseProxy.cs',
	ide_content = content,
	ide_aspnet = True,
	use = deps,
	target = 'public/js/app/app.js',
)

bld(
	features = 'tsc',
	name = 'Peach.Pro.Web.Test',
	source = 'public/ts/test/reference.ts',
	ide_aspnet = True,
	target = 'public/js/test/test.js',
)
