#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'PeachFarm.Common.dll',
	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'System.Xml.dll',
	'System.Xml.Linq.dll',
	'ServiceStack.Common.dll',           
	'ServiceStack.dll',                  
	'ServiceStack.Interfaces.dll',       
	'ServiceStack.OrmLite.dll',          
	'ServiceStack.OrmLite.SqlServer.dll',
	'ServiceStack.Redis.dll',            
	'ServiceStack.ServiceInterface.dll', 
	'ServiceStack.Text.dll',             
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachFarm.Controller.dll',
)

if bld.env.MCS and bld.env.DEST_OS != "win32":
	bld.install_files('${BINDIR}','pf_controller')
