#!/usr/bin/env python
from waflib import Utils

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'PeachFarm.Common.dll',
	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'System.Xml.dll',
	'System.Xml.Linq.dll',
]

app = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachFarm.Controller.dll',
	ide_path = '../Peach Farm',
)

if bld.env.MCS and bld.env.DEST_OS != "win32":
	app.install_755 = 'pf_controller'
