#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Data.dll',
	'System.Runtime.Remoting.dll',
	'System.Xml.dll',
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Renci.SshNet.dll',
	'BouncyCastle.Crypto.dll',
	'Ionic.Zip.dll',
	'Newtonsoft.Json.dll',
	'SocketHttpListener.dll',
	'Dapper.dll',
	'Aspose.Words.dll',
]

if bld.env.TARGET == 'win':
	deps.extend([
		'System.Data.SQLite.dll',
	])
else:
	deps.extend([
		'Mono.Data.Sqlite.dll',
	])

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name = 'Peach.Pro.Test.dll',
	resource = bld.path.ant_glob('Resources/**/*'),
	ide_use = 'CrashingProgram CrashingFileConsumer CrashableServer',
	namespace = 'Peach.Pro.Test.Core',
)
