#!/usr/bin/env python

deps = [
	'Aspose.Words.dll',
	'BouncyCastle.Crypto.dll',
	'Castle.Core.dll',
	'Dapper.dll',
	'FlxClientCommon.dll',
	'FlxLicensingClient.dll',
	'FlexNet.Operations.dll',
	'Ionic.Zip.dll',
	'komodo_net.dll',
	'Managed.Adb.dll',
	'Mono.Posix.dll',
	'Moq.dll',
	'Newtonsoft.Json.dll',
	'NLog.dll',
	'nunit.framework.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Peach.Pro.PitTester.dll',
	'Portable.Licensing.dll',
	'Renci.SshNet.dll',
	'SharpSnmpLib.Full.dll',
	'SharpSnmpLib.Portable.dll',
	'SharpPcap.dll',
	'SocketHttpListener.dll',
	'System.dll',
	'System.Configuration.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Data.SQLite.dll',
	'System.Runtime.Remoting.dll',
	'System.Web.Services.dll',
	'System.Xml.dll',
]

top = bld.path.parent.parent.parent
flexnet = 'flexnet_client-2016.03.0'

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name = 'Peach.Pro.Test.dll',
	resource = bld.path.ant_glob('Resources/**/*'),
	ide_use = 'CrashingProgram CrashingFileConsumer CrashableServer CrashTest',
	namespace = 'Peach.Pro.Test.Core',
	install_644 = {
		top.find_or_declare('/'.join(['3rdParty', flexnet, bld.env.BASENAME])) :
		top.ant_glob('/'.join(['3rdParty', flexnet, bld.env.BASENAME, '**']))
	}
)
