#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'System.dll',
	'System.Core.dll',
	'System.Runtime.Remoting.dll',
	'System.Xml.dll',
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Renci.SshNet.dll',
	'BouncyCastle.Crypto.dll',
	'Ionic.Zip.dll',
	'Newtonsoft.Json.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Pro.Test.dll',
	resource = 'google.der',
	ide_use = 'CrashingProgram CrashingFileConsumer CrashableServer',
)
