// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>PeachFarm.Common.Mongo</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace PeachFarm.Common.Mongo
{
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using System.Collections.Generic;


	public partial class Job
	{

		private string userNameField;

		private string pitFileNameField;

		private string jobIDField;

		private System.DateTime startDateField;

		public string UserName
		{
			get
			{
				return this.userNameField;
			}
			set
			{
				this.userNameField = value;
			}
		}

		public string PitFileName
		{
			get
			{
				return this.pitFileNameField;
			}
			set
			{
				this.pitFileNameField = value;
			}
		}

		public string JobID
		{
			get
			{
				return this.jobIDField;
			}
			set
			{
				this.jobIDField = value;
			}
		}

		public System.DateTime StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}
	}

	public partial class Iteration
	{

		private uint iterationNumberField;

		private string testNameField;

		private uint seedNumberField;

		private System.DateTime stampField;

		private List<Fault> faultsField;

		private string jobIDField;

		private string nodeNameField;

		public Iteration()
		{
			this.faultsField = new List<Fault>();
		}

		public uint IterationNumber
		{
			get
			{
				return this.iterationNumberField;
			}
			set
			{
				this.iterationNumberField = value;
			}
		}

		public string TestName
		{
			get
			{
				return this.testNameField;
			}
			set
			{
				this.testNameField = value;
			}
		}

		public uint SeedNumber
		{
			get
			{
				return this.seedNumberField;
			}
			set
			{
				this.seedNumberField = value;
			}
		}

		public System.DateTime Stamp
		{
			get
			{
				return this.stampField;
			}
			set
			{
				this.stampField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayAttribute(Order = 4)]
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public List<Fault> Faults
		{
			get
			{
				return this.faultsField;
			}
			set
			{
				this.faultsField = value;
			}
		}

		public string JobID
		{
			get
			{
				return this.jobIDField;
			}
			set
			{
				this.jobIDField = value;
			}
		}

		public string NodeName
		{
			get
			{
				return this.nodeNameField;
			}
			set
			{
				this.nodeNameField = value;
			}
		}
	}

	public partial class Fault
	{

		private bool isReproductionField;

		private bool controlIterationField;

		private bool controlRecordingIterationField;

		private string descriptionField;

		private string detectionSourceField;

		private string exploitabilityField;

		private string folderNameField;

		private uint iterationField;

		private string majorHashField;

		private string minorHashField;

		private string titleField;

		private string faultTypeField;

		private List<Action> stateModelField;

		private List<CollectedData> collectedDataField;

		public Fault()
		{
			this.collectedDataField = new List<CollectedData>();
			this.stateModelField = new List<Action>();
		}

		public bool IsReproduction
		{
			get
			{
				return this.isReproductionField;
			}
			set
			{
				this.isReproductionField = value;
			}
		}

		public bool ControlIteration
		{
			get
			{
				return this.controlIterationField;
			}
			set
			{
				this.controlIterationField = value;
			}
		}

		public bool ControlRecordingIteration
		{
			get
			{
				return this.controlRecordingIterationField;
			}
			set
			{
				this.controlRecordingIterationField = value;
			}
		}

		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		public string DetectionSource
		{
			get
			{
				return this.detectionSourceField;
			}
			set
			{
				this.detectionSourceField = value;
			}
		}

		public string Exploitability
		{
			get
			{
				return this.exploitabilityField;
			}
			set
			{
				this.exploitabilityField = value;
			}
		}

		public string FolderName
		{
			get
			{
				return this.folderNameField;
			}
			set
			{
				this.folderNameField = value;
			}
		}

		public uint Iteration
		{
			get
			{
				return this.iterationField;
			}
			set
			{
				this.iterationField = value;
			}
		}

		public string MajorHash
		{
			get
			{
				return this.majorHashField;
			}
			set
			{
				this.majorHashField = value;
			}
		}

		public string MinorHash
		{
			get
			{
				return this.minorHashField;
			}
			set
			{
				this.minorHashField = value;
			}
		}

		public string Title
		{
			get
			{
				return this.titleField;
			}
			set
			{
				this.titleField = value;
			}
		}

		public string FaultType
		{
			get
			{
				return this.faultTypeField;
			}
			set
			{
				this.faultTypeField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayAttribute(Order = 12)]
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public List<Action> StateModel
		{
			get
			{
				return this.stateModelField;
			}
			set
			{
				this.stateModelField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayAttribute(Order = 13)]
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public List<CollectedData> CollectedData
		{
			get
			{
				return this.collectedDataField;
			}
			set
			{
				this.collectedDataField = value;
			}
		}
	}

	public partial class Action
	{

		private string actionNameField;

		private string actionTypeField;

		private int parameterField;

		private byte[] dataField;

		private string dataPathField;

		public string ActionName
		{
			get
			{
				return this.actionNameField;
			}
			set
			{
				this.actionNameField = value;
			}
		}

		public string ActionType
		{
			get
			{
				return this.actionTypeField;
			}
			set
			{
				this.actionTypeField = value;
			}
		}

		public int Parameter
		{
			get
			{
				return this.parameterField;
			}
			set
			{
				this.parameterField = value;
			}
		}

		public byte[] Data
		{
			get
			{
				return this.dataField;
			}
			set
			{
				this.dataField = value;
			}
		}

		public string DataPath
		{
			get
			{
				return this.dataPathField;
			}
			set
			{
				this.dataPathField = value;
			}
		}
	}

	public partial class CollectedData
	{

		private string keyField;

		private byte[] dataField;

		private string dataPathField;

		public string Key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}

		public byte[] Data
		{
			get
			{
				return this.dataField;
			}
			set
			{
				this.dataField = value;
			}
		}

		public string DataPath
		{
			get
			{
				return this.dataPathField;
			}
			set
			{
				this.dataPathField = value;
			}
		}
	}
}
