#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'System.Runtime.Serialization.dll'
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PeachFarm.Common.dll',
)
