[[Transformers_Base64DecodeTransformer]]
== Base64DecodeTransformer

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO: 
// Verify parameters expand parameter description 
// Full pit example using hex console 
// expand  general description 
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format 
// Test output, input

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

=== Transformer type: Encoder/Decoder

The _Base64DecodeTransformer_ will Base64 decode the value in the parent xref:DataModel[DataModel]. The xref:Transformer[Transformer] can bidirectionally encode data as well as decode data. Note an output operation 

=== Parameters 

No Parameters are supported by this element.

=== Attributes

_Required:_

There are no required attributes.

_Optional:_

There are no optional attributes.

=== Actions Supported 

 * xref:Action_input[input]
 * xref:Action_output[output]
 * xref:Action_call[call]
 * xref:Action_getProperty[getProperty] 
 * xref:Action_setProperty[setProperty]

=== Examples

.Decoding Value To and From File Example
==========================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<String value="Plaintext: " token="true"/>
		<String name="TransformMe" value="QUJDREVGR0g=">
			<Transformer class="Base64Decode" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Plaintext Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>
			
			<!-- Write Plaintext Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
				<Data>
					<Field name="TransformMe" value="QUJDREVGR0g=" />
				</Data>
			</Action>
			<Action type="close" publisher="FilePubWrite" />
			
			<!-- Read and encode Plaintext file and slurp Base64 string to output in console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>
			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//StringValue" />
			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<String name="StringValue" />
				</DataModel>
			</Action>
			
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" name="ConsolePub"/>
		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="encoded.bin" />
		</Publisher>
		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="encoded.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>

		<Logger class="File">
			<Param name="Path" value="logs"/> 
		</Logger>
	</Test>
</Peach>
----


Output from this example.
----
> peach -1 --debug example.xml


----
==========================