[[Transformers_Bz2DecompressTransformer]]
== Bz2DecompressTransformer

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO: 
// Verify parameters expand parameter description 
// Full pit example using hex console 
// expand  general description 
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format 
// Test output, input

// Updated:
// 2/20/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

=== Transformer type: Compress

The _Bz2DecompressTransformer_ performs a bzip2 decompression on the value in the parent xref:DataModel[DataModel]. 
The xref:Transformer[Transformer] can bidirectionally compress data as well as decompress data.

=== Parameters 

No Parameters are supported by this element.

=== Actions Supported 

 * xref:Action_input[input]
 * xref:Action_output[output]
 * xref:Action_call[call]
 * xref:Action_getProperty[getProperty] 
 * xref:Action_setProperty[setProperty] 

=== Examples

[source,xml]
----
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<Blob name="TransformMe" value="42 5A 68 39 31 41 59 26 53 59 A7 83 53 78 00 00 0D 81 80 22 6F 58 00 20 00 31 00 D3 4D 01 55 03 41 EA 5D 4D A1 1E 44 47 51 18 7C 5D C9 14 E1 42 42 9E 0D 4D E0" valueType="hex" >
			<Transformer class="Bz2Decompress" />
		</Blob>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Encrypted Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>
			
			<!-- Write Encrypted Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
			</Action>
			<Action type="close" publisher="FilePubWrite" />
			
			<!-- Read and decrypt encrypted file and slurp output to console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>
			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//BlobValue" />
			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<Blob name="BlobValue" />
				</DataModel>
			</Action>
					
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" name="ConsolePub"/>
		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="encrypted.bin" />
		</Publisher>
		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="encrypted.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>
	</Test>
</Peach>
----
