<<<
[[Transformers_CvsScramble]]
== CvsScramble

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output, input

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Cryptography

_CvsScramble_ performs a pserver password scramble on the given value. 

The xref:Transformer[Transformer] can bidirectionally encrypt and decrypt data.

=== Parameters

None.

=== Attributes

None.

=== Actions Supported

xref:Action_input[input]:: On input this, transformer decrypts the incoming data.
xref:Action_output[output]:: On output this, transformer encrypts the outgoing data.

=== Examples

.Simple Encrypt Example
==========================
This example uses CvsScramble on an inline value and writes the transformed value to a file, reads the value from a file, and outputs it to the console.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<String name="TransformMe" value="superdoopersecret">
			<Transformer class="CvsScramble" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Encoded Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>

			<!-- Write Encoded Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
				<Data>
					<Field name="TransformMe" value="superdoopersecret" />
				</Data>
			</Action>

			<Action type="close" publisher="FilePubWrite" />

			<!-- Read and decode encoded file and slurp decoded string to output in console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>

			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//StringValue" />

			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<String name="StringValue" />
				</DataModel>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>

		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="encrypted.bin" />
		</Publisher>

		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="encrypted.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>

		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----


Output from this example.
----
> peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Peach Fuzzer LLC

[*] Test 'Default' starting with random seed 4965.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(18 bytes)
00000000   41 5A 62 3A 64 20 65 30  30 3A 64 20 5A 64 68 20   AZb:d e00:d Zdh
00000010   64 2C                                              d,
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher output(18 bytes)
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Input
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher input()
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker DataModel 'InputModel' Bytes: 0/18, Bits: 0/144
Peach.Core.Cracker.DataCracker getSize: -----> DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.TransformMe' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker getSize: <----- Deterministic: ???
Peach.Core.Cracker.DataCracker Crack: DataModel 'InputModel' Size: <null>, Bytes : 0/18, Bits: 0/144
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'InputModel.TransformMe' Bytes: 0/18, Bits : 0/144
Peach.Core.Cracker.DataCracker getSize: -----> String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.TransformMe' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker lookahead: String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker getSize: <----- Last Unsized: 144
Peach.Core.Cracker.DataCracker Crack: String 'InputModel.TransformMe' Size: 136, Bytes: 0/17, Bits: 0/136
Peach.Core.Dom.DataElement String 'InputModel.TransformMe' value is: superdoopersecret
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Slurp
Peach.Core.Dom.Action Slurp, setting OutputModel.StringValue from InputModel.TransformMe
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(17 bytes)
00000000   73 75 70 65 72 64 6F 6F  70 65 72 73 65 63 72 65   superdoopersecre
00000010   74                                                 t
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Publishers.FilePublisher stop()
Peach.Core.Publishers.FilePublisher stop()

[*] Test 'Default' finished.
----
==========================