[[Transformers_GzipDecompressTransformer]]
== GzipDecompressTransformer

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO: 
// Verify parameters expand parameter description 
// Full pit example using hex console 
// expand  general description 
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format 
// Test output, input

// Updated:
// 2/20/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

=== Transformer type: Compress

The _GzipDecompressTransformer_ performs a gzip decompression on the value in the parent xref:DataModel[DataModel]. The xref:Transformer[Transformer] can bidirectionally compress data as well as decompress data.

=== Parameters 

No Parameters are supported by this element.

=== Attributes

_Required:_

There are no required attributes.

_Optional:_

There are no optional attributes.

=== Actions Supported 

 * xref:Action_input[input]
 * xref:Action_output[output]
 * xref:Action_call[call]
 * xref:Action_getProperty[getProperty] 
 * xref:Action_setProperty[setProperty] 

=== Examples

.Compression To and From File Example 
==========================
This example uses the GzipCompress Transformer to compress a value, write the value to the console, write to a file, and then reads it from the file to the console. 

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1"> 
		<Blob name="TransformMe" value="1F 8B 08 00 00 00 00 00 04 00 EC BD 07 60 1C 49 96 25 26 2F 6D CA 7B 7F 4A F5 4A D7 E0 74 A1 08 80 60 13 24 D8 90 40 10 EC C1 88 CD E6 92 EC 1D 69 47 23 29 AB 2A 81 CA 65 56 65 5D 66 16 40 CC ED 9D BC F7 DE 7B EF BD F7 DE 7B EF BD F7 BA 3B 9D 4E 27 F7 DF FF 3F 5C 66 64 01 6C F6 CE 4A DA C9 9E 21 80 AA C8 1F 3F 7E 7C 1F 3F 22 9A 79 5D 2C DF 2E F2 55 99 67 4D 1E FE F5 FF 04 00 00 FF FF 32 B6 7E 40 1C 00 00 00" valueType="hex">
			<Transformer class="GzipDecompress" />
		</Blob>
	</DataModel> 

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Decompressed Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>
			
			<!-- Write Decompressed Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
			</Action>
			<Action type="close" publisher="FilePubWrite" />
			
			<!-- Read and decompress file and slurp output to console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>
			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//BlobValue" />
			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<Blob name="BlobValue" />
				</DataModel>
			</Action>
					
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" name="ConsolePub"/>
		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="decompressed.bin" />
		</Publisher>
		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="decompressed.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>
	</Test>
</Peach>
----

Output from this example.
----
> peach -1 --debug example.xml


----
==========================