<<<
[[Transformers_MD5Transformer]]
== MD5Transformer

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

=== Transformer type: Cryptography

The _MD5Transformer_ creates an MD5 hash of the value in the parent xref:DataModel[DataModel].
This xref:Transformer[Transformer] can only be applied to outgoing data as it is a fundamental principle of hashes that the operation be one-way.

=== Parameters

No Parameters are supported by this transformer.

=== Attributes

No Attributes are supported by this transformer.

=== Actions Supported

 * xref:Action_output[output]:: On output this transformer will hash the outgoing data.

=== Examples

.Simple Console Example
==========================
This example uses the MD5 transformer on an inline value and writes the transformed value to the console.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<Block name="Main">
			<String name="TransformMe" value="superdoopersecret">
				<Transformer class="Md5" />
			</String>
		</Block>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Encrypted Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>

		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----


Output from this example.
----
> peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 58687.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(16 bytes)
00000000   04 9B F0 86 41 46 4B 3F  3D 49 95 6D D0 81 12 BA   ????AFK?=I?m????
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================