== Licensing

{product} is licenses in two ways depending on how it's purchased.
When purchased directly through Peach Fuzzer, LLC, {product} is 
licensed per instance.
When purchased through a cloud provider marketplace billing occurs through
the marketplace itself for each instance that is started.

This chapter is intended for purchases made directly through Peach Fuzzer, LLC
as cloud marketplace purchases are automatically licensed.

For instances purchased through Peach Fuzzer, LLC, each instance must be activated through our licensing system.
When the instance is destroyed, it's license must be returned before it can be used again.

=== License Types

{product} has two purchase options that enable different features of the product.

{product} {skubasic}::
The {skubasic} version of {product} contains all features with the exception
of the fuzzing modules.  This covers OWASP Top 10 and PCI 6.5, but does not
perform additional fuzz testing.
+
The checks/asserts not included with this licenses will be shown as disabled
in the project/profile configuration.

{product} {skuadvanced}::
    The {skuadvanced} version of {product} expands the {skubasic} feature set
    adding in fuzzing of web apis.

=== Licensing Concepts

Activation ID::
Activation IDs are used to license {product} instances.
Each purchased instance will receive it's own activation ID.
Activation IDs can be found via the link:{portalurl}[{product} Portal]
on the licensing page.

Device ID::

==== How to identify unused activation IDs

TODO

==== How to find instance device ID

TODO


include::02_Activation/00_Section.adoc[]

=== Reclaim license/Returning Device

TODO

=== Licensing Expiring Warning

TODO

=== How to purchase additional licenses

TODO
