#!/usr/bin/env python

deps = [
	'NLog.dll',
	'nunit.framework.dll',
	'System.dll',
	'System.Core.dll',
	'System.Runtime.Remoting.dll',
	'System.Xml.dll',
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Community.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Renci.SshNet.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Community.Test.dll',
	ide_use = 'CrashingProgram CrashingFileConsumer CrashableServer',
	ide_path = '../',
)
