<<<
[[Monitors_PageHeap]]
== PageHeap Monitor (Windows)

*Monitor Category*: *Fault detection*

The _PageHeap_ monitor enables heap allocation monitoring for an executable through the Windows debugger. Peach sets and clears the parameters used for monitoring heap allocation at the beginning and end of the fuzzing session.

NOTE: The _PageHeap_ monitor requires heightened or administrative permissions to run.

=== Parameters

_Required:_

Executable:: Executable name (no path)

_Optional:_

WinDbgPath:: Path to the Windows Debugger installation. If not provided, Peach attempts to locate the directory.

=== Examples

ifdef::peachug[]

.Enable for Notepad +
====================

This parameter example is from a setup that monitors heap allocation in Notepad. The example a
common setup in which both the PageHeap and the Windows Debug monitors are configured for the
fuzzing run.

_PageHeap Monitor Parameters_
[cols="2,4" options="header",halign="center"]
|==========================================================
|Parameter    |Value
|Executable   |`notepad.exe`
|==========================================================

_Windows Debugger Monitor Parameters_
[cols="2,4" options="header",halign="center"]
|==========================================================
|Parameter    |Value
|Executable   |`notepad.exe`
|Arguments    |`fuzzed.txt`
|StartOnCall  |`launchProgram`
|==========================================================

====================

endif::peachug[]


ifndef::peachug[]


.Enable for Notepad
========================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
      <Action type="close"/>
      <Action type="call" method="launchProgram" publisher="Peach.Agent"/>
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="WindowsDebugger">
        <Param name="Executable" value="notepad.exe"/>
        <Param name="Arguments" value="fuzzed.txt"/>
        <Param name="StartOnCall" value="launchProgram"/>
    </Monitor>
    <Monitor class="PageHeap">
      <Param name="Executable" value="notepad.exe" />
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Peach Fuzzer LLC

[*] Test 'Default' starting with random seed 5090.
Peach.Core.Agent.Agent StartMonitor: Monitor WindowsDebugger
Peach.Core.Agent.Agent StartMonitor: Monitor_1 PageHeap
Peach.Core.Agent.Agent SessionStarting: Monitor
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid SessionStarting
Peach.Core.Agent.Agent SessionStarting: Monitor_1

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher output(32 bytes)
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Call
Peach.Core.Agent.AgentManager Message: Action.Call => launchProgram
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid Cpu is idle, stopping process.
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid DetectedFault()
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid DetectedFault() - No fault detected
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.FilePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor_1
Peach.Core.Agent.Agent SessionFinished: Monitor
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid SessionFinished
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _FinishDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _FinishDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger

[*] Test 'Default' finished.
----
========================

endif::peachug[]
