<<<
[[Monitors_Socket]]
== Socket Monitor

*Monitor Category*: *Fault detection*

The _Socket_ monitor waits for an incoming TCP or UDP connection. This monitor accepts
a point-to-point connection to a single host or a multicast connection where the host broadcasts to
one or more clients. Multicast connections are not supported when using the TCP protocol.

If a connection is accepted, _Socket_ raises a fault if the +FaultOnSuccess+ parameter is specified.

=== Parameters

_Required:_

None.

_Optional:_

Host:: IP address of remote host, defaults to "".
Interface:: IP address of interface to listen on, defaults to 0.0.0.0.
Port:: Port to listen on, defaults to 8080.
Protocol:: Protocol type to listen for, defaults to tcp.
Timeout:: Length of time to wait for incoming connection, defaults to 1000 ms.
FaultOnSuccess:: Fault if no connection is recorded, defaults to false.

=== Examples

ifdef::peachug[]

.Listen for Incoming Connection
====================

This parameter example is from a setup that listens for a connection request on port 53.

[cols="2,4" options="header",halign="center"]
|==========================================================
|Parameter    |Value
|Port         |`53`
|==========================================================
====================

endif::peachug[]


ifndef::peachug[]


.Listen for Incoming Connection
===============================

This example listens for a connection request on port 53.

NOTE: If you want to run this example and generate a fault after starting Peach, you can use NetCat or a similar application to  generate a fault.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="Local">
	<Monitor class="Socket">
		<Param name="Port" value="53" />
	</Monitor>
  </Agent>


  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output for this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Peach Fuzzer LLC

[*] Test 'Default' starting with random seed 20168.
Peach.Core.Agent.Agent StartMonitor: Monitor Socket
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----

To stimulate this monitor to cause a fault, run the following command after starting Peach:

----
nc -vv 127.0.0.1 53
----

===============================

endif::peachug[]
