#!/usr/bin/env python

deps = [
	'NLog.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

app = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PeachWorker.exe',
	ver_product = 'Peach Fuzzing Worker',
)
