#!/usr/bin/env python

import os
from waflib import Task

deps = [
	'NLog.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'SharpPcap.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

top = bld.path.parent.parent

#def glob_from(*parts):
#	path = os.path.join(*parts)
#	return (
#		top.find_or_declare(path),
#		top.ant_glob(os.path.join(path, '**'))
#	)

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PeachAgent.exe',
)

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	app.install_755 = 'peachagent'

# end
