#!/usr/bin/env python

deps = [
	'NLog.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'SharpPcap.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

app = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PeachAgent.exe',
	ver_product = 'Peach Agent',
)

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	app.install_755 = 'peachagent'
