#!/usr/bin/env python

deps = [
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'mscorlib.dll',
	'PeachFarm.Common.dll',
	'System.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.Windows.Forms.dll',
	'Telerik.Reporting.dll',
]

bld(
	features = 'cs win',
	use = deps,
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name='PeachFarm.Reporting.Reports.dll',
)
