#!/usr/bin/env python

deps = [
	'nunit.framework.dll',
	'NLog.dll',
	
	'System.dll',
	'System.Core.dll',

	'Peach.Core.dll',
	'Peach.Core.Test.dll',

	'Peach.Pro.dll',
	'Peach.Pro.WebApi.dll',

	'Nancy.dll',
	'Nancy.Testing.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Pro.Test.WebApi.dll',
	csdoc = False,
)
