#!/usr/bin/env python

deps = [
	'nunit.framework.dll',
	'NLog.dll',
	
	'System.dll',
	'System.Core.dll',
	'System.Net.Http.dll',
	'System.Web.Http.dll',

	'Peach.Core.dll',
	'Peach.Core.Test.dll',

	'Peach.Pro.dll',
	'Peach.Pro.WebApi2.dll',

	'Newtonsoft.Json.dll',

	'Moq.dll',
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Pro.Test.WebApi.dll',
	csdoc = False,
)
