#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Configuration.Install.dll',
	'System.ServiceProcess.dll',
	'NLog.dll',
	'PeachFarm.Reporting.dll',
	'PeachFarm.Common.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachFarm.Reporting.Service.exe',
	ide_path = '../Peach Farm',
)
