=== Development/Engineering Team

For teams building web services and web APIs, integration into the CI 
system or automated test system provides a lot of advantages over 
traditional web testing processes.

 * Immediate feedback.
When security testing occurs with every build, security issues are found and fixed much faster.
 
 * Lower cost of fixing security issues.
The cost to fix a security issue increases as time between when it was authored and discovered grows.
By providing immediate feedback, the time between write and fix is shortened.

 * Lower Cost of Ownership.
Re-purposing existing automated tests removes the need to maintain configurations for each API.
Re-using existing tests also quickly provides high test coverage with little effort.

A typical deployment includes the following components:

CI integration::
The CI system's pipeline is configured to include {product} testing with specific types of builds.
For example, nightly builds might be configured to run {product} testing for 2 hours each night.
If security testing fails during those 2 hours, the build would be marked as such, similar to failing
automated tests.
+ 
For more information see the xref:CI[CI Integration] section of the User Guide.

Traffic Generator::
+
A traffic generator is needed to produce requests that are then tested and/or fuzzed.
Traffic generators will replay the same traffic over and over allowing {product} to modify them as
needed to perform testing.
+
The xref:TrafficGen[Traffic Generator] section provides more information about what is needed.
+
There are two common methods:
+
Automated Test Integration;;
+
Use existing test automation with one of Peach's framework integrations such as JUnit or pytest.
The use of existing test automation provides a fast way to get {product} running.
+
Custom Traffic Generator;;
+
A custom traffic generator can also be used.
These are custom written scripts in any language (python, java, nodejs, etc.).
A simple custom traffic generator might be a loop around a set of API calls.

Issue Tracker Integration::
Peach can automatically log found faults into popular issue trackers such as JIRA or Bugzilla.
The scripts and documentation are provided in _SDK/tools/peach2bugzilla_ and _SDK/tools/peach2jira_.
+
For more information see the xref:IssueTracker[Issue Tracker Integration] section of the User Guide.

