#!/usr/bin/env python

deps = [
    'Peach.Core.dll',
    'NLog.dll',
    'System.dll',
    ]

bld(
    features = 'cs',
    use = deps,
    source = bld.path.ant_glob('**/*.cs'),
    name='CiscoCDPFixups.dll',
    )

