#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Configuration.Install.dll',
	'System.Data.dll',
	'PeachFarm.Controller.dll',
	'System.ServiceProcess.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name='PeachFarm.Controller.Service.exe',
)
