#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Configuration.Install.dll',
	'System.Data.dll',
	'PeachFarm.Controller.dll',
	'System.ServiceProcess.dll',
	'PeachFarm.Common.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	name='pf_controller.exe',
	namespace = 'PeachFarm.Controller.Service',
	install_644 = 'controller.config.template',
	ide_path = '../Peach Farm',
)
