#!/usr/bin/env python

subdirs = [
	'ComContainer',
	'Core',
	'FuzzBang',
	'Godel',
	'LinuxCrashHandler',
	'NetworkFuzzer',
	'OS/Linux',
	'OS/OSX',
	'OS/Windows',
	'Peach',
	'SampleNinja',
	'SDK',
	'Test/Apps/ComTest',
	'Test/Apps/CrashableServer',
	'Test/Apps/CrashingFileConsumer',
	'Test/Apps/CrashingProgram',
	'Test/Core',
	'Test/Godel',
	'Test/OS/Linux',
	'Test/OS/OSX',
	'Test/OS/Windows',
	'Test/PitTester',
	'Validator',
	'Web',
	'WindowsDebugInstance',
	'XmlGenerator',
]

bld.recurse(subdirs)
