#!/usr/bin/env python

subdirs = [
	'ComContainer',
	'Core',
	'FlexNet/Library',
	'FlexNet/Tool',
	'NetworkFuzzer',
	'OS/UnixTrampoline',
	'Peach',
	'PeachAgent',
	'PeachPcapTool',
	'PeachWebRecorder',
	'PitTester',
	'PitTool',
	'Service',
	'SDK',
	'Test/Apps/AsanTest',
	'Test/Apps/ComTest',
	'Test/Apps/CrashableServer',
	'Test/Apps/CrashingFileConsumer',
	'Test/Apps/CrashingProgram',
	'Test/Apps/CrashingService',
	'Test/Apps/CrashTest',
	'Test/Apps/CrashTestDummy',
	'Test/Apps/SimpleHttpServer',
	'Test/Core',
	'Test/OS/Linux',
	'Test/OS/OSX',
	'Test/OS/Windows',
	'Test/WebApi',
	'Validator',
	'Web',
	'WebApi2',
	'Worker',
	'XmlGenerator',
]

# Only build can tool on windows
if bld.env.BASENAME.startswith('win_'):
	subdirs.append('PeachCanTool')

if bld.env.BASENAME == 'web':
	subdirs = [ 'Core' ]

bld.recurse(subdirs)

# end
