[[Check_FrameworkDebugMode]]
== Framework Debug Mode

// TODO
[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration[2013-A5-Security Misconfiguration]
| CWE | link:https://cwe.mitre.org/data/definitions/285.html[CWE-285: Improper Authorization]
| PCI | 6.5.8 Improper access control
|====

Tests to see if debug mode is enabled in various frameworks.  
Debug mode can allows various amounts of access, from simple extended error messages through command execution.
Leaving debug mode on in production deployments represents a serious risk.

Frameworks Supported:

 * ASP.NET
 * Flask
 
If your framework has a debug mode and is not listed, please email our support alias {supportemail}.
We are actively looking to expand this check with additional framework support.

=== Configuration

This check is not configurable.

=== Operation

|====
| Test generation | Endpoint Scope
|====

This is a mutational check that produces test cases by modifying requests made by the traffic generator.
