[[Check_InsecureHttpMethods]]
== Insecure HTTP Methods

[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration[2013-A5-Security Misconfiguration]
| CWE | link:https://cwe.mitre.org/data/definitions/200.html[CWE-200: Information Exposure]
| PCI | N/A
|====

Check for variouse HTTP methods that are considered insecure for variouse reasons (see configuration section).

=== Configuration

Check Options::
+
Enable/disable checking for OPTIONS HTTP method.
+
The OPTIONS method is a low severity information disclosure issue.
+
Some API designers are using OPTIONS to allow for self discovery of resource
actions.  This is a non-standard use for OPTIONS and is not wide spread at time
of writing.  If OPTIONS is used for this purpose, this portion of the check can
be disabled.

Check Trace::
+
Enable/disable checking for TRACE HTTP method.
+
The TRACE HTTP method can be used along with other client side issues to leak sensitive headers.

Check Arbitrary::
+
Enable/disable checking for arbitrary HTTP methods.
+
Arbitrary HTTP methods can be used to bypass authentication or other program restrictions.
They are typically treated as GET requests by most servers/frameworks.
This can lead to internal logic confusion.

=== Operation

|====
| Test generation | Resource Scope
|====

This is a mutational check that produces test cases by modifying requests made by the traffic generator.
