[[Check_JsonInjection]]
== JSON Injection Check

[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A1-Injection[2013-A1-Injection]
| CWE | link:https://cwe.mitre.org/data/definitions/929.html[CWE-929: OWASP Top Ten 2013 Category A1 - Injection]
| PCI | 6.5.1 Injection flaws
|====

JSON Injection is an attack technique used to manipulate or compromise the 
logic of a JSON application or service. The injection of unintended JSON content 
and/or structures into a JSON message can alter the intended logic of the 
application. Further, JSON injection can cause the insertion of malicious content 
into the resulting message/document.

This check injects various special JSON characters that demonstrate an injection issue.  
The response is then analyzed to determine if the JSON injection has been included in any
response body identified as containing JSON.

The check comes pre-populated with a list of JSON injections.
The provided list can be editted to add, edit or remove entries.

=== Configuration

Force Running:: Force running check, even if JSON was not detected in response.
Injections:: List of injections that are used by check.

=== Operation

|====
| Test generation | Parameter Scope
|====

This is a mutational check that produces test cases by modifying requests made by the traffic generator.
