[[Check_SensitiveInfo]]
== Sensitive Information Check

[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure[2013-A6-Sensitive Data Exposure]
| CWE | link:https://cwe.mitre.org/data/definitions/200.html[CWE-200: Information Exposure] +
| PCI | 6.5.5 Information leakage and improper error handling
|====

Information Leakage is an application weakness where an application reveals sensitive data.  
Examples include technical details of the web application, environment, or user-specific data. 
Sensitive data may be used by an attacker to exploit the target web application, its hosting 
network, or its users. Therefore, leakage of sensitive data should be limited or prevented 
whenever possible. Information Leakage, in its most common form, is the result of one or more 
of the following conditions: A failure to scrub out HTML/Script comments containing sensitive 
information, improper application or server configurations, or differences in page responses 
for valid versus invalid data.

This check performs analysis of API responses and log messagess to detect the following:

* Database error messages
* Framework/server error messages
* Sensitive PII
* Version dislosure

The check comes pre-populated with a large list of regular expressions that are matched against
responses and log messages.
The provided list can be editted at various scope levels (Global, Project, Profile, Route) to 
add, edit or remote entries.

=== Configuration

This check is not configurable.

=== Operation

|====
| Passive on all requests | No test generation | No traffic generation
|====

This is a global check, global checks operate on all responses and log messages for the defined scope
(project or route).  Each response is analyzed to detect any configured regex matches.

