[Check_SensitiveFile]
== Sensitive File Check

[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure[2013-A6-Sensitive Data Exposure]
| CWE | https://cwe.mitre.org/data/definitions/200.html[CWE-200: Information Exposure] +
| PCI | 6.5.5 Information leakage and improper error handling
|====

Information Leakage is an application weakness where an application reveals sensitive data,
such as technical details of the web application, environment, or user-specific data.
Sensitive data may be used by an attacker to exploit the target web application, its hosting
network, or its users. Therefore, leakage of sensitive data should be limited or prevented
whenever possible. Information Leakage, in its most common form, is the result of one or more
of the following conditions: A failure to scrub out HTML/Script comments containing sensitive
information, improper application or server configurations, or differences in page responses
for valid versus invalid data. 

For this check the weakness is one or more files and/or folders being accessable that should 
not be.
This can include files common in home folders like such as command histories or files that
contain secrets such as passwords.

The check comes pre-populated with a list of common files/folders to checkfor.
The provided list can be editted at various scope levels (Global, Project, Profile, Route) to add, edit or remote entries.

Detection is based on result code.
If default error pages are used with a successful result code, a regular expression can be
used to detect the error page instead of status code.

=== Configuration

TODO

=== Operation

|====
| Test generation 
|====

This is a mutational check that produces test cases by modifying requests made by the traffic generator.
