[[Check_SessionCookie]]
== Session Cookie Check

[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure[2013-A2-Broken Authentication and Session Management]
| CWE | https://www.owasp.org/index.php/Top_10_2013-A2-Broken_Authentication_and_Session_Management[CWE-930: OWASP Top Ten 2013 Category A2 - Broken Authentication and Session Management] +
| PCI | 6.5.10 Broken authentication and session management
|====

Since HTTP is a stateless protocol, Web sites commonly use cookies to store session 
IDs that uniquely identify a user from request to request. Consequently, each 
session ID's confidentiality must be maintained in order to prevent multiple users 
from accessing the same account. A stolen session ID can be used to view another 
user's account or perform a fraudulent transaction.

One part of securing session ID's is to property mark them to expire and also require
the correct set of flags to ensure they are not transmitted in the clear or accessible
from scripting.

This check performs the following:

* Verify HttpOnly flag
* Verify Secure flag
* Verify expiration

The check comes pre-populated with a large of regular expressions that are used
to identify which cookie is the session identifier.
The provided list can be editted at various scope levels (Global, Project, Profile, Route) to 
add, edit or remote entries.

=== Configuration

TODO

=== Operation

|====
| Passive on all requests | No test generation | No traffic generation
|====

This is a global check, global checks operate on all responses for the defined scope
(project or route).  Each response is analyzed to detect any configured regex matches.

