[Check_XmlInjection]
== XML Injection Check

[cols="1,4"]
|====
| OWASP Top 10 | link:https://www.owasp.org/index.php/Top_10_2013-A1-Injection[2013-A1-Injection]
| CWE | https://cwe.mitre.org/data/definitions/79.html[CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')] +
| PCI | 6.5.1 Injection flaws
|====

XML Injection is an attack technique used to manipulate or compromise the 
logic of an XML application or service. The injection of unintended XML content 
and/or structures into an XML message can alter the intend logic of the 
application. Further, XML injection can cause the insertion of malicious content 
into the resulting message/document.

This check injects various special XML characters that demonstraight an injection issue.  
The response is then analyzed to determine if the XML injection has been included in any
response body identified as contianing XML.

The check comes pre-populated with a list of XML injections.
The provided list can be editted at various scope levels (Global, Project, Profile, Route) to add, edit or remote entries.

=== Configuration

TODO

=== Operation

|====
| Test generation 
|====

This is a mutational check that produces test cases by modifying requests made by the traffic generator.
