=== What is {product}?

{product} performs security testing of Web Serices/APIs. 
Testing includes (for example) OWASP Top 10 and PCI 6.5 security issues and also includes fuzzing.
{product} is designed to integrate into modern development models such as Agile and continuous integration (CI) cicles.
{product} integrates with CI systems and is intended to be run automatically during daily builds.
{product} is intended to be integrated into engineering groups with the least amount of workflow changes.

==== Use cases

{product} has two primary use cases, integration into engineering groups and use by security teamms
in an organization.

 as a blocking step in continus integration and continuous deployment.

Peach Web enables Peach to perform fuzz testing of various web services and web APIs.
Any web service or API system that utilizes HTTP as the transport layer with JSON, XML or formdata is supported.
Examples include REST, SOAP and JSON-API.

Testing is performed by sending valid traffic through Peach's web proxy to the test target.
As requests pass through the web proxy, they are modified to create test cases.
Transport layer security (SSL/TLS) is supported along with client cert authentication.
Web socket traffic is also supported, but is not tested at this time (pass through only).

Peach Web has been designed to integrate into the development process to provide immediate feedback on API security.
This is an optional, but recommended method for usage.

// end
