=== What is {product}?

{product} performs security testing of Web Serices/APIs. 
Testing includes (for example) OWASP Top 10 and PCI 6.5 security issues and also includes fuzzing.
{product} is designed to integrate into modern development models such as Agile and continuous integration (CI) cicles.
{product} integrates with CI systems and is intended to be run automatically during daily builds.
{product} is intended to be integrated into engineering groups with the least amount of workflow changes.

* Primary usage
** Testing Web APIs

fuzzer for data consumers. Fuzzing is a software testing technique that
introduces malformed data to parts of a computer system. How the tested item reacts to unexpected
data becomes the source of security bugs.

Peach is a smart fuzzer that operates by performing the following actions:

* Understands the data structure and the flows of the test target
* Creates and feeds malformed data to the test target
* Monitors the test target to record interesting information when unintended or undesirable behavior
occurs (monitors include debuggers and network packet sniffers)

Peach is a versatile product and has been used to fuzz a wide range of products and devices:

* web browsers (file consumers)
* web servers (network servers)
* mobile devices (such as Android iOS)
* robots
* SCADA systems
* Semiconductor chips

Because Peach can easily extend its interfacing and monitoring, it is the most adaptable fuzzer that exists.





Peach Web enables Peach to perform fuzz testing of various web services and web APIs.
Any web service or API system that utilizes HTTP as the transport layer with JSON, XML or formdata is supported.
Examples include REST, SOAP and JSON-API.

Testing is performed by sending valid traffic through Peach's web proxy to the test target.
As requests pass through the web proxy, they are modified to create test cases.
Transport layer security (SSL/TLS) is supported along with client cert authentication.
Web socket traffic is also supported, but is not tested at this time (pass through only).

Peach Web has been designed to integrate into the development process to provide immediate feedback on API security.
This is an optional, but recommended method for usage.

// end
