#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Configuration.Install.dll',
	'System.ServiceProcess.dll',
	'System.Data.dll',
	'PeachFarm.Node.dll',
	'PeachFarm.Common.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='pf_node.exe',
	namespace = 'PeachFarm.Node.Service',
	install_644 = 'node.config.template',
)
