#!/usr/bin/env python

peach = bld.path.find_node('../Peach')

bld(
	name = 'peach-sdk',
	features = 'doc',
	install_path = '${BINDIR}/sdk',
	install_755 = {
		bld.path : bld.path.ant_glob('**/*', excl='wscript_build'),
		peach    : peach.ant_glob('samples/**'),
	}
)

bld(
	name = 'ExtendExamples.dll',
	features = 'cs',
	source = bld.path.ant_glob('extend/examples/*.cs'),
	use = [
		'NLog.dll',
		'System.dll',
		'System.Core.dll',
		'System.Xml.dll',
		'Peach.Core.dll',
	],
	install_path = None, # Compile only, don't install in ${BINDIR}
)
