
[[webproxy_TrafficGen]]
=== Automated Test Integration

Peach has support for several automated test frameworks with more under development.
If your automation framework is not currently supported please let support@peachfuzzer.com know
so it can be added to our list and an interim solution found.

==== JUnit 4

The JUnit 4 integrations is an extension to JUnit 4 to create a Peach Suite of test cases.
Integration requires creating a special Suite of unit tests.

Examples are provided with the source code:

TestFlaskRestTarget.java::
	JUnit 4 test cases that operate against the _flask_rest_target_.

FuzzFlashRestTarget.java::
	Example of a Peach Suite that uses the unit tests defined in _TestFlaskRestTarget_.

===== Installation

Build with Maven or Netbeans. A resulting jar file is produced in the _target_ folder.
Dependencies are in _target/lib_.

===== Usage

Create a suite similar to "FuzzFlashRestTarget.java".  

Example usage:

All test classes to include are listed in the @PeachSuiteClasses attribute.

[source=java]
----
@RunWith(com.peachfuzzer.web.frameworks.junit4.JUnit4PeachSuiteRunner.class)
@PeachSuiteClasses(TestFlaskRestTarget.class)
public class FuzzFlaskRestTarget {
    @BeforeClass
    public static void setProxy()
    {
        // Route all web traffic through Peach Web Proxy
        // this is specific to the library used by your test
        // cases.
        Options.setOption(Option.PROXY, new HttpHost("127.0.0.1", 8001));
    }
    
    @AfterClass
    public static void removeProxy()
    {
        // Stop traffic from routing through Peach Web Proxy
        Options.setOption(Option.PROXY, null);
    }
}
----

===== Running

When running Peach set a time duration or test case range.
For JUnit 4 runner, Peach controls when the runner should stop.

Run via the command line:

.Windows
----
set PEACH_API_HOST=127.0.0.1:8888
java org.junit.runner.JUnitCore com.peachfuzzer.web.frameworks.junit4.examples.FuzzFlaskRestTarget
----

.Linux
----
export PEACH_API_HOST=127.0.0.1:8888
java org.junit.runner.JUnitCore com.peachfuzzer.web.frameworks.junit4.examples.FuzzFlaskRestTarget
----

==== pytest

pytest-peach is a plugin for link:http://pytest.org[py.test] that integrates with Peach Web.
Integration includes calling the correct Peach Fuzzer APIs to report test names and not
fuzzing setup and teardown requests.

Pytest integration is provided as a pytest plugin called "pytest-peach".
It's available in the SDK as "sdk\webproxy\testrunners\pytest-peach".
The plugin builds and installs via the command "python setup.py install".
The plugin is also available via pip "pip install pytest-peach".

===== Requirements

You will need the following prerequisites in order to use pytest-peach:

- Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5 or PyPy
- py.test 2.8 or newer
- Requests v2.11 or newer

===== Installation

To install pytest-repeat:

----
$ pip install pytest-repeat
----

*From Source*

----
$ python setup.py install
----

===== Usage

----
pytest --peach=auto --peach_count=10000 test_target.py
----

*Arguments*

_Required_

--peach=JOB_ID::
   This argument enables the pytest Peach Fuzzer extention.
   To interact with Peach Fuzzer an active job id is needed.
   The easiest method is to self discover this id by setting it to +auto+.
   Optionally a full job id can be supplied. The use of _auto_ is recommended.

_Optional_

--peach_count=COUNT::
   How many test case iterations per test to perform. Defaults to +1000+.

--peach_api=BASE_URL::
   Base URL of Peach Fuzzer instance. Defaults to +http://127.0.0.1:8888+.

=== Selenium

Selenium test cases can be used with Peach Web via exporting them to a supported framework.
For example, the JUnit 4 integration has an example of using exported Selenium test cases.
The exported Selenium test cases have been modified to set the Proxy value in the target
web driver.

==== Custom Traffic Generators

Custom traffic generators exercise the web APIs being tested in a loop.
For best results it's recommended that the Peach Web Proxy API be used.
This allows performing some test setup/tear down independent of the fuzzed API calls.
The traffic generator should produce traffic until a call to the Peach Web Proxy APIs fail.
This allows Peach to direct the length of testing.

NOTE: An example traffic generator is included in the SDK as _SDK\webproxy\examples\flask_rest_target\hand_fuzz.py_.
This traffic generator makes use of the Peach Web Proxy API.

==== Proxy REST API

The Proxy API allows for tight integration with application unit tests.
As such the provided APIs match with typical unit test framework actions such as set-up and tear-down.  When using unit tests with Peach the typical flow is as follows:

. POST /p/jobs - Start fuzzing job using WebProxy pit
. PUT sessionSetUp
. [One time set up actions here]
LOOP:
.. PUT testSetUp
.. [Setup actions that occur on each iteration of fuzzing]
.. PUT testCase w/test name
.. [Requests that are fuzzed]
.. PUT testTearDown
.. [Tear down action that occur on each iteration of fuzzing]
.. GOTO LOOP
. PUT sessionTearDown - Once per fuzzing session
. [Session tear down actions, occur once per-fuzzing session]

NOTE: Interactive est api documentation can be viewed inside of Peach by navigating
to "Help" -> "Rest API" then select the "Proxy" section.

*****
Peach Web provides a Python module 'peachproxy' that provides wrappers around the Peach Proxy API.
The module is available in _SDK/webproxy/peachproxy_.
It can be installed by running:

----
python setup.py install
----

The module provides functions for each the Peach Web Proxy APIs.

*****
