[[tg_pytest]]
==== pytest

pytest-peach is a plugin for link:http://pytest.org[py.test] that integrates with Peach Web.
Integration includes calling the correct Peach Fuzzer APIs to report test names and not
fuzzing setup and teardown requests.

Pytest integration is provided as a pytest plugin called "pytest-peach".
It's available in the SDK as "sdk\webproxy\testrunners\pytest-peach".
The plugin builds and installs via the command "python setup.py install".
The plugin is also available via pip "pip install pytest-peach".

===== Requirements

You will need the following prerequisites in order to use pytest-peach:

- Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5 or PyPy
- py.test 2.8 or newer
- Requests v2.11 or newer

===== Installation

To install pytest-repeat:

----
$ pip install pytest-repeat
----

*From Source*

----
$ python setup.py install
----

===== Usage

----
pytest --peach=auto --peach_count=10000 test_target.py
----

*Arguments*

_Required_

--peach=JOB_ID::
   This argument enables the pytest Peach Fuzzer extention.
   To interact with Peach Fuzzer an active job id is needed.
   The easiest method is to self discover this id by setting it to +auto+.
   Optionally a full job id can be supplied. The use of _auto_ is recommended.

_Optional_

--peach_count=COUNT::
   How many test case iterations per test to perform. Defaults to +1000+.

--peach_api=BASE_URL::
   Base URL of Peach Fuzzer instance. Defaults to +http://127.0.0.1:8888+.
