[[tg_pytest]]
== pytest

pytest-peach is a plugin for link:http://pytest.org[pytest] that integrates with {product}.
Integration includes calling the correct {product} APIs to report test names and 
disable testing of setup/teardown methods.

Pytest integration is provided as a pytest plugin called "pytest-peach".
It's available in the SDK as "sdk\testrunners\pytest".
The plugin builds and installs via the command "python setup.py install".
The plugin is also available via pip "pip install pytest-peach".

=== Requirements

You will need the following prerequisites in order to use pytest-peach:

- Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5 or PyPy
- pytest 2.8 or newer
- Requests v2.11 or newer

=== Installation

To install pytest-peach plugin:

----
$ pip install pytest-repeat
----

*From Source*

----
$ python setup.py install
----

=== Usage

----
pytest --peach=on test_target.py
----

*Arguments*

_Required_

--peach=true::
   This argument enables the pytest {product} extension.

=== Example PEACH_AUTOMATION_CMD

  PEACH_AUTOMATION_CMD="pytest --peach=on testrunners/pytest/tests/test_target.py"

