[[tg_Custom]]
==== Custom Traffic Generators

Custom traffic generators exercise the web APIs being tested in a loop.
This allows performing some test setup/tear down independent of the fuzzed API calls.
The traffic generator should produce traffic until a call to the Peach Web Proxy APIs fail.
This allows Peach to direct the length of testing.

NOTE: An example traffic generator is included in the SDK as _SDK\testrunner\custom\python\hand_fuzz.py_.

TIP: Instead of writing a custom traffic generator from scratch consider writing a small
automated test in pytest, pyunit or junit4.  You can then leverage existing plugins for 
these test runners.  This is typically easier than writing a custom traffic generator script.

===== Logic flow from CI integration

This the the expected logic flow for custom traffic generators.
Traffic generators should use an existing library for implementation.

. Loop over test(s)
.. Call Peach libraries setup method
.. Optionally perform any setup related logic (not tested)
.. Call Peach libraries test method
.. Generate traffic that is tested
.. Call Peach libraries test teardown method
.. Optionally perform any teardown logic (not tested)
. Call libraries suite teardown method

===== Logic flow with no CI integration

This the the expected logic flow for custom traffic generators.
Traffic generators should use an existing library for implementation.

. Call Session Setup method of library
. Loop over test(s)
.. Call Peach libraries setup method
.. Optionally perform any setup related logic (not tested)
.. Call Peach libraries test method
.. Generate traffic that is tested
.. Call Peach libraries test teardown method
.. Optionally perform any teardown logic (not tested)
. Call libraries suite teardown method
. Call libraries session teardown method

===== Examples

.Python
==========================

An example traffic generator is included in the SDK as _SDK\testrunner\custom\python\hand_fuzz.py_.
This example expected to be called form a CI integration script.

==========================
