#!/usr/bin/env python
from waflib import Utils

name = 'PeachSampleNinja.exe'

#if bld.env.MCS and bld.env.DEST_OS != 'win32':
#	name = ''
#	bld.install_files('${BINDIR}', 'peach', chmod=Utils.O755)

bld(
	features = 'cs',
	use = 'System.Data.SQLite.dll System.Data.DataSetExtensions.dll Peach.Core.dll',
	source = bld.path.ant_glob('**/*.cs'),
	name = name,
	#namespace = 'PeachE',
	ver_product = 'Peach Enterprise',
	#install = bld.path.ant_glob('template.xml samples/*')
)
