#!/usr/bin/env python
from waflib import Utils

name = 'PeachSampleNinja.exe'

#if bld.env.MCS and bld.env.DEST_OS != 'win32':
#	name = ''
#	bld.install_files('${BINDIR}', 'peach', chmod=Utils.O755)

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'Peach.Core.dll',

	'System.Data.DataSetExtensions.dll',
	'System.Runtime.Remoting.dll',

	'System.Management.dll',
	'System.Xml.dll',

	'System.Data.dll',
	'System.Web.dll',
	'System.Web.Services.dll',
	'Microsoft.Dynamic.dll',
	'Microsoft.CSharp.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',

	'System.Data.SQLite.dll',
	'System.Data.DataSetExtensions.dll',
	'System.Data.dll',
	'System.Data.DataSetExtensions.dll',
	
	]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = name,
	resource = 'SampleNinja.db',
	ver_product = 'Peach Enterprise',
)
