#!/usr/bin/env python

deps = [
	'NLog.dll',

	'System.dll',
	'System.Core.dll',
	'System.Net.Http.dll',
	'Microsoft.CSharp.dll',

	'Peach.Core.dll',
	'Peach.Pro.dll',

	'Swashbuckle.Core.dll',

	'System.Net.Http.Formatting.dll',
	'System.Web.Cors.dll',
	'System.Web.Http.dll',
	'System.Web.Http.Cors.dll',
	'System.Web.Http.Owin.dll',

	'Microsoft.Owin.StaticFiles.dll',
	'Microsoft.Owin.FileSystems.dll',
	'Microsoft.Owin.Host.HttpListener.dll',
	'Microsoft.Owin.Hosting.dll',
	'Microsoft.Owin.dll',
	'Owin.dll',

	'Newtonsoft.Json.dll',

	'Ionic.Zip.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	resource = bld.path.ant_glob('Resources/**/* Views/**/*'),
	name = 'Peach.Pro.WebApi2.dll',
	csflags = [
		'/nowarn:1702', # The two assembly references have differing build and/or revision numbers
	],)
