#!/usr/bin/env python

deps = [
	'EasyHook.dll',
	'System.dll',
	'System.Core.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'PeachHooker.Network.dll',
	keyfile = 'PeachHooker.Network.snk',
	ide_path='Peach Hooker',
	csdoc = False,
)
