include::DHCPv4_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with DHCPv4 enabled.  The software tool bind can be targeted in a Linux environment.
A firewall must not block the DHCPv4 messages.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
SourcePort:: UDPv4 port number of the local machine.
TargetPort:: UDPv4 port number of the target host machine.
SourceMAC:: MAC Address of the local machine.
TargetMAC:: MAC Address of the target host machine.
RouterIP:: Router IP Address (fuzzed in DataModel).
BroadcastIP:: Broadcast IP Address (fuzzed in DataModel).
DHCPServerIP:: DHCP Server IP Address (fuzzed in DataModel).
SubnetMask:: Subnet Mask (fuzzed in DataModel).
DomainName:: Domain Name (fuzzed in DataModel).
DNS:: DNS Server IP Address (fuzzed in DataModel).
NetBios:: NetBios Server IP Address (fuzzed in DataModel).
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug DHCPv4.xml
----
==== Full test run
----
peach DHCPv4.xml
----

=== Example

.Sample DHCPv4 Configuration File
==========================
Example configuration sending DHCPv4 packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Dynamic Host Configuration Protocol (DHCP-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/dhcp4/"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="68"/>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="127.0.0.1"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="67"/>
    <Hwaddr key="SourceMAC" name="Source MAC Address" description="" value="0800c0565000"/>
    <Hwaddr key="TargetMAC" name="Target MAC Address" description="" value="f8e71b290c00"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>

    <String key="RouterIP" value="192.168.146.2"/>
    <String key="BroadcastIP" value="192.168.146.255"/>
    <String key="DHCPServerIP" value="192.168.146.254"/>
    <String key="SubnetMask" value="255.255.255.0"/>
    <String key="DomainName" value="localdomain"/>
    <String key="DNS" value="192.168.146.2"/>
    <String key="NetBios" value="192.168.146.2"/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
    <Iface key="tsharkInterface" name="name" description="" value="eth0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/bin/tshark"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="en0"/>
    <Iface key="tsharkInterface" name="name" description="" value="en0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
    <Iface key="tsharkInterface" name="name" description="" value="2"/>
    <String key="tsharkBin" name="name" description="" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================

