include::DHCPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with DHCPv6 enabled.  The software tool bind6 can be targeted in a Linux environment.
A firewall must not be blocking DHCPv6 messages.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine
SourceIPv6:: IP address of the interface on the local machine
SourcePort:: UDPv6 port number of the local machine
TargetPort:: UDPv6 port number of the target host machine
SourceMAC:: MAC Address of the local machine
TargetInterface:: Network Interface to configure
MulticastDHCP:: Multicast Address (fuzzed in DataModel)
TargetIPv6Lease:: Target IPv6 Lease (fuzzed in DataModel)
MaxTries:: Maximum number of packets to listen for before going to next iteration
Interface:: Name of local interface (used for monitoring) (Must be set to ::1)

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing
LoggerPath:: Path to folder where logs will be stored
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

.Fuzzing DHCPv6 Server
----
peach -1 -debug DHCPv6_Server.xml
----

.Fuzzing DHCPv6 Client
----
peach -1 -debug DHCPv6_Client.xml
----

==== Single test debug run

.Fuzzing DHCPv6 Server
----
peach DHCPv6_Server.xml
----

.Fuzzing DHCPv6 Client
----
peach DHCPv6_Client.xml
----

=== Examples

.Sample DHCPv6 Client Configuration File
==========================

Example configuration sending DHCPv6 packets.

For this example we assume you are running on Ubuntu or Debian Linux.

.Install DHCPv6 Client
----
sudo apt-get install wide-dhcpv6-client
----

.Running the client
----
dhcpv6c -f <interface>
----

NOTE: The MAC addresses must be updated based on the environment.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="TargetIPv6Lease"
				value="fe80::908:7a38:6156:acce"
				name="Target IPv6 Lease"
				description="IPv6 address to assign."/>
		
		<String key="MaxTries"
				value="20"
				name="Max Tries"
				description="Maximum number of tries to assign IP address per iteration."/>
		
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Ipv6 key="SourceIPv6"
			  value="::1"
			  name="Source IPv6 Address"
			  description="The IPv6 address of the machine running Peach Fuzzer. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="SourcePort"
			   value="547"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />
		
		<Ipv6 key="TargetIPv6"
			  value="::1"
			  name="Target IPv6 Address"
			  description="The IPv6 address of the target machine or device. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="TargetPort"
			   value="546"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<String key="LoggerPath"
				value="logs/dhcpv6_server/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================

.Sample DHCPv6 Server Configuration File
==========================
Example configuration sending DHCPv6 packets.

For this example we assume you are running on Windows.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Dynamic Host Configuration Protocol for IPv6(DHCPV6-In)
----

NOTE: The MAC addresses must be updated based on the environment.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="TargetIPv6Lease"
				value="fe80::908:7a38:6156:acce"
				name="Target IPv6 Lease"
				description="IPv6 address to assign."/>

		<String key="MaxTries"
				value="20"
				name="Max Tries"
				description="Maximum number of tries to assign IP address per iteration."/>

		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Ipv6 key="SourceIPv6"
			  value="::1"
			  name="Source IPv6 Address"
			  description="The IPv6 address of the machine running Peach Fuzzer. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="SourcePort"
			   value="547"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />
		
		<Ipv6 key="TargetIPv6"
			  value="::1"
			  name="Target IPv6 Address"
			  description="The IPv6 address of the target machine or device. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="TargetPort"
			   value="546"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<String key="LoggerPath"
				value="logs/dhcpv6_client/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================
