include::DHCPv4_DataSheet.adoc[]

=== Configuration

==== Target Configuration

A target machine with DHCPv4 enabled.  The software tool bind can be targeted in a Linux environment.
A firewall must not block the DHCPv4 messages.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
SourcePort:: UDPv4 port number of the local machine.
SourceMAC:: MAC Address of the local machine.
TargetMAC:: MAC Address of the target host machine.
Interface:: Name of local interface.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

----
peach -1 --debug DHCPv4.xml
----

==== Full test run

----
peach DHCPv4.xml
----

=== Example

.Sample DHCPv4 Configuration File
==========================
Example configuration sending DHCPv4 packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Dynamic Host Configuration Protocol (DHCP-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Ipv4 key="SourceIPv4"
			  value="127.0.0.1"
			  name="Source IPv4 Address"
			  description="The IPv4 address of the machine running Peach Fuzzer. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field."/>

		<Range key="SourcePort"
			   value="1055"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />

		<Ipv4 key="TargetIPv4"
			  value="127.0.0.1"
			  name="Target IPv4 Address"
			  description="The IPv4 address of the target machine or device. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field." />

		<String key="LoggerPath"
				value="logs/dhcpv4/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>

	<Linux>
		<Iface key="Interface"
			   value="eth0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Linux>

	<OSX>
		<Iface key="Interface"
			   value="en0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</OSX>

	<Windows>
		<Iface key="Interface"
			   value="Local Area Connection"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Windows>
</PitDefines>
----
==========================

