include::DHCPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with DHCPv6 enabled.  The software tool bind6 can be targeted in a Linux environment.
A firewall must not be blocking DHCPv6 messages.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine
SourceIPv6:: IP address of the interface on the local machine
SourcePort:: UDPv6 port number of the local machine
TargetPort:: UDPv6 port number of the target host machine
SourceMAC:: MAC Address of the local machine
TargetInterface:: Network Interface to configure
MulticastDHCP:: Multicast Address (fuzzed in DataModel)
TargetIPv6Lease:: Target IPv6 Lease (fuzzed in DataModel)
MaxTries:: Maximum number of packets to listen for before going to next iteration
Interface:: Name of local interface (used for monitoring) (Must be set to ::1)

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing
LoggerPath:: Path to folder where logs will be stored
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

.Single test debug run
----
peach -1 -debug DHCPv6_Server.xml
peach -1 -debug DHCPv6_Client.xml
----
.Full test run
----
peach DHCPv6_Server.xml
peach DHCPv6_Client.xml
----

=== Examples

.Sample DHCPv6 Configuration File
==========================
Example configuration sending DHCPv6 packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Dynamic Host Configuration Protocol for IPv6(DHCPV6-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/dhcpV6/"/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="547"/>
    <String key="MulticastDHCP" value="ff02::1:2"/>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="fe80::5054:ff:fe02:c880"/>
    <String key="TargetIPv6Lease" value="fe80::908:7a38:6156:acce"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="fe80::3e97:eff:fe47:524a%4"/>
    <String key="MaxTries" value="20"/> <!-- Maximum number of packets to listen for before going to next iteration -->
    <Hwaddr key="SourceMAC" name="Source MAC Address" description="" value="000c291bf55d"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="546"/>
    <String key="TargetInterface" value="veth1"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <Iface key="Interface" name="name" description=""  value="::1"/> <!-- This needs to be "::1" to bind to all interfaces. This is because ipv6 multicast oddness. -->
    <Ipv4 key="RemoteAgentIP" name="Remote Agent IP Address" description=""  value="127.0.0.1"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="tsharkInterface" name="name" description="" value="eth0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/bin/tshark"/>
  </Linux>

  <OSX>
    <Iface key="tsharkInterface" name="name" description="" value="en0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows>
    <Iface key="tsharkInterface" name="name" description="" value="2"/>
    <String key="tsharkBin" name="name" description="" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================
