
:Doctitle: ICMPv6 Peach Pit Data Sheet
:Description: Internet Control Message Protocol version 6 (ICMPv6)

 * Peach Pit: ICMPv6
 * Direction: Client
 * Supported Platforms: Windows, Linux, OS X

Internet Control Message Protocol version 6 (ICMPv6) is the implementation of the Internet Control Message Protocol (ICMP) for Internet Protocol version 6 (IPv6) defined in RFC 4443. ICMPv6 is an integral part of IPv6 and performs error reporting, diagnostic functions (like ping), and a framework for extensions to implement future changes.

Several extensions have been published, defining new ICMPv6 message types as well as new options for existing ICMPv6 message types. Neighbor Discovery Protocol (NDP) is a node discovery protocol in IPv6 which replaces and enhances functions of ARP. Secure Neighbor Discovery Protocol (SEND) is an extension of NDP with extra security. Multicast Router Discovery (MRD) allows discovery of multicast routers.

Specifications
--------------

[options="header"]
|========
|Specification | Title
|RFC4443 | Internet Control Message Protocol (ICMPv6) for the Internet Protocol Version 6 (IPv6) Specification
|RFC2460 | Internet Protocol, Version 6 (IPv6) Specification
|RFC2710 | Multicast Listener Discovery (MLD) for IPv6
|RFC4861 | Neighbor Discovery for IP version 6 (IPv6)
|RFC6275 | Mobility Support in IPv6
|RFC4620 | IPv6 Node Information Queries
|RFC3122 | Extensions to IPv6 Neighbor Discovery for Inverse Discovery Specification
|RFC3810 | Multicast Listener Discovery Version 2 (MLDv2) for IPv6
|RFC4286 | Multicast Router Discovery
|RFC4861 | Neighbor Discovery
|RFC5568 | Mobile IPv6 Fast Handovers
|RFC3971 | SEcure Neighbor Discovery (SEND)
|RFC6550 | RPL: IPv6 Routing Protocol for Low-Power and Lossy Networks
|RFC6743 | ICMP Locator Update Message for the Identifier-Locator Network Protocol for IPv6 (ILNPv6)
|========

Use Cases
---------

[options="header"]
|========
|Messages | Specification
|Destination Unreachable | RFC4443 (Section 3.1)
|Packet Too Big | RFC4443 (Section 3.2)
|Time Exceeded | RFC4443 (Section 3.3)
|Parameter Problem | RFC4443 (Section 3.4)
|Echo Request | RFC4443 (Section 4.1)
|Echo Reply | RFC4443 (Section 4.2)
|========

