include::ICMPv4_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with ICMPv4 enabled.  A firewall must not block ICMPv4 messages.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug ICMPv4.xml
----
==== Full test run
----
peach ICMPv4.xml
----

=== Examples

.Sample ICMPv4 Configuration File
==========================
Example configuration sending ICMPv4 packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Destination Unreachable Fragmentation Needed (ICMPv4-In)
File and Printer Sharing (Echo Request - ICMPv4-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Define key="RemoteAgentIP" value="10.0.1.40"/>
    <Define key="TargetIPv4" value="127.0.0.1"/>
    <Define key="LoggerPath" value="logs/ICMP/"/>
    <Define key="SourceIPv4" value="127.0.0.1"/>
    <Define key="Strategy"  value="Sequential"/>
    <Define key="PitLibraryPath" value="."/>
  </All>

  <Linux platform="linux">
    <Define key="Interface" value="eth0"/>
    <Define key="tsharkInterface" value="eth0"/>
    <Define key="tsharkBin" value="/usr/bin/tshark"/>
  </Linux>

  <OSX platform="osx">
    <Define key="Interface" value="en0"/>
    <Define key="tsharkInterface" value="en0"/>
    <Define key="tsharkBin" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows platform="windows">
    <Define key="Interface" value="Local Area Connection"/>
    <Define key="tsharkInterface" value="2"/>
    <Define key="tsharkBin" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================
