include::ICMPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with ICMPv6 enabled.  A firewall must not block ICMPv6 messages.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes.
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug ICMPv6.xml
----
==== Full test run
----
peach ICMPv6.xml
----

=== Examples

.Sample ICMPv6 Configuration File
==========================
Example configuration sending ICMPv6 packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Destination Unreachable (ICMPv6-In)
Core Networking - Multicast Listener Done (ICMPv6-In)
Core Networking - Multicast Listener Query (ICMPv6-In)
Core Networking - Multicast Listener Report (ICMPv6-In)
Core Networking - Multicast Listener Report v2 (ICMPv6-In)
Core Networking - Neighbor Discovery Advertisement (ICMPv6-In)
Core Networking - Neighbor Discovery Solicitation (ICMPv6-In)
Core Networking - Packet Too Big (ICMPv6-In)
Core Networking - Parameter Problem (ICMPv6-In)
Core Networking - Router Advertisement (ICMPv6-In)
Core Networking - Router Solicitation (ICMPv6-In)
Core Networking - Time Exceeded (ICMPv6-In)
File and Printer Sharing (Echo Request - ICMPv6-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv4 key="RemoteAgentIP" name="Remote Agent IP Address" description="" value="10.0.1.40"/>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="::1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/ICMPv6/"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="::1"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="lo"/>
    <Iface key="tsharkInterface" name="name" description="" value="lo"/>
    <String key="tsharkBin" name="name" description="" value="/usr/bin/tshark"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="en0"/>
    <Iface key="tsharkInterface" name="name" description="" value="en0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
    <Iface key="tsharkInterface" name="name" description="" value="2"/>
    <String key="tsharkBin" name="name" description="" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================
