include::IGMP_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with IGMP enabled.  A firewall must not block IGMP messages.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine
SourceIPv4:: IP address of the interface on the local machine
Interface:: Name of local interface (used for monitoring)

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing
LoggerPath:: Path to folder where logs will be stored
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug IGMP.xml
----
==== Full test run
----
peach IGMP.xml
----

=== Examples

.Sample IGMP Configuration File
==========================
Example configuration sending IGMP packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Internet Group Management Protocol (IGMP-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv4 key="RemoteAgentIP" name="Remote Agent IP Address" description="" value="10.0.1.40"/>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="224.0.0.22"/>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/IGMP/"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
    <Iface key="tsharkInterface" name="name" description="" value="eth0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/bin/tshark"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="em0"/>
    <Iface key="tsharkInterface" name="name" description="" value="em0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
    <Iface key="tsharkInterface" name="name" description="" value="2"/>
    <String key="tsharkBin" name="name" description="" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================
