include::IPSECv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
An IPsec target configured for manual keying using the keys defined in the configuration file is required.
IP-tools on Linux can be used.

Both a UDP and an TCP listener are required to run all the tests. The networking tool socat can be used as a listener.

==== Required Pit Configuration Changes

TargetIPv6:: IPv6 address of the target host machine.
SourceIPv6:: IPv6 address of the interface on the local machine.
TargetIPv4:: IPv4 address of the target host machine (used for encapsulating IPv4 in IPv6).
SourceIPv4:: IPv4 address of the interface on the local machine (used for encapsulating IPv4 in IPv6).
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Mode:: Processing mode for IPsec can either be Tunnel or Transport.
EncryptionAlg:: Encryption algorithm used when encrypting packets.
CryptoKey:: Shared key used to encrypt packets.
HashAlg:: Hashing algorithm used to provide data integrity.
AuthKey:: Shared key used for HMAC hashing.
IV:: Initialization vector used with the encryption algorithm.
SPI:: Security parameter index used assigned to the local machine.
SourcePort:: UDPv6 and/or TCPv6 port number of the local machine.
TargetPort:: UDPv6 and/or TCPv6 port number of the target host machine.

==== Optional Pit Configuration Changes

Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

.Fuzzing IPSECv6 ESP
----
peach -1 --debug IPSECv6_ESP.xml
----

.Fuzzing IPSECv6 AH
----
peach -1 --debug IPSECv6_AH.xml
----

==== Full test run

.Fuzzing IPSECv6 ESP
----
peach IPSECv6_ESP.xml
----

.Fuzzing IPSECv6 AH
----
peach IPSECv6_AH.xml
----

=== Examples

.Sample IPsec AH Configuration File
==========================
Example configuration using ipsec-tools on Linux.

First we must install ipsec-tools; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the  platform specific installation instructions for ipsec-tools.

----
#This will enable to the target machine to both send and receive IPsec traffic from the specified IP addresses

sudo apt-get install ipsec-tools

#Create the following ipsec.config file changing the encryption keys, algorithms and IP address to match the pit config

## Start ipsec.config ##
flush;
spdflush;

add 10.0.1.1 10.0.1.2 ah 201 -A hmac-md5 "4141414141414141414141414141414141414141";
add 10.0.1.2 10.0.1.1 ah 301 -A hmac-md5 "4141414141414141414141414141414141414141";

spdadd 10.0.1.2 10.0.1.2 any -P out ipsec
    ah/transport//require;

spdadd 10.0.1.1 10.0.1.2 any -P in ipsec
    ah/transport//require;
## End ipsec.config ##

#Run setkey to enable changes

sudo setkey -f ipsec.config

#Setting up socat listener for UDP

sudo socat STDIO udp-listen:12345

#Setting up socat listener for TCP

sudo socat STDIO tcp-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Enum key="Mode"
			  value="Transport"
			  enumType="Peach.Enterprise.Pits.IpSecv6_Mode"
			  name="IPSEC Mode"
			  description="IPSEC mode of operation."/>
		
		<Enum key="HashAlg"
			  value="HMACMD5"
			  enumType="Peach.Enterprise.Pits.IpSecv6_HMAC"
			  name="HMAC Hash Algorithm"
			  description="The HMAC hash algorithm to use."/>
		
		<String key="AuthKey"
				value="4141414141414141414141414141414141414141"
				name="HMAC Key"
				description="HMAC authentication key. Length of this key is dependent on the HMAC algorithm selected."/>
		<String key="SPI"
				value="201"
				name="Security Parameters Index (SPI)"
				description="The SPI is an arbitrary 32-bit value that, in combination with the destination IP address and security protocol (AH), uniquely identifies the Security Association for this datagram."/>
		
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Ipv4 key="SourceIPv4"
			  value="127.0.0.1"
			  name="Source IPv4 Address"
			  description="The IPv4 address of the machine running Peach Fuzzer. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field."/>

		<Ipv6 key="SourceIPv6"
			  value="::1"
			  name="Source IPv6 Address"
			  description="The IPv6 address of the machine running Peach Fuzzer. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="SourcePort"
			   value="1234"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />

		<Ipv4 key="TargetIPv4"
			  value="127.0.0.1"
			  name="Target IPv4 Address"
			  description="The IPv4 address of the target machine or device. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field." />

		<Ipv6 key="TargetIPv6"
			  value="::1"
			  name="Target IPv6 Address"
			  description="The IPv6 address of the target machine or device. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="TargetPort"
			   value="1234"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<String key="LoggerPath"
				value="logs/ipsecv6_ah/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================

.Sample IPsec ESP Configuration File
==========================
Example configuration using ipsec-tools on Linux.

First we must install ipsec-tools; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the  platform specific installation instructions for ipsec-tools.

----
#This will enable to the target machine to both send and receive IPsec traffic from the specified IP addresses

sudo apt-get install ipsec-tools

#Create the following ipsec.config file changing the encryption keys, algorithms and IP address to match the pit config

## Start ipsec.config ##
flush;
spdflush;

add 10.0.1.1 10.0.1.2 ah 201 -A hmac-md5 "4141414141414141414141414141414141414141";
add 10.0.1.2 10.0.1.1 ah 301 -A hmac-md5 "4141414141414141414141414141414141414141";

add 10.0.1.1 10.0.1.2 esp 201 -E 3des-cbc "aeaeaeaeaeaeaeae";
add 10.0.1.2 10.0.1.1 esp 301 -E 3des-cbc "aeaeaeaeaeaeaeae";

spdadd 10.0.1.2 10.0.1.2 any -P out ipsec
    esp/transport//require
    ah/transport//require;

spdadd 10.0.1.1 10.0.1.2 any -P in ipsec
    esp/transport//require
    ah/transport//require;
## End ipsec.config ##

#Run setkey to enable changes

sudo setkey -f ipsec.config

#Setting up socat listener for UDP

sudo socat STDIO udp-listen:12345

#Setting up socat listener for TCP

sudo socat STDIO tcp-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		
		<Enum key="Mode"
			  value="Transport"
			  enumType="Peach.Enterprise.Pits.IpSecv6_Mode"
			  name="IPSEC Mode"
			  description="IPSEC mode of operation."/>
		
		<Enum key="EncryptionAlg"
			  value="Aes128"
			  enumType="Peach.Enterprise.Pits.IpSecv6_Encryption"
			  name="Encryption Algorithm"
			  description="IPSEC encryption algorithm."/>

		<String key="CryptoKey"
				value="41414141414141414141414141414141"
				name="Encryption Key"
				description="Encryption key in HEX. For AES the key must be 16 bytes long. For 3DES it must be 8 bytes long."/>
		<String key="IV"
				value="baae9ef59ff1ee56211769bd91da50ed"
				name="Initialization Vector (IV)"
				description="Initialization vector (IV) in HEX. For AES the IV must be 16 bytes long. For 3DES is must be 8 bytes long."/>
		
		<Enum key="HashAlg"
			  value="HMACMD5"
			  enumType="Peach.Enterprise.Pits.IpSecv6_HMAC"
			  name="HMAC Hash Algorithm"
			  description="The HMAC hash algorithm to use."/>
		
		<String key="AuthKey"
				value="4141414141414141414141414141414141414141"
				name="HMAC Key"
				description="HMAC authentication key. Length of this key is dependent on the HMAC algorithm selected."/>
		<String key="SPI"
				value="201"
				name="Security Parameters Index (SPI)"
				description="The SPI is an arbitrary 32-bit value that, in combination with the destination IP address and security protocol (AH), uniquely identifies the Security Association for this datagram."/>
		
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Ipv4 key="SourceIPv4"
			  value="127.0.0.1"
			  name="Source IPv4 Address"
			  description="The IPv4 address of the machine running Peach Fuzzer. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field."/>

		<Ipv6 key="SourceIPv6"
			  value="::1"
			  name="Source IPv6 Address"
			  description="The IPv6 address of the machine running Peach Fuzzer. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="SourcePort"
			   value="1234"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />

		<Ipv4 key="TargetIPv4"
			  value="127.0.0.1"
			  name="Target IPv4 Address"
			  description="The IPv4 address of the target machine or device. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field." />

		<Ipv6 key="TargetIPv6"
			  value="::1"
			  name="Target IPv6 Address"
			  description="The IPv6 address of the target machine or device. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="TargetPort"
			   value="1234"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<String key="LoggerPath"
				value="logs/ipsecv6_esp/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================

