include::IPSECv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
An IPsec target configured for manual keying using the keys defined in the configuration file is required.
IP-tools on Linux can be used.

Both a UDP and an TCP listener are required to run all the tests. The networking tool socat can be used as a listener.

==== Required Pit Configuration Changes
TargetIPv6:: IPv6 address of the target host machine.
SourceIPv6:: IPv6 address of the interface on the local machine.
TargetIPv4:: IPv4 address of the target host machine (used for encapsulating IPv4 in IPv6).
SourceIPv4:: IPv4 address of the interface on the local machine (used for encapsulating IPv4 in IPv6).
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Mode:: Processing mode for IPsec can either be Tunnel or Transport.
EncryptionAlg:: Encryption algorithm used when encrypting packets.
CryptoKey:: Shared key used to encrypt packets.
HashAlg:: Hashing algorithm used to provide data integrity.
AuthKey:: Shared key used for HMAC hashing.
IV:: Initialization vector used with the encryption algorithm.
SPI:: Security parameter index used assigned to the local machine.
Interface:: Name of local interface (used for monitoring).
SourcePort:: UDPv6 and/or TCPv6 port number of the local machine.
TargetPort:: UDPv6 and/or TCPv6 port number of the target host machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
#ESP Header Test
peach -1 --debug IPSECv6.xml

#Authentication Header Test
peach -1 --debug IPSECv6.xml AH
----
==== Full test run
----
#ESP Header Test
peach IPSECv6.xml

#Authentication Header Test
peach IPSECv6.xml AH
----

=== Examples

.Sample IPsec Configuration File
==========================
Example configuration using ipsec-tools on Linux.

First we must install ipsec-tools; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the  platform specific installation instructions for ipsec-tools.

----
#This will enable to the target machine to both send and receive IPsec traffic from the specified IP addresses

sudo apt-get install ipsec-tools

#Create the following ipsec.config file changing the encryption keys, algorithms and IP address to match the pit config

## Start ipsec.config ##
flush;
spdflush;

add 10.0.1.1 10.0.1.2 ah 201 -A hmac-md5 "4141414141414141414141414141414141414141";
add 10.0.1.2 10.0.1.1 ah 301 -A hmac-md5 "4141414141414141414141414141414141414141";

add 10.0.1.1 10.0.1.2 esp 201 -E 3des-cbc "aeaeaeaeaeaeaeae";
add 10.0.1.2 10.0.1.1 esp 301 -E 3des-cbc "aeaeaeaeaeaeaeae";

spdadd 10.0.1.2 10.0.1.2 any -P out ipsec
    esp/transport//require
    ah/transport//require;

spdadd 10.0.1.1 10.0.1.2 any -P in ipsec
    esp/transport//require
    ah/transport//require;
## End ipsec.config ##

#Run setkey to enable changes

sudo setkey -f ipsec.config

#Setting up socat listener for UDP

sudo socat STDIO udp-listen:12345

#Setting up socat listener for TCP

sudo socat STDIO tcp-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <String key="LoggerPath" name="Logger Path" description=""  value="./logs/ipsec/"/>
    <Hwaddr key="SourceMAC" name="Source MAC Address" description="" value="ffffffffffff" />
    <Hwaddr key="TargetMAC" name="Target MAC Address" description="" value="000000000000"/>
    <String key="Mode" value="Transport"/>
    <Strategy key="Strategy" name="name" description="" value="Random"/>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="127.0.0.1"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="::1"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="::1"/>
    <String key="EncryptionAlg" value="Aes128"/>
    <String key="CryptoKey" value="41414141414141414141414141414141"/>
    <String key="IV" value="baae9ef59ff1ee56211769bd91da50ed"/>
    <String key="HashAlg" value="HMACSHA1"/>
    <String key="AuthKey" value="4141414141414141414141414141414141414141"/>
    <String key="SPI" value="201"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="12345"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="12345"/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
  </Linux>

  <OSX>
    <!-- OS X doesn't support raw ESP or AH packets -->
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
  </Windows>
</PitDefines>
----
==========================
