include::IPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
IPv6 and UDPv6 listeners are required to run all tests. The network tool socat can be used as a listener.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Interface:: Name of local interface (used for monitoring).
SourcePort:: UDPv6 port number of the local machine.
TargetPort:: UDPv6 port number of the target host machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run
----
peach -1 --debug IPv6.xml
----
==== Full test run
----
peach IPv6.xml
----

=== Examples

.Sample IPv6 Configuration File
==========================
Example configuration using socat on Linux.

First we must install and run socat; for this example we assume you are running Linux. For other platforms follow the  platform specific installation instructions for socat.

----
#Install socat
sudo apt-get install socat

# Used to listen for ipv6 traffic
socat STDIO ip-recv:ipv6

#Used to listen for UDPv6
socat STDIO udp6-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Ipv6 key="SourceIPv6"
			  value="::1"
			  name="Source IPv6 Address"
			  description="The IPv6 address of the machine running Peach Fuzzer. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="SourcePort"
			   value="12345"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />

		<Ipv6 key="TargetIPv6"
			  value="::1"
			  name="Target IPv6 Address"
			  description="The IPv6 address of the target machine or device. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>

		<Range key="TargetPort"
			   value="12345"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<String key="LoggerPath"
				value="logs/vlan/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>

	<Linux>
		<Iface key="Interface"
			   value="eth0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Linux>

	<OSX>
		<Iface key="Interface"
			   value="en0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</OSX>

	<Windows>
		<Iface key="Interface"
			   value="Local Area Connection"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Windows>
</PitDefines>
----
==========================
