include::IPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
IPv6 and UDPv6 listeners are required to run all tests. The network tool socat can be used as a listener.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Interface:: Name of local interface (used for monitoring).
SourcePort:: UDPv6 port number of the local machine.
TargetPort:: UDPv6 port number of the target host machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug IPv6.xml
----
==== Full test run
----
peach IPv6.xml
----

=== Examples

.Sample IPv6 Configuration File
==========================
Example configuration using socat on Linux.

First we must install and run socat; for this example we assume you are running Linux. For other platforms follow the  platform specific installation instructions for socat.

----
#Install socat
sudo apt-get install socat

# Used to listen for ipv6 traffic
socat STDIO ip-recv:ipv6

#Used to listen for UDPv6
socat STDIO udp6-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="::1"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="::1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/IPv6/"/>
    <Hwaddr key="SourceMAC" name="Source MAC Address" description="" value="000c29ef2a1b" />
    <Hwaddr key="TargetMAC" name="Target MAC Address" description="" value="000c29ef2a1b" />
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="12345"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="12345"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
  </Linux>

  <OSX>
    <!-- This can't run on OS X because it uses the RawEther publisher. -->
  </OSX>

  <Windows>
    <!-- This can't run on windows because it uses the RawEther publisher. -->
  </Windows>
</PitDefines>
----
==========================
