include::LACP_DataSheet.adoc[]

=== Configuration

==== Target Configuration
No extra applications are required for pit tests but we recommend a LACP enabled switch.

==== Required Pit Configuration Changes
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Interface:: Name of local interface.
ActorPort:: Port number of the local machine.
PartnerPort:: Port number of the target host machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

----
peach -1 -debug LACP.xml
----

==== Full test run

----
peach LACP.xml
----

=== Examples

.Sample LACP Configuration File
==========================
Example configuration for sending LACP packets.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Hwaddr key="ActorMAC" 
				value="0004961f506a"
				name="Actor System ID"
				description="The Actor’s System ID, encoded as a MAC address."/>
		<Hwaddr key="PartnerMAC" 
				value="000000000000"
				name="Partner System ID"
				description="The Partner’s System ID, encoded as a MAC address."/>
		<Range key="ActorPort" 
			   value="18" 
			   min="0" max="65535"
			   name="LACP Actor Port"
			   description="The port number assigned to the port by the Actor (the System sending the PDU)."/>
		<Range key="PartnerPort" 
			   value="0" 
			   min="0" max="65535"
			   name="LACP Partner Port"
			   description="The port number associated with this link assigned to the port by the Partner."/>
		
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />

		<String key="LoggerPath"
				value="logs/lacp/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>

	<Linux>
		<Iface key="Interface"
			   value="eth0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Linux>

	<OSX>
		<Iface key="Interface"
			   value="en0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</OSX>

	<Windows>
		<Iface key="Interface"
			   value="Local Area Connection"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Windows>
</PitDefines>
----
==========================
