include::Ldap_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A configured LDAP server with an account that is defined in the configuration file is required.

OpenLDAP can be used on Linux.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine
SourceIPv4:: IP address of the interface on the local machine
TargetPort:: LDAP port number of the target host machine
Username:: Username used to login to the LDAP service
Password:: Password for the user logging into the LDAP service

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing
LoggerPath:: Path to folder where logs will be stored
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

.Fuzzing an LDAP Client
----
peach -1 --debug LDAP_Client.xml
----

.Fuzzing an LDAP Server
----
peach -1 --debug LDAP_Server.xml
----

==== Full test run

.Fuzzing an LDAP Client
----
peach LDAP_Client.xml
----

.Fuzzing an LDAP Server
----
peach LDAP_Server.xml
----

=== Examples

.Sample LDAP Client Configuration File
==========================

Example configuration using OpenLdap on Linux.

First we must install OpenLDAP; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the  platform specific installation instructions for OpenLDAP.

----
# Install OpenLdap client tools
sudo apt-get install ldap-utils

----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="UserName"
				value="cn=admin,dc=peach,dc=local"
				name="LDAP Username"
				description="Credentials to use when binding to LDAP server. Example: cn=admin,dc=peach,dc=local."/>

		<String key="Password"
				value="password"
				name="LDAP Password"
				description="Password to use for authenticating to LDAP server."/>

		<Ipv4 key="SourceIPv4"
			  value="127.0.0.1"
			  name="Source IPv4 Address"
			  description="The IPv4 address of the machine running Peach Fuzzer. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field."/>

		<Range key="SourcePort"
			   value="389"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<Range  key="Timeout"
				value="5000"
				min="0" max="10000000"
				name="Timeout"
				description="Timeout in milliseconds to wait for data to be send or received. During fuzzing a timeout failure will cause the fuzzer to skip to the next iteration."/>

		<String key="LoggerPath"
				value="logs/vlan/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================

.Sample LDAP Server Configuration File
==========================
Example configuration using OpenLdap on Linux.

First we must install OpenLDAP; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the  platform specific installation instructions for OpenLDAP.

----
#Install OpenLdap server
sudo apt-get install slapd ldap-utils migrationtools

#Configure slapd
dpkg-reconfigure slapd

  *Omit OpenLDAP server configuration? No
  *DNS domain name: peach.local
  *Name of your organization: Peach 3.0
  *Admin Password: password
  *Confirm Password: password
  *Database backend to use: BDB
  *Do you want your database to be removed when slapd is purged? No
  *Move old database? Yes
  *Allow LDAPv2 Protocol? No

#Edit migration tools common and edit the following parameters
pico /etc/migrate_comon.ph
  $DEFAULT_MAIL_DOMAIN = "peach.local";
  $DEFAULT_BASE = "dc=peach.local";
#Press ctrl+x to save

#Create a group and people ldif file
pico ~/grouppeople.ldif
  dn: ou=People,dc=peach,dc=local
  ou: People
  objectclass: organizationalUnit
#Press ctrl+x to save

#Use migration tools to export users on your system to ldif files
/usr/share/migrationtools/migrate_group.pl /etc/group ~/group.ldif
/usr/share/migrationtools/migrate_passwd.pl /etc/passwd ~/password.ldif

#Add the the created files to Ldap, the admin password is required after each of the following commands
cd ~
ldapadd -x -W -D "cn=admin,dc=peach,dc=local" -f grouppeople.ldif
ldapadd -x -W -D "cn=admin,dc=peach,dc=local" -f group.ldif
ldapadd -x -W -D "cn=admin,dc=peach,dc=local" -f password.ldif
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="UserName"
				value="cn=admin,dc=peach,dc=local"
				name="LDAP Username"
				description="Credentials to use when binding to LDAP server. Example: cn=admin,dc=peach,dc=local."/>

		<String key="Password"
				value="password"
				name="LDAP Password"
				description="Password to use for authenticating to LDAP server."/>
		
		<Ipv4 key="TargetIPv4"
			  value="127.0.0.1"
			  name="Target IPv4 Address"
			  description="The IPv4 address of the target machine or device. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field." />

		<Range key="TargetPort"
			   value="389"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<Range  key="Timeout"
				value="5000"
				min="0" max="10000000"
				name="Timeout"
				description="Timeout in milliseconds to wait for data to be send or received. During fuzzing a timeout failure will cause the fuzzer to skip to the next iteration."/>

		<String key="LoggerPath"
				value="logs/ldap/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================
