include::LLDP_DataSheet.adoc[]

=== Configuration

==== Target Configuration
This pit broadcasts LLDP packets; no extra applications are required.

==== Required Pit Configuration Changes
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Interface:: Name of local interface.
Hostname:: Host name of the switch.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run
----
peach -1 --debug LLDP.xml
----
==== Full test run
----
peach LLDP.xml
----

=== Examples

.Sample LLDP Configuration File
==========================
Example configuration for sending LLDP packets.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="Hostname"
				value="foobar"
				name="Switch Hostname"
				description="Hostname of the switch."/>
		
		<Hwaddr key="SourceMAC"
				value="000000000000"
				name="Source MAC Address"
				description="Hardware address of the network interface on machine running Peach Fuzzer. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."/>

		<Hwaddr key="TargetMAC"
				value="000000000000"
				name="Target MAC Address"
				description="Hardware address of the network interface on target machine or device. To find the hardware address on Windows, run 'ipconfig /all' and look for the 'Physical Address' field. For Linux run 'ifconfig' and look for the 'HWaddr' field. For OS X run 'ifconfig' and look for the 'ether' field."  />

		<String key="LoggerPath"
				value="logs/lldp/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>

	<Linux>
		<Iface key="Interface"
			   value="eth0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Linux>

	<OSX>
		<Iface key="Interface"
			   value="en0"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</OSX>

	<Windows>
		<Iface key="Interface"
			   value="Local Area Connection"
			   name="Network Interface"
			   description="The network interface to transmit packets over. For Windows, the network interfaces can be shown by running 'ipconfig'. On Linux and OS X, the network interfaces can be shown by running the command 'ifconfig'."/>
	</Windows>
</PitDefines>
----
==========================
