include::LLDP_DataSheet.adoc[]

=== Configuration

==== Target Configuration
This pit broadcasts LLDP packets; no extra applications are required.

==== Required Pit Configuration Changes
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
Interface:: Name of local interface (used for monitoring).
Hostname:: Host name of the switch.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug LLDP.xml
----
==== Full test run
----
peach LLDP.xml
----

=== Examples

.Sample LLDP Configuration File
==========================
Example configuration for sending LLDP packets.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv4 key="RemoteAgentIP" name="Remote Agent IP Address" description="" value="10.0.1.40"/>
    <Hwaddr key="SourceMAC" name="Source MAC Address" description="" value="000000000000"/>
    <Hwaddr key="TargetMAC" name="Target MAC Address" description="" value="ffffffffffff"/>
    <String key="Hostname" value="foobar"/>
    <String key="LoggerPath" name="Logger Path" description=""  value="logs/lldp/"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
    <Iface key="tsharkInterface" name="name" description="" value="eth0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/bin/tshark"/>
  </Linux>

  <OSX>
    <!-- This can't run on OS X because it uses the RawEther publisher. -->
  </OSX>

  <Windows>
    <!-- This can't run on windows because it uses the RawEther publisher. -->
  </Windows>
</PitDefines>
----
==========================
