include::MLD_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with MLD enabled.  A firewall must not block MLD messages.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run
----
peach -1 --debug MLD.xml
----
==== Full test run
----
peach MLD.xml
----

=== Examples

.Sample MLD Configuration File
==========================
Example configuration sending MLD packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Multicast Listener Done (ICMPv6-In)
Core Networking - Multicast Listener Query (ICMPv6-In)
Core Networking - Multicast Listener Report (ICMPv6-In)
Core Networking - Multicast Listener Report v2 (ICMPv6-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Ipv6 key="SourceIPv6"
			  value="::1"
			  name="Source IPv6 Address"
			  description="The IPv6 address of the machine running Peach Fuzzer. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>
		<Ipv6 key="TargetIPv6"
			  value="::1"
			  name="Target IPv6 Address"
			  description="The IPv6 address of the target machine or device. The IPv6 address can be found on Windows by running 'ipconfig' and looking for the 'IPv6 Address' field. For Linux run 'ifconfig' and look for 'inet6 addr' field. For OS X run 'ifconfig' and look for the 'inet6' field."/>
		
		<String key="LoggerPath"
				value="logs/mdl/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================
