include::MLD_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with MLD enabled.  A firewall must not block MLD messages.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug MLD.xml
----
==== Full test run
----
peach MLD.xml
----

=== Examples

.Sample MLD Configuration File
==========================
Example configuration sending MLD packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Multicast Listener Done (ICMPv6-In)
Core Networking - Multicast Listener Query (ICMPv6-In)
Core Networking - Multicast Listener Report (ICMPv6-In)
Core Networking - Multicast Listener Report v2 (ICMPv6-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv4 key="RemoteAgentIP" name="Remote Agent IP Address" description="" value="10.0.1.40"/>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="::1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/MLD/"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="::1"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
    <Iface key="tsharkInterface" name="name" description="" value="eth0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/bin/tshark"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="em0"/>
    <Iface key="tsharkInterface" name="name" description="" value="em0"/>
    <String key="tsharkBin" name="name" description="" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows>
    <!-- This can't run on windows because it uses the RawEther publisher. -->
    <!-- Platform independence is added as an example. -->
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
    <Iface key="tsharkInterface" name="name" description="" value="2"/>
    <String key="tsharkBin" name="name" description="" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================
