include::MLD_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A target machine with MLD enabled.  A firewall must not block MLD messages.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug MLD.xml
----
==== Full test run
----
peach MLD.xml
----

=== Examples

.Sample MLD Configuration File
==========================
Example configuration sending MLD packets.

For this example we assume you are running on Windows. For other platforms use the preferred way to configure the firewall.

Windows Firewall Inbound Rules to enable on Target:

----
Core Networking - Multicast Listener Done (ICMPv6-In)
Core Networking - Multicast Listener Query (ICMPv6-In)
Core Networking - Multicast Listener Report (ICMPv6-In)
Core Networking - Multicast Listener Report v2 (ICMPv6-In)
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Define key="RemoteAgentIP" value="10.0.1.40"/>
    <Define key="TargetIPv6" value="::1"/>
    <Define key="LoggerPath" value="logs/MLD/"/>
    <Define key="SourceIPv6" value="::1"/>
    <Define key="Strategy"  value="Sequential"/>
    <Define key="Path" value="."/>
  </All>

  <Linux platform="linux">
    <Define key="Interface" value="eth0"/>
    <Define key="tsharkInterface" value="eth0"/>
    <Define key="tsharkBin" value="/usr/bin/tshark"/>
  </Linux>

  <OSX platform="osx">
    <Define key="Interface" value="em0"/>
    <Define key="tsharkInterface" value="em0"/>
    <Define key="tsharkBin" value="/usr/local/bin/tshark"/> <!-- fix depending on actual install location -->
  </OSX>

  <Windows platform="windows">
    <!-- This can't run on windows because it uses the RawEther publisher. -->
    <!-- Platform independence is added as an example. -->
    <Define key="Interface" value="Local Area Connection"/>
    <Define key="tsharkInterface" value="2"/>
    <Define key="tsharkBin" value="C:\Program Files\Wireshark\tshark.exe"/>
  </Windows>
</PitDefines>
----
==========================
