include::modbus_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A Modbus server listening on the Modbus port defined in configuration file is required. The network tool socat can be used as the listener.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
TargetPort:: Modbus port number of the target host machine.
SerialPort:: The serial port of the local machine when using Modbus over serial.
Baudrate:: The baud rate for the current serial port.
Parity:: The parity bit value used for the current serial port.
DataBits:: The number of data bits in each character for the current serial port.
StopBits:: Number of bits sent at the end of every character for the current serial port.
Handshake:: The current handshake protocol used by the current serial port.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Timeout:: How long to wait for incoming data.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

.Fuzzing modbus via TCP
----
peach modbus_tcp.xml
----

.Fuzzing modbus via ASCII Serial
----
peach modbus_ascii_serial.xml
----

.Fuzzing modbus via RTU Serial
----
peach modbus_rtu_serial.xml
----

==== Full test run

.Fuzzing modbus via TCP
----
peach modbus_tcp.xml
----

.Fuzzing modbus via ASCII Serial
----
peach modbus_ascii_serial.xml
----

.Fuzzing modbus via RTU Serial
----
peach modbus_rtu_serial.xml
----

=== Examples

.Sample Modbus TCP Configuration File
==========================
Example configuration using socat on Linux.

First we must install and run socat; for this example we assume you are running Linux. For other platforms follow the platform specific installation instructions for socat.

----
sudo apt-get install socat

socat tcp-l:502,fork exec:'/bin/cat'
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Ipv4 key="TargetIPv4"
			  value="127.0.0.1"
			  name="Target IPv4 Address"
			  description="The IPv4 address of the target machine or device. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field." />

		<Range key="TargetPort"
			   value="502"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<Range  key="Timeout"
				value="5000"
				min="0" max="10000000"
				name="Timeout"
				description="Timeout in milliseconds to wait for data to be send or received. During fuzzing a timeout failure will cause the fuzzer to skip to the next iteration."/>


		<String key="LoggerPath"
				value="logs/modbus_tcp/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================

