include::NTP_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A UDP listener listening on the UDPv4 port defined in configuration file is required. The network tool socat can be used as the listener.

==== Required Pit Configuration Changes
TargetIPv4:: IPv4 address of the target host machine.
SourcePort:: UDPv4 and/or TCPv4 port number of the local machine.
TargetPort:: UDPv4 and/or TCPv4 port number of the target host machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug NTP.xml
----
==== Full test run
----
peach NTP.xml
----

=== Examples

.Sample NTP Configuration File
==========================
Example configuration using socat on Linux.

First we must install and run socat; for this example we assume you are running Linux. For other platforms follow the platform specific installation instructions for socat.

----
sudo apt-get install socat

socat STDIO udp4-listen:123
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="123"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="123"/>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="127.0.0.1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="./logs/ntp/"/>
    <Strategy key="Strategy" name="name" description="" value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>
</PitDefines>
----
==========================
