include::TCPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
An application must be listening on the TCP port defined in the configuration file. The network tool socat can be used as the listener.

Disable outgoing RST packets when using this pit because Peach manages TCP state outside of the kernel context.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
TargetIPBytes:: IP address of the target host machine in hexadecimal.
SourceIPBytes:: IP address of the interface on the local machine in hexadecimal.
SourcePort:: TCPv6 port number of the local machine.
TargetPort:: TCPv6 port number of the target host machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug TCPv6.xml
----
==== Full test run
----
peach TCPv6.xml
----

=== Examples

.Sample TCPv6 Configuration File
==========================
Example configuration using socat on Linux.

First we must configure the firewall then install and run socat, for this example we assume you are running Linux. For other platforms follow the platform specific installation instructions for socat and firewall configuration.

[source,bash]
----
#Disable outgoing RST on the node running Peach
ip6tables -A OUTPUT -p tcp -m tcp --tcp-flags RST RST -j DROP

#Add a local IPv6 interface, this becomes your source ip
ip addr add ::2 dev lo

#Install socat

sudo apt-get install socat

#Set up TCPv4 listener
socat tcp6-l:4321,fork,reuseaddr STDIO
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Define key="TargetIPv6" value="::1"/>
    <Define key="SourceIPv6" value="::2"/>
    <Define key="TargetPort" value="4321"/>
    <Define key="SourcePort" value="5280"/>
    <Define key="Strategy"  value="Sequential"/>
    <Define key="Path" value="."/>
    <Define key="TargetIPBytes" value="C0A89280"/>
    <Define key="SourceIPBytes" value="C0A89201"/>
  </All>

  <Linux platform="linux">
    <Define key="Interface" value="eth0"/>
  </Linux>

  <OSX platform="osx">
    <Define key="Interface" value="en0"/>
  </OSX>

  <Windows platform="windows">
    <Define key="Interface" value="Local Area Connection"/>
  </Windows>
</PitDefines>
----
==========================
