include::TCPv4_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A TCP listener listening on the TCPv4 port defined in configuration file is required. The network tool socat can be used as the listener.

To use this pit, disable outgoing RST packets; Peach manages TCP states outside of the kernel context.

==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
TargetIPBytes:: IP address of the target host machine in hexadecimal.
SourceIPBytes:: IP address of the interface on the local machine in hexadecimal.
SourcePort:: TCPv4 port number of the local machine.
TargetPort:: TCPv4 port number of the target host machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug TCPv4.xml
----
==== Full test run
----
peach TCPv4.xml
----

=== Examples

.Sample TCPv4 Configuration File
==========================
Example configuration using socat on Linux.

First we must configure the firewall then install and run socat; for this example we assume you are running Linux. For other platforms follow the platform specific installation instructions for socat and firewall configuration.

[source,bash]
----
#Disable outgoing RST on the node running Peach
sudo iptables -A OUTPUT -p tcp -m tcp --tcp-flags RST RST -j DROP

#Install socat

sudo apt-get install socat

#Set up TCPv4 listener
socat tcp4-l:12345,fork,reuseaddr STDIO
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="127.0.0.1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/tcp/"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="12345"/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="52080"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
    <String key="TargetIPBytes" value="C0A89280"/>
    <String key="SourceIPBytes" value="C0A89201"/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="en0"/>
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
  </Windows>
</PitDefines>
----
==========================
