include::TELNET_DataSheet.adoc[]

=== Configuration

==== Target Configuration

A Telnet server is required to test the client side of the Telnet pit.
On Linux, telnetd can be downloaded using apt-get.

==== Required Pit Configuration Changes

TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
SourcePort:: Telnet port number of the local machine.
TargetPort:: Telnet port number of the target host machine.
Interface:: Name of local interface (used for monitoring).
Username:: User name of the remote Telnet account.
Password:: Password for the associated Telnet user account.
Program:: The client program to test when fuzzing as the server.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run

.Fuzzing a telnet client
----
peach -1 --debug TELNET_Client.xml
----

.Fuzzing a telnet server
----
peach -1 --debug TELNET_Server.xml
----

==== Full test run

.Fuzzing a telnet client
----
peach TELNET_Client.xml
----

.Fuzzing a telnet server
----
peach TELNET_Server.xml
----

=== Examples

.Sample Telnet Server Configuration File
==========================
Example configuration using telnetd on Linux.

First we must install the telnet server telnetd; for this example we assume you are running on Ubuntu or Debian. A test user account must also be created.

----
# Install telnet server on Linux
sudo apt-get install telnetd

# Add a test user account with password telnetuserp455
sudo adduser telnetuser
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="Username"
				value="telnetuser"
				name="Username"
				description="Username to use when logging into telnet server."/>
		<String key="Password"
				value="telnetuserp455"
				name="Password"
				description="Password to use when logging into telnet server."/>
		
		<Ipv4 key="TargetIPv4"
			  value="127.0.0.1"
			  name="Target IPv4 Address"
			  description="The IPv4 address of the target machine or device. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field." />

		<Range key="TargetPort"
			   value="23"
			   min="0"
			   max="65535"
			   name="Target Port"
			   description="The target or destination port the network packet is sent to."/>

		<String key="LoggerPath"
				value="logs/telnet_client/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================

.Sample Telnet Client Configuration File
==========================

The Telnet Client Pit file will simulate a telnet server to perform fuzzing of a telnet client application. This example configuration assumes the user is running on Ubuntu Server LTS.

.Install telnet on Linux 
----
sudo apt-get install telnet
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<Ipv4 key="SourceIPv4"
			  value="127.0.0.1"
			  name="Source IPv4 Address"
			  description="The IPv4 address of the machine running Peach Fuzzer. The IPv4 address can be found on Windows by running 'ipconfig' and looking for the 'IPv4 Address' field. For Linux run 'ifconfig' and look for 'inet addr' field. For OS X run 'ifconfig' and look for the 'inet' field."/>

		<Range key="SourcePort"
			   value="23"
			   min="0" max="65535"
			   name="Source Port"
			   description="The source port the network packet originates from."/>

		<String key="LoggerPath"
				value="logs/telnet_server/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />

		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />

		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library."/>
	</All>
</PitDefines>
----
==========================
