include::TELNET_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A Telnet server is required to test the client side of the Telnet pit.
On Linux, telnetd can be downloaded using apt-get.



==== Required Pit Configuration Changes
TargetIPv4:: IP address of the target host machine.
SourceIPv4:: IP address of the interface on the local machine.
SourcePort:: Telnet port number of the local machine.
TargetPort:: Telnet port number of the target host machine.
Interface:: Name of local interface (used for monitoring).
Username:: User name of the remote Telnet account.
Password:: Password for the associated Telnet user account.
Program:: The client program to test when fuzzing as the server.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
#Test client
peach -1 --debug TELNET_Client.xml

#Test server
peach -1 --debug TELNET_Server.xml
----
==== Full test run
----
#Test client
peach TELNET_Client.xml

#Test server
peach TELNET_Server.xml
----

=== Examples

.Sample Telnet Configuration File
==========================
Example configuration using telnetd on Linux.

First we must install telnet and telnetd; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the platform specific installation instructions for telnet and telnetd.

----
#Install telnet and telnet server on Linux
sudo apt-get install telnet
sudo apt-get install telnetd

#Download Putty for Telnet windows. Putty can be downloaded using the link below
http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="23"/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="31337"/>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="127.0.0.1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="./logs/telnet/"/>
    <Strategy key="Strategy" name="name" description="" value="Random"/>
    <String key="Username" value="username"/>
    <String key="Password" value="password"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
    <String key="Program" name="Program" description="" value="telnet"/>
    <String key="Agent" value="Linux"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="en0"/>
    <String key="Program" name="Program" description="" value="telnet"/>
    <String key="Agent" value="OSX"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
    <String key="Program" name="Program" description="" value="putty.exe"/>
    <String key="Agent" value="Windows"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
  </Windows>
</PitDefines>
----
==========================
