include::UDPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A UDP listener listening on the UDPv6 port defined in configuration file is required. The network tool socat can be used as the listener.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
SourcePort:: UDPv6 port number of the local machine.
TargetPort:: UDPv6 port number of the target host machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug UDPv6.xml
----
==== Full test run
----
peach UDPv6.xml
----

=== Examples

.Sample UDPv6 Configuration File
==========================
Example configuration using socat on Linux.

First we must install socat and configure socat to listen for packets; for this example we assume you are running Linux. For other platforms follow the platform specific installation instructions for socat.

----
sudo apt-get install socat

socat STDIO udp6-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Define key="TargetIPv6" value="::1"/>
    <Define key="LoggerPath" value="logs/udpV6/"/>
    <Define key="SourceIPv6" value="::1"/>
    <Define key="SourcePort" value="12345"/>
    <Define key="TargetPort" value="12345"/>
    <Define key="Strategy"  value="Sequential"/>
    <Define key="PitLibraryPath" value="."/>
  </All>

  <Linux platform="linux">
    <Define key="Interface" value="eth0"/>
  </Linux>

  <OSX platform="osx">
    <Define key="Interface" value="en0"/>
  </OSX>

  <Windows platform="windows">
    <Define key="Interface" value="Local Area Connection"/>
  </Windows>
</PitDefines>
----
==========================
