include::UDPv6_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A UDP listener listening on the UDPv6 port defined in configuration file is required. The network tool socat can be used as the listener.

==== Required Pit Configuration Changes
TargetIPv6:: IP address of the target host machine.
SourceIPv6:: IP address of the interface on the local machine.
SourcePort:: UDPv6 port number of the local machine.
TargetPort:: UDPv6 port number of the target host machine.
Interface:: Name of local interface (used for monitoring).

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug UDPv6.xml
----
==== Full test run
----
peach UDPv6.xml
----

=== Examples

.Sample UDPv6 Configuration File
==========================
Example configuration using socat on Linux.

First we must install socat and configure socat to listen for packets; for this example we assume you are running Linux. For other platforms follow the platform specific installation instructions for socat.

----
sudo apt-get install socat

socat STDIO udp6-listen:12345
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="::1"/>
    <String key="LoggerPath" name="Logger Path" description="" value="logs/udpV6/"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="::1"/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="12345"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="12345"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
  </Linux>

  <OSX>
    <Iface key="Interface" name="name" description="" value="en0"/>
  </OSX>

  <Windows>
    <Iface key="Interface" name="name" description="" value="Local Area Connection"/>
  </Windows>
</PitDefines>
----
==========================
