
:Doctitle: UDPv6 Peach Pit Data Sheet
:Description: User Datagram Protocol version 6 (UDPv6)

 * Peach Pit: UDPv6
 * Direction: Client
 * Supported Platforms: Windows, Linux, OS X

The User Datagram Protocol (UDP) is one of the core members of the Internet protocol suite, which allows computer applications to send messages (which may be referred to as datagrams) to other hosts on an Internet Protocol (IP) network without prior communications in order to set up special transmission channels or data paths.

UDP uses a simple transmission model with a minimum of protocol mechanism. UDP is a protocol over IP; it does not add any complexity to verify that its messages got to where they were supposed to go. 

UDP has no handshaking dialogs; the user's program is exposed to any underlying network protocol unreliability. This means that there is no guarantee of delivery, ordering, or duplicate protection.


=== Specifications


[options="header"]
|========
|Specification | Title
|RFC768  | User Datagram Protocol
|========

=== Use Cases


[options="header"]
|========
|Messages | Specification
|UDP Header | RFC768
|========
