
:Doctitle: UDPv4 Peach Pit Data Sheet
:Description: User Datagram Protocol version 4 (UDPv4)

 * Peach Pit: UDPv4
 * Direction: Client
 * Supported Platforms: Windows, Linux, OS X

The User Datagram Protocol (UDP) is one of the core members of the Internet protocol suite. It allows applications to send messages (called datagrams) to other hosts on an Internet Protocol (IP) network. Messages are stateless and can be sent without prior communications to set up special transmission channels or data paths.

UDP uses a simple transmission model with a minimum of protocol mechanism. It has no handshaking dialogues, and thus exposes any underlying network protocol unreliability to the user's program. As this is normally IP over unreliable media, there is no guarantee of delivery, ordering, or duplicate protection.

=== Specifications


[options="header"]
|========
|Specification | Title
|RFC768  | User Datagram Protocol
|========

=== Use Cases


[options="header"]
|========
|Messages | Specification
|UDP Header | RFC768
|========
