include::VXLAN_DataSheet.adoc[]

=== Configuration

==== Target Configuration
Setting up VXLAN is a multi-step process. In order to simplify the setup, please refer to to VMware's official VLXAN deployment guide http://www.vmware.com/files/pdf/techpaper/VMware-VXLAN-Deployment-Guide.pdf[here]

==== Required Pit Configuration Changes
TargetIPv6:: IPv6 address of the target host machine.
SourceIPv6:: IPv6 address of the interface on the local machine.
TargetIPv4:: IPv4 address of the target host machine.
SourceIPv4:: IPv4 address of the interface on the local machine.
SourceMAC:: MAC address on local machine.
TargetMAC:: MAC address of target machine.
OuterTargetIPv4:: IPv4 address of the target host machine.
OuterSourceIPv4:: IPv4 address of the interface on the local machine.
OuterSourceMAC:: MAC address on local machine.
OuterTargetMAC:: MAC address of target machine.
Tag:: VXLAN identifier specifying the VXLAN to which the frames belong.
Interface:: Name of local interface (used for monitoring).
SourcePort:: UDPv4 and/or TCPv4 port number of the local machine.
TargetPort:: UDPv4 and/or TCPv4 port number of the target host machine.

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug VXLAN.xml
----
==== Full test run
----
peach VXLAN.xml
----

=== Examples

.Sample VXLAN Configuration File
==========================
Example configuration for sending vxlan packets.
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <String key="OuterSourceMAC" value="000000000000"/>
    <String key="OuterSourceIPv4" value="10.6.66.51" />
    <String key="OuterTargetMAC"   value="000000000000"/>
    <String key="OuterTargetIPv4" value="10.6.66.52"/>
    <String key="LoggerPath" name="Logger Path" description=""  value="logs/vxlan/"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <Hwaddr key="SourceMAC" name="Source MAC Address" description="" value="000000000000" />
    <Hwaddr key="TargetMAC" name="Target MAC Address" description="" value="000000000000"/>
    <Ipv4 key="TargetIPv4" name="Target IP Address" description="" value="127.0.0.1"/>
    <Ipv4 key="SourceIPv4" name="Source IP Address" description="" value="127.0.0.1"/>
    <Ipv6 key="TargetIPv6" name="Target IP Address" description="" value="::1"/>
    <Ipv6 key="SourceIPv6" name="Source IP Address" description="" value="::1"/>
    <String key="Tag" value="1"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
    <Range key="SourcePort" name="name" description="" min="0" max="65535" value="12345"/>
    <Range key="TargetPort" name="name" description="" min="0" max="65535" value="12345"/>
  </All>

  <Linux>
    <Iface key="Interface" name="name" description="" value="eth0"/>
  </Linux>

  <OSX>
    <!-- This can't run on OS X because it uses the RawEther publisher. -->
  </OSX>

  <Windows>
    <!-- This can't run on windows because it uses the RawEther publisher. -->
  </Windows>
</PitDefines>
----
==========================
