<<<
[[Fixups_CiscoFixup]]
== CiscoCdpChecksum

// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include use case "This is used when fuzzing {0} protocols"
// Show example of output 
// Give full pit to run using hex publisher 
// List Parent element types  

// Updated:
// 2/21/14: Mick
// expanded description
// Added parent types
// Added full example

The _CiscoCdpChecksum_ is a Custom Peach algorithm to fix  Cisco's one-off error in their CRC implementation (known feature).
It is defined in RFC1071.
It can be found in the Open source CRCTool Library.
This is used when fuzzing protocols that perform the Cisco implementation of CRC.

=== Parent Elements

 * xref:Number[Number]
 * xref:String[String]

=== Parameters

xref:ref[ref]:: Reference to data element which the CRC calculation will be performed on.

=== Examples

.Basic Usage Example
======================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="checksum" size="16">
			<Fixup class="CiscoCdpChecksum">
				<Param name="ref" value="Packet" />
			</Fixup>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----
======================
