<<<
[[Fixups_ScriptFixup]]
== Script

// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include use case "This is used when fuzzing {0} protocols"
// Give full pit to run using hex publisher 
// Example 1 Use peach sample python fixup 
// List Parent element types
//  Must match return value of fixup Explain in section 

// Updated:
// - 02/18/2014: Mick
// Added full examples
// Added description


The _Script_ is a proxy that allow you to write fixups in a scripting language like python or ruby.
The class parameter is required for python fixups. It has two arguments--self (a python construct inherent in the language) and element (the data element being "fixed up").
The class parameter's returned argument must match the DataElement type of the Fixup's parent.

=== Parent Elements

 * Parent type must match the DataElement type returned by the Fixup.

=== Parameters

xref:ref[ref]:: Reference to data element which the calculation will be performed on
class:: Reference to Python class to call

=== Examples

.Basic Usage Example
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<Import import="MathWrapperFixup.py" />

	<DataModel name="TheDataModel">
		<Number name="FirstNumber"  size="16" endian="big" value="10"/>
		<Number name="Log10Number" size="16"  endian="big">
			<Fixup class="Script">
				<Param name="ref" value="FirstNumber" />
				<Param name="class" value="MathWrapperFile.MathWrapper" />
			</Fixup>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="TheDataModel" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

[source,python]
----
# MathWrapperFixup.py
import math
class MathWrapper:
  def __init__(self, parent):
    self._parent = parent
  def fixup(self, element):
    return int(math.log10(element.DefaultValue))
----
====================
