[[Fixups_SequenceIncrementFixup]]


// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include 
//   Use case "This is used when fuzzing {0} "
//   Will return number within valid range of parent number 
//   Actions that increment number are call, set, output 
//   Discuss reentrant / skipto non-determinism 
// Give full pit to run using hex publisher, test works 
// Example 1 
//   Once Param evaluates to true w/multiple output actions 5,5,5 -> 6,6,6
// Example 2 
//   Once evaluates to false w/multiple output actions 1,2,3 -> 4,5,6 
// Example 3 
//   Show example off changing offset w/multiple output actions  
// Test each example works 
// List Parent element types
// Number, String

// Updated:
// - 02/18/2014: Mick
// Added full examples

== SequenceIncrementFixup

The _SequenceIncrementFixup_ will increment each iteration starting at 1.
This is useful when a field must be a unique or sequential value every iteration.
This checksum can be used when fuzzing protocols that contain a incrementing sequence numbers.
The Fixup will produce numbers valid for the DataElement it modifies and is constrained to their size.

=== Parent Elements

 * xref:Number[Number]
 * xref:String[String]
 
=== Parameters

	* _Offset_ -- Sets the initial value each iteration to Offset * (Iteration - 1). Default is null.
	* _Once_ -- Only increment the value once per iteration. Default is false.
 
=== Examples

.Three outputs with Once set to false. The number is incremented before each action.
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="IncrementingNumber" size="16"  endian="big">
			<Fixup class="SequenceIncrementFixup"/>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

.Three outputs with Once set to false and Offset to 5. The number is incremented by 5 each iteration.
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="IncrementingNumber" size="16"  endian="big">
			<Fixup class="SequenceIncrementFixup">
				<Param name="Offset" value="5" />
			</Fixup>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

.Three outputs with Once set to true. Each action outputs the same incremented number.
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="IncrementingNumber" size="16"  endian="big">
			<Fixup class="SequenceIncrementFixup">
				<Param name="Once" value="true" />
			</Fixup>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----
