<<<
[[Fixups_SspiFixup]]
== Sspi

// Updated:
// - 02/18/2014: Mick
// Added full examples

Performs Microsoft SSPI authentication and places the result in the parent 
element. SSPI supports a number of challenge-response authentication protocols.  

This fixup is useful for working with NTLM authentication, with Microsoft 
protocols such as CIFS and SMB, and with authentication across secure boundaries (domains).

[NOTE] The SSPI challenge-response authentication acts more like a CRC or checksum than a protocol. Typically, the SSPI data is within a packet of a protocol, such as CIFS. 

=== Parent Elements

xref:String[String]

=== Parameters

_Required:_

User:: User name of the authorizing account.
Password:: Password associated with the authorizing account.  

_Optional:_

Domain:: Domain in which the authorizing account resides. Default is `""`.
ContinueNeeded:: Reference to key for connection-oriented use in NTLM. 
The value is the name of the field in the state bag that indicates whether 
authrentication continues (as in a connection).

=== Examples

.Sspi Fixup Example

This example consists ot two code fragments: 

* A few lines of Python code takes the received message from the server and places 
it into the Peach state store. The fixup then processes the message text next time 
the script runs:
* A portion of the State model that performs the challenge response authentication. 

[NOTE] The challenge-response authentication requires multiple exchanges between 
the client and the server to complete the authentication process. The example 
shows the portion of the state model that achieves the authentication.

The following Python fragment sets up the storage for the challenge/response value 
in the state bag:

=========================
    import clr
    clr.AddReferenceByPartialName('Peach.Core')

    import Peach.Core
    import System

    def ContinueUpdate(ctx, action):
        securityBuffer = action.dataModel.find('SecurityBuffer')
        if securityBuffer != None:
            ctx.iterationStateStore['Peach.SspiSecurityBuffer'] = securityBuffer.Value
            
=========================


The following pit fragment defines the action to achieve authentication in the state model.

=========================
[source,xml]
----
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">
    
	<DataModel name="Packet">
        <String name="SspiResponse">
			<Fixup class="SspiFixup">
                <String name="User" value="PeachUser"/>
                <String name="Password" value="Calhoun30701"/>
                <String name="Domain" value="CAITLIN" />
                <String name="SecurityContinues" value="" />
		    </Fixup>
        </String>

        <BLob name="UserData" />
    </DataModel>


    <StateModel>
        <State name="Initial">
            <!-- Fill in initial state details -->
        </State>

        <!-- The next state will loop several times to perform
             the challenge-response authentication -->
        <State name="Authenticate">
            <Action type="output" name="SessionSetupRequest">
                <DataModel ref="CIFS:TcpRequest"/>
            </Action>
            
            <Action type="input" name="SessionSetupResponse" 
                onComplete="cifs.ContinueUpdate(Context, Action)">
                
                <DataModel ref="CIFS:TcpResponse"/>
            </Action>

            <!-- Next action does the loop until authenticate is done -->
            <Action type="changeState" ref="Authenticate"
                when="Context.iterationStateStore['Peach.SspiContinueNeeded']" />

            <!-- Authentication complete, goto next state -->
            <Action type="changeState" ref="ConnectIpc" />
        </State>
    </StateModel>

    <!-- Place the remaining pit details here. -->

</Peach>
----

=========================
