<<<
[[Fixups_UDPChecksumFixup]]
== UDPChecksumFixup

// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include use case "This is used when fuzzing {0} protocols"
// Give full pit to run using hex publisher, test example 
// List Parent element types 
// Number, Blob 

// Updated:
// - 02/18/2014: Mick
// Added full examples

The _UDPChecksumFixup_  will produce an internet checksum as defined in RFC 1071.
A discussion on how to apply UDPChecksumFixup can be found in RFC 793 for IPv4 and RFC 2460 for IPv6.
This checksum is primarily used when fuzzing the UDPv4 and UDPv6 Protocols.

=== Parent Elements

 * xref:Number[Number]
 * xref:String[String]
 
=== Parameters

xref:ref[ref]:: Reference to data element on which the checksum will be performed.
src:: Source IP Address. IP address of the local machine. 
dst:: Destination IP Address. IP address of the remote machine.

=== Examples

.UDP Packet Example
===================
This example models a UDP packet which includes use of the UDPChecksumFixup.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="checksum" size="16">
			<Fixup class="UDPChecksumFixup">
				<Param name="ref" value="Packet" />
				<Param name="src" value="192.168.1.10" />
				<Param name="dst" value="192.168.1.11" />
			</Fixup>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----
===================
