:Doctitle: BMP Peach Pit Data Sheet
:Description: BMP Image Format

 * Peach Pit: BMP
 * Supported Platforms: Windows, Linux, OS X

Bitmap is a Microsoft defined file format containing raster graphic images. 
Bitmap files contain fixed sized headers and a variable length pixel array.

The BMP header varies by a the version number; each subsequent version appends fields to end of the previous version. For example:  

* The v2 header is the same header as the v1 header except that there are additional data fields appended to the v1 header 
* The v3 is header is the same header as the v2 header except that there are additional data fields appended to the v2 header 

The file format is closely tied to the DIB internal data structure in the Windows API.

=== Specifications


[options="header"]
|========
|Specification | Title
|http://msdn.microsoft.com/en-us/library/dd183386%28VS.85%29.aspx | Bitmap Header Types
|========

=== Use Cases


[options="header"]
|========
|Supported Headers | Specification
|BITMAPCOREHEADER | Bitmap Header Types
|BITMAPINFOHEADER | Bitmap Header Types
|BITMAPV4HEADER | Bitmap Header Types
|BITMAPV5HEADER | Bitmap Header Types
|========

