include::Ico_DataSheet.adoc[]

=== Configuration

==== Target Configuration
Any number of image viewing programs may be targeted with the Ico file format. Example targets for fuzzing Ico are "feh" on Linux and "mspaint.exe" on Windows.
In the Ico.xml.config pit file, you can set the target program that you are fuzzing, such as feh or mspaint.exe. Normally you would set different target programs for different operating systems.

==== Required Pit Configuration Changes
Seed:: Name of a valid Ico file located in the Samples directory. An empty string indicates use all files in the directory.  Multiple files can be globbed together with an asterisk wildcard.
Target:: The program that will open the fuzzed Ico files

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Directory path to folder where logs will be stored.
Agent:: The agent that will be ran to open the target program. This is generally OS dependent.
Path:: Path to the relative base directory where all pits are located.
SamplePath:: Path to the directory in which the Ico sample files are stored.  Relative to Path.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug Ico.xml
----
==== Full test run
----
peach Ico.xml
----

=== Examples

.Sample Ico Configuration File
==========================
Example configuration using feh on linux. The configuration file also contains settings for mspaint on Windows and preview on OSX:

First we must install feh, for this example we assume you are running on ubuntu or debian. For other platforms follow the  platform specific installation instructions for feh.

----
#Installing feh on linux
sudo apt-get install feh
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Define key="Seed" value="ico_sample_1.ico"/>
    <Define key="Strategy"  value="Sequential"/>
    <Define key="LoggerPath"  value="./logs/ico/"/>
    <Define key="SamplePath" value="_Common/Samples/Image"/>
    <Define key="Path" value="."/>
  </All>

  <Linux platform="linux">
    <Define key="Agent" value="LinuxAgent"/>
    <Define key="Target" value="feh" />
  </Linux>

  <OSX platform="osx">
    <Define key="Agent" value="OsxAgent"/>
    <Define key="Target" value="/Applications/Preview.app/Contents/MacOS/Preview" />
  </OSX>

  <Windows platform="windows">
    <Define key="Agent" value="WinAgent"/>
    <Define key="Target" value="C:\\windows\\system32\\mspaint.exe" />
  </Windows>
</PitDefines>
----

When running this you will see feh repeatedly open and close.

==========================