include::Jpeg2000_DataSheet.adoc[]

=== Configuration

==== Target Configuration
Any number of image viewing programs (like GIMP 2.8 on Linux and Windows) may be targeted with the JPEG2000 file format.

In the JPEG2000.xml.config pit file, you can set the target program (such as GIMP 2.8) that you are fuzzing . If available, you can set different target programs for different operating systems.

==== Required Pit Configuration Changes
Seed:: Name of a valid JPEG2000 file located in the Samples directory. An empty string indicates use all files in the directory.  Multiple files can be globbed together with an asterisk wildcard.
Target:: The program that will open the fuzzed JPEG2000 files

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Directory path to folder where logs will be stored.
Agent:: The agent that will be ran to open the target program. This is generally OS dependent.
Path:: Path to the relative base directory where all pits are located.
SamplePath:: Path to the directory in which the JPEG2000 sample files are stored.  Relative to Path.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug JPEG2000.xml
----
==== Full test run
----
peach JPEG2000.xml
----

=== Examples

.Sample JPEG2000 Configuration File
==========================
Example configuration using feh on Linux. The configuration file also contains settings for gimp on Windows and preview on OSX:

First we must install feh; for this example we assume you are running on Ubuntu or Debian. For other platforms follow the platform specific installation instructions for feh.

----
#Installing feh on linux
sudo apt-get install feh
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <Define key="Seed" value="jpeg2000_sample_01.jp2"/>
    <Define key="Strategy"  value="Sequential"/>
    <Define key="LoggerPath"  value="./logs/JPEG2000/"/>
    <Define key="SamplePath" value="_Common/Samples/Image" />
    <Define key="Path" value="."/>
  </All>

  <Linux platform="linux">
    <Define key="Agent" value="LinuxAgent"/>
    <Define key="Target" value="feh" />
  </Linux>

  <OSX platform="osx">
    <Define key="Agent"  value="OsxAgent"/>
    <Define key="Target" value="/Applications/Preview.app/Contents/MacOS/Preview" />
  </OSX>

  <Windows platform="windows">
    <Define key="Agent" value="WinAgent"/>
    <Define key="Target" value="C:\\Program Files\\GIMP 2\\bin\\gimp-2.8.exe" />
  </Windows>
</PitDefines>
----

When running this you will see feh repeatedly open and close.

==========================
