include::avi_divx_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A video player that supports the avi format is required. The program VLC can be used for this.

==== Required Pit Configuration Changes
Seed:: Name of a valid avi file located in the SamplePath directory. An empty string indicates use all files in the directory.
SamplePath:: Directory path to the directory which the Avi sample files are stored.
Target:: The program that will open the fuzzed Avi files

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.
Agent:: Agent to run depending on the target OS. This value shouldn't be changed.

==== Configure Additional Monitors
Add monitors to agent as needed

=== Running

==== Single test debug run
----
peach -1 --debug avi_divx.xml
----
==== Full test run
----
peach avi_divx.xml
----

=== Examples

.Sample avi_divx Configuration File
==========================
Example configuration using VLC player.

First, install VLC player; for this example we assume you are running on Ubuntu or Debian. For other platforms follow instructions on the VLC http://www.videolan.org/vlc/index.html[website]:

----
sudo apt-get install vlc
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
  <All>
    <String key="Seed" name="name" description="" value="avi_divx_sample*.avi"/>
    <Strategy key="Strategy" name="name" description=""  value="Random"/>
    <String key="LoggerPath" name="Logger Path" description=""  value="./logs/avi_divx/"/>
    <String key="PitLibraryPath" name="Pit Library Path" description="" value="."/>
    <String key="SamplePath" value="##PitLibraryPath##/_Common/Samples/Video"/>
  </All>

  <Linux>
    <String key="Agent" value="Linux"/>
    <String key="Target" name="name" description="" value="vlc" />
  </Linux>
  <OSX>
    <String key="Agent" value="OSX"/>
    <String key="Target" name="name" description="" value="/Applications/VLC.app/Contents/MacOS/VLC" />
  </OSX>

  <Windows>
    <String key="Agent" value="Win"/>
    <String key="Target" name="name" description="" value="C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe" />
</PitDefines>
----

When running this you will see VLC player repeatedly open and close.

==========================
