include::avi_divx_DataSheet.adoc[]

=== Configuration

==== Target Configuration
A video player that supports the avi format is required. The program VLC can be used for this.

==== Required Pit Configuration Changes
Seed:: Name of a valid avi file located in the SamplePath directory. An empty string indicates use all files in the directory.
SamplePath:: Directory path to the directory which the Avi sample files are stored.
Target:: The program that will open the fuzzed Avi files

==== Optional Pit Configuration Changes
Strategy:: Fuzzing strategy Peach will use for testing.
LoggerPath:: Path to folder where logs will be stored.
Path:: Path to the relative base directory where all pits are located.
Agent:: Agent to run depending on the target OS. This value shouldn't be changed.

==== Configure Monitoring

Monitoring must be configured to provide fault detection, data collection, and automation as needed.

=== Running

==== Single test debug run
----
peach -1 --debug avi_divx.xml
----
==== Full test run
----
peach avi_divx.xml
----

=== Examples

.Sample avi_divx Configuration File
==========================
Example configuration using VLC player.

First, install VLC player; for this example we assume you are running on Ubuntu or Debian. For other platforms follow instructions on the VLC http://www.videolan.org/vlc/index.html[website]:

----
sudo apt-get install vlc
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<PitDefines>
	<All>
		<String key="Seed"
				value="avi_divx_sample*.avi"
				name="Seed File"
				description="The name of the sample file to use when fuzzing." />
		
		<Strategy key="Strategy"
				  value="Random"
				  name="Mutation Strategy"
				  description="The mutation strategy to use when fuzzing." />
		
		<String key="LoggerPath"
				value="./logs/avi_divx/"
				name="Logger Path"
				description="The directory where Peach will save the log produced when fuzzing." />
		
		<String key="SamplePath"
				value="./_Common/Samples/Video"
				name="Sample Path"
				description="The directory containing the samples to use when fuzzing." />
		
		<String key="PitLibraryPath"
				value="."
				name="Pit Library Path"
				description="The path to the root of the pit library." />
	</All>
</PitDefines>
----

When running this you will see VLC player repeatedly open and close.

==========================
