#!/usr/bin/env python
from waflib import Utils

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Data.dll',
	'System.Xml.dll',
	'Peach.Core.dll',
	'Peach.Enterprise.dll',
	'PeachFarm.Common.dll',
	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'Ionic.Zip.dll',
]

if bld.env.TARGET == 'win':
	deps.append('System.Data.SQLite.dll')
else:
	deps.append('Mono.Data.Sqlite.dll')

app = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachFarm.Node.dll',
	ide_path = '../Peach Farm',
	csdoc = False,
)

if bld.env.MCS and bld.env.DEST_OS != "win32":
	app.install_755 = 'pf_node'
