#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Data.dll',
	'System.Xml.dll',
	'Peach.Core.dll',
	'Peach.Enterprise.dll',
	'PeachFarm.Common.dll',
	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'Ionic.Zip.Reduced.dll',
	'System.Data.SQLite.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachFarm.Node.dll',
)

if bld.env.MCS and bld.env.DEST_OS != "win32":
	bld.install_files('${BINDIR}','pf_node')
