#!/usr/bin/env python

deps = [
	'Ionic.Zip.dll',
	'NLog.dll',
	'nunit.framework.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'SharpPcap.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Pro.PitTester.dll',
)
