#!/usr/bin/env python

deps = [
	'NLog.dll',
	
	'System.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Data.DataSetExtensions.dll',
	'System.Xml.dll',
	
	'Microsoft.CSharp.dll',
	
	'Peach.Core.dll',

	'Irony.dll',
	'Irony.Interpreter.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Godel.Core.dll',
	ide_path = 'Peach Enterprise',
)



