#!/usr/bin/env python

assets = bld.path.find_node('assets')
content = [
	'LICENSE.txt',
	'package.json',
	'tsd.json',
	'webpack.config.js',
] + bld.path.ant_glob('assets/**/*') + \
	bld.path.ant_glob('app/**/*') + \
	bld.path.ant_glob('typings/**/*')

npm_source = bld.path.ant_glob([
	'package.json',
	'app/**/*',
	'typings/**/*',
	'webpack.config.js',
])

npm_target = [
	'dist/app.js',
	'dist/app.js.map',
	'dist/vendor.js',
	'dist/fontawesome-webfont.ttf',
	'dist/fontawesome-webfont.woff',
	'dist/fontawesome-webfont.woff2',
	'dist/fontawesome-webfont.eot',
	'dist/fontawesome-webfont.svg',
	'dist/glyphicons-halflings-regular.woff',
	'dist/glyphicons-halflings-regular.woff2',
	'dist/glyphicons-halflings-regular.eot',
	'dist/glyphicons-halflings-regular.svg',
	'dist/glyphicons-halflings-regular.ttf',
]

bld(
	name ='Peach.Pro.Web2',
	features = 'peach npm',
	npm_source = npm_source,
	npm_target = npm_target,
	install_path = '${BINDIR}/public',
	ide_content = content,
	install_644 = {
		assets : assets.ant_glob('**/*'),
	}
)
