#!/usr/bin/env python

dist = bld.path.find_node('dist')
assets = bld.path.find_node('assets')

content = [
	'LICENSE.txt',
	'package.json',
	'tsd.json',
	'webpack.config.js',
] + bld.path.ant_glob('assets/**/*') + \
	bld.path.ant_glob('app/**/*') + \
	bld.path.ant_glob('typings/**/*')

bld(
	name ='Peach.Pro.Web2',
	features = 'peach npm',
	install_path = '${BINDIR}/public',
	ide_content = content,
	install_644 = {
		dist   : dist.ant_glob('**/*'),
		assets : assets.ant_glob('**/*'),
	}
)
