[[CI_GenericRunner]]
=== Generic CI Runner

Generic integration with CI systems is provided by running a command that
returns non-zero when testing does not pass.
The vast majority of CI systems support this method of integration.

The generic CI integration script is available in SDK\ci\generic.

To use the script, configure your CI system to run this script after setting
correct environmental variables to provide needed configuration.

==== CI Script Logic

The generic CI runner has this high-level flow:

. Load environment variables
. Start new testing session
.. Call peachproxy.session_setup()
.. {product} provides a proxy port and session id
. Launch automation
. Poll {product} to check if tests have finished
. Wait for automation or kill after timeout
. Send session teardown to {product}
.. Call peachproxy.session_teardown()
. If JUnit XML enabled:
.. Call peachproxy.junit_xml()
.. If failures exit with PEACH_EXIT_CODE_FAILURE
.. Else exit with PEACH_EXIT_CODE_OK

If any hard failure occurs, exit with PEACH_EXIT_CODE_ERROR.

==== Environment Parameters

These options are set as environmental variables.

PEACH_API::
    URL to {product} APIs.
    If company policy prohibits the use of 'http', 'https' can be specified instead.
    This will cause testing to complete slower due to TLS negotiation.
    This environmental is required.
    Example: +http://192.168.1.5+

PEACH_API_TOKEN::
    URL to {product} APIs.
    This environmental is required.
    Example: +http://192.168.1.5+

PEACH_PROJECT::
    {product} project name.
    This environmental is required.
    Example: +Default+
    
PEACH_PROFILE::
    Project profile to use.
    This environmental is required.
    Example: +Nightly+
    
PEACH_AUTOMATION_CMD::
    Command line to launch test automation with {product} integration.
    This environmental is required.
    Example: +python /opt/peachweb/sdk/examples/flask_rest_target/hand_fuzz.py+

PEACH_JUNIT (optional)::
    Generate standard JUNIT XML output of results.
    This output can be used by CI's like Jenkins to display
    details of any failures directly in the CI.
    Example: +junit-peachapisec.xml+

PEACH_UI (optional)::
    URL to {product} UI if different from PEACH_API.
    Default to PEACH_API setting.
    Example: +http://peachweb+
    
PEACH_VERBOSE (optional)::
    Show output from automation cmd.  Defaults to False.

PEACH_SYSLOG_HOST (optional)::
    Syslog server host.  
    When set syslog logging is enabled with same log level as console.
    Example: +corplogs.corp.com+
    
PEACH_SYSLOG_PORT (optional)::
    Syslog server port.  
    Defaults to 512.

PEACH_EXIT_CODE_OK (optional)::
    Exit code to return when testing completed with no failure or errors.
    Defaults to 0.
    
PEACH_EXIT_CODE_FAILURE (optional)::
    Exit code to return when testing completed with no errors, but failures
    were found.
    Defaults to 1.
    
PEACH_EXIT_CODE_ERROR (optional)::
    Exit code to return when testing did not complete due to errors.
    Defaults to 100.

==== Usage

To use the script, follow this process:

Install requirements::
+
Install required python modules:
+
  pip install -r requirements.txt

Run script::
+
Linux;;
+
----
PEACH_PROJECT=Default \
PEACH_PROFILE=Quick \
PEACH_API=http://10.10.10.10 \
PEACH_API_TOKEN=b5638ae7-6e77-4585-b035-7d9de2e3f6b3 \
PEACH_AUTOMATION_CMD=python testrunners/custom/python/hand_fuzz.py \
python ci/generic/peach_ci_runner.py    
----
Windows;;
+
----
set PEACH_PROJECT=Default
set PEACH_PROFILE=Quick
set PEACH_API=http://10.10.10.10
set PEACH_API_TOKEN=b5638ae7-6e77-4585-b035-7d9de2e3f6b3
set PEACH_AUTOMATION_CMD=python testrunners\custom\python\hand_fuzz.py
python ci\generic\peach_ci_runner.py
----

TIP: During initial setup it's useful to enable output from your test automation command by
setting +PEACH_VERBOSE=True+.  Remember to disable this once the configuration is working as
the output could be very large.

NOTE: {product} must be running prior to launching this script.
