[[CI_TravisCi]]
== Travis CI

* No inbound access to build machines
* Use cloud CI runner
** Creates SSH tunnels to/from Peach API Security
* Steps
** Create a working .travis.xml to build/test your product
** Create a new SSH key (id_rsa, id_rsa.pub)
** Use travis cli to encrypt (travis encrypt-file id_rsa --add)
** Commit id_rsa.enc, store id_rsa someplace private (NOT IN REPOSITORY)
** 

* Cloud instances have build time limit
** Testing slowed down by tunneling traffic out to Peach API Security


----
language: python
python:
- '2.7'

before_install:
- openssl aes-256-cbc -K $encrypted_db113545913a_key -iv $encrypted_db113545913a_iv -in id_rsa.enc -out id_rsa -d  <1>
- sudo apt-get update -qq
- sudo apt-get install -qq openssh-client   <2>

addons:
  ssh_known_hosts: 52.52.169.252   <3>

install:
- pip install -r flask_rest_target/requirements.txt
- pip install -r cloud-generic/requirements.txt                 <4>
- "cd peachproxy ; python setup.py -q install ; cd .."          <5>
- "cd pytest-peach/src ; python setup.py -q install ; cd ../.." <6>
- "chmod a-rwx id_rsa ; chmod u+r id_rsa"                       <7>

env:
- PEACH_SSH_HOST=52.52.169.252  <8>
  PEACH_SSH_PORT=22  <9>
  PEACH_SSH_ID=id_rsa <10>
  PEACH_SSH_USER=ubuntu  <11>
  PEACH_CONFIG=cloud-generic/peach-web.project <12>
  PEACH_PROFILE=Quick <13>
  PEACH_UI=http://52.52.169.252 <14>
  PEACH_JUNIT=peach_output.xml <15>
  PEACH_AUTOMATION_CMD="pytest --peach=on pytest-peach/test_target.py" <16>
  PEACH_VERBOSE=False  <17>

before_script:
- "nohup python flask_rest_target/rest_target.py &"

script:
- pytest --junitxml=test.xml pytest-peach/test_target.py
- python cloud-generic/peach_cloud_ci_runner.py <18>
----
<1> Decrypt SSH private identity file (id_rsa.enc -> id_rsa)
<2> Install OpenSSH client software ('ssh' command)
<3> Add Peach API Security IP address to known ssh hosts
<4> Install CI runner python requirements
<5> Install Peach API Security API module
<6> Install Peach pytest plugin
<7> Fix permissions on id_rsa file
<8> Set Peach API Security SSH hostname
<9> Set Peach API Security SSH port number
<10> Set Peach API Security SSH private key
<11> Set Peach API Security SSH username
<12> Project name
<13> Project Profile name
<14> UI URL to display in logs
<15> Produce JUnit XML results file
<16> Traffic generator command. This command will run the unit tests with Peach integration
<17> Disable verbose output (hides traffic generator output).  Set to True to enable more output.
<18> Run Peach API Security CI integration script
