[CI_GenericRunner]
== Generic CI Runner

Generic integration with CI systems is provided by running a command that
returns non-zero when testing does not pass.
The vast majority of CI systems support this method of integration.

The generic CI integration script is available in SDK\ci\generic.

To use, update the configuration at top of python file and
configure your CI system to run.

=== Environment Parameters

These options are set as environmental variables.

PEACH_API::
    URL to {product} APIs.
    This environmental is required.
    Example: +http://192.168.1.5:5000+

PEACH_CONFIG::
    {product} local configuration file.
    This environmental is required.
    Example: +/home/jenkins_home/peach-project1.config+
    
PEACH_AUTOMATION_CMD::
    Command line to launch test automation with {product} integration.
    Command should not return until automation has completed.
    This environmental is required.
    Example: +python /opt/peachweb/sdk/examples/flask_rest_target/hand_fuzz.py+

PEACH_UI (optional)::
    URL to {product} UI if different from PEACH_API.
    Default to PEACH_API setting.
    Example: +http://peachweb+
    
PEACH_VERBOSE (optional)::
    Show output from automation cmd.  Defaults to False.

PEACH_SYSLOG_HOST (optional)::
    Syslog server host.  
    When set syslog logging is enabled with same log level as console.
    
PEACH_SYSLOG_PORT (optional)::
    Syslog server port.  
    Defaults to 512.

PEACH_EXIT_CODE_OK (optional)::
    Exit code to return when testing completed with no failure or errors.
    Defaults to 0.
    
PEACH_EXIT_CODE_FAILURE (optional)::
    Exit code to return when testing completed with no errors, but failures
    were found.
    Defaults to 1.
    
PEACH_EXIT_CODE_ERROR (optional)::
    Exit code to return when testing did not complete due to errors.
    Defaults to 100.

==== Usage

To use this script follow this process:

. Create and export a {product} configuration file.
. Save file in place CI system can access
. Configure CI to launch Generic CI Runner script
. Test configuration

NOTE: {product} must be running prior to launching this script.
