#!/bin/bash

DIRNAME="`dirname ${0}`"
DEBUG=""
case "$*" in
  *--debug*)
    DEBUG="--debug"
    ;;
esac

MONO="$(which mono)"

if [ -z $MONO ];
then
	echo "Error: mono could not be found."
	echo ""
	echo "Ensure mono is properly installed and try again."
	echo ""
	exit 1
fi

${MONO} --gc=sgen ${DEBUG} ${DIRNAME}/Peach.exe $@
