#!/usr/bin/env python

deps = [
	'NLog.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

app = bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.exe',
	ver_product = 'Peach Fuzzing Platfom',
	install_644 = 'peach.xsd',
)

# samples folder is installed to output dir by ../SDK/wscript_build

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	app.install_755 = 'peach'

peach_pro = [
	# Peach
	'Peach.exe',
	'Peach.Pro.Web',
	'peach-sdk',

	# Peach Platform Suppoort
	'Peach.Pro.OS.Windows.dll',
	'Peach.Pro.OS.Linux.dll',
	'Peach.Pro.OS.OSX.dll',

	# Include sample programs so sample pits work
	'CrashableServer',
	'CrashingFileConsumer',
	'CrashingProgram',
	'ComTest',

	# Linux core file monitor
	'PeachLinuxCrashHandler.exe',

	# Windows side-process helpers
	'Peach.Pro.ComContainer.exe',
	'Peach.Pro.WindowsDebugInstance.exe',

	# Helper Programs
	'PeachValidator.exe',
	'PeachFuzzBang.exe',
	'PeachMinset.exe',
	'PeachSampleNinja.exe',

	# Basic Block Pin Tool
	'bblocks',
	'bblocks32',
	'bblocks64',

	'IronPython.StdLib', # Python Standard Library
	'pin',               # Pin Binaries
	'VMware-VIX',        # VMWare VIX API
	'CrashWrangler',     # CrashWrangler
]

tgt = '-'.join([ 'peach-pro', bld.env.BUILDTAG, bld.variant ])

bld(
	features = 'zip',
	name = tgt,
	use = peach_pro,
)

farm = [
	'pf_admin.exe',
	'pf_controller.exe',
	'pf_node.exe',
	'PeachFarmMonitor',
	'PeachFarm.Reporting.Service.exe',
]

tgt = '-'.join([ 'peach-ent', bld.env.BUILDTAG, bld.variant ])

bld(
	features = 'zip',
	name = tgt,
	use = peach_pro + farm,
)

