#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Configuration.dll',
	'System.Core.dll',
	'System.Drawing.dll',
	'System.Windows.Forms.dll',
	'PeachFarm.Common.dll',
	'PeachFarm.Reporting.Reports.dll',
	'Telerik.Reporting.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='PeachFarm.Reporting.dll',
)
