[[ConfigProfiles]]
=== Profiles

Profiles define different testing configurations primarily targetted at CI/CD support.
Profiles can be used in different build pipelines based required testing time.
Over the course of a period of time (say week) all testing can be comapleted
without overly delaying the release of new builds or deployments.

The default profile configurations should be fine to start with.  During the course
of your integration of the tool they can be adjusted as needed.

Quick::
    The Quick profile is used for tests that need a fast turnaround.
    For example, builds performed during the day would use a Quick profile,
    so they are not delayed by security testing.
    +
    The Quick profile should be used in combination with Nightly or Weekly.
    +
    Some checks are performed and fuzzing is disabled in the Quick profile.

Nightly::
    The Nightly profile is used for overnight testing or testing that can take longer
    to complete than Quick.
    All checks are performed during nightly with some fuzzing.
    +
    It's recommended to use Nightly in combination with Weekly.

Weekly::
    The Weekly profile is used for testing over weekends. Weekly testing requires more time
    to complete than the Nightly profile.
    The Weekly profile performs is the amount of fuzzing that is 
    performed during testing.

Full::
    The Full profile is used for single-shot testing.
    It performs complete testing, including checks and fuzzing, in a single run.
    +
    This profile is recommended for manual runs

==== Configuring which Checks Run

To configure which checks run during specific profiles or change specific settings
for said check, navigate to the project page using the top nav.  Each profile will
be listed.  Click on the profile to view a list of Checks and there state (on/off).

Checks listed as On will run as part of the profile.  Checks can be toggled by
clicking the On/Off toggle button.  To configure a specific Check click on it's
name in the list.  For more information about configuring a specific check see
the xref:ChecksAndAsserts[Checks and Asserts] section of this document.

==== Custom Profiles

Custom profiles are not supported in this version of {product}.  They are on our
roadmap and will be released soon.  If you run into a situation in which custom
profiles are required, please contact support via the link:{portalurl}[customer portal]
or our support email {supportemail}.
