[[ConfigRoutes]]
=== Route Configuration

One or more routes can be configured for use with {product}.
Each route contains several configuration parameters.
Route entries are matched in order.
It's recommended that a final route entry be included with a Route pattern of +*+ as a catch all.

Adding multiple routes allows different configurations based on matching a portion of the Path.
For example, if two different APIs are accessed during testing _/storage/*_ and _/users/*_,
each can have a different route entry allowing for different fault status codes
or Swagger API specifications.

_Required:_

Path Pattern:: This pattern will match a specific route to a request.
Define a pattern that matches the HTTP request path (excluding the scheme, host, and query)
using single character wildcard (+?+) and multiple character wildcard (+*+). +
Examples: `/storage/*` or `*/v?/*`

_Optional:_

Test::
	Should the route be included or excluded from testing.
	This setting affects all requests that match the route.
	Default to _included_.

Swagger::
	Optionally provide the URL to a Swagger API JSON.
	For example, _http://127.0.0.1:8888/swagger/docs/v1_ or _file:///opt/service/swagger.js_

Script::
	Optional python script.  Examples provided in SDK/scripts.
	See xref:Scripts[Scripts] for a full explanation and examples.

Rewrite Base URL::
	Optionally provide a new replacement base URL.
	Only the scheme, host, and port are replaced.

Failure Status Codes::
	Optionally provide a comma separated list of HTTP status codes that
	will result in a test failing. When a test fails it is logged as a fault in the tool.
	Example: +500,501+

Header Testing::
+
This parameter controls what HTTP headers are included/excluded from testing.
+
Mutate;; Include or exclude the header from mutation.
Pattern;; Pattern to match against HTTP headers.
+
Headers support pattern matching using the single character wildcard (+?+) or multiple character wildcard (+*+).

API Tokens::
+
This parameter is used to list any/all authentication tokens parameter/headers used
by the APIs under test.
This will enable various checks related to API Tokens.
+
Name;; Include or exclude the header from mutation.
Part;; Where to find the api token, headers, body, etc.
Expires;; Expiration time for the token in minutes
Signature;; Is token a signature of the request (URL, headers, body, etc.)
