#!/usr/bin/env python

deps = [
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.Web.dll',
	'System.Web.Services.dll',
	'System.Configuration.dll',

	'Portable.Licensing.dll',

	'NLog.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Ionic.Zip.dll',

	'IronPython.dll',
	'IronRuby.dll',
	'IronRuby.Libraries.dll',
	'IronRuby.Libraries.Yaml.dll',

	'Microsoft.Dynamic.dll',
	'Microsoft.CSharp.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	
	'Renci.SshNet.dll',
	'Newtonsoft.Json.dll',
	'SuperSocket.Common.dll',
	'SuperSocket.SocketBase.dll',
	'SuperSocket.SocketEngine.dll',
	'SuperWebSocket.dll',

	'Peach.Core.dll',
	'Godel.Core.dll',

	'Nancy.dll',
	'Nancy.Metadata.Module.dll',
	'Nancy.Hosting.Self.dll',
	'Nancy.Serialization.JsonNet.dll',
#	'Nancy.Swagger.Annotations.dll',
#	'Nancy.Swagger.dll',
#	'Swagger.ObjectModel.dll',

	'Managed.Adb.dll',
	'BouncyCastle.Crypto.dll',
	'Syslog.Server.dll',
	'aardvark_net.dll',
	'LibUsbDotNet.dll',
]

if bld.env.TARGET == 'win':
	deps.extend([
		'System.Data.SQLite.dll',
	])
else:
	deps.extend([
		'Mono.Data.Sqlite.dll',
	])

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	resource = bld.path.ant_glob('Resources/**/* WebServices/Views/**/*'),
	content = 'IronPython.StdLib',
	name = 'Peach.Pro.dll',
	namespace = 'Peach.Pro.Core',
)
