#!/usr/bin/env python

deps = [
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.Web.dll',
	'System.Web.Services.dll',
	'System.Configuration.dll',

	'NLog.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
	'Ionic.Zip.dll',

	'IronPython.dll',
	'IronRuby.dll',
	'IronRuby.Libraries.dll',
	'IronRuby.Libraries.Yaml.dll',

	'Microsoft.Dynamic.dll',
	'Microsoft.CSharp.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	
	'Renci.SshNet.dll',
	'Newtonsoft.Json.dll',
	'SuperSocket.Common.dll',
	'SuperSocket.SocketBase.dll',
	'SuperWebSocket.dll',
	'log4net.dll',

	'Peach.Core.dll',
	'Godel.Core.dll',

	'Nancy.dll',
	'Nancy.Hosting.Self.dll',
	'Nancy.Serialization.JsonNet.dll',

	'Managed.Adb.dll',
	'BouncyCastle.Crypto.dll',
	'Syslog.Server.dll',
	'aardvark_net.dll',
]

if bld.env.TARGET == 'win':
	deps.extend([
		'System.Data.SQLite.dll',
	])
else:
	deps.extend([
		'Mono.Data.Sqlite.dll',
	])

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	resource = 'xmltests.zip',
	content = 'IronPython.StdLib',
	name = 'Peach.Pro.dll',
)
