#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'nunit.framework.dll',
	'NLog.dll',
	'Peach.Core.dll',
	'Peach.Pro.OS.Linux.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',	
]

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Pro.Test.OS.Linux.dll',
	ide_path = '../',
)
