#!/usr/bin/env python

'''
tsc = bld(
	rule = 'tsc --target ES5 --out ${TGT} --module amd --removeComments ${SRC}',
	source = bld.path.ant_glob('app/**/*.ts'),
	target = 'all.js',
)

alljs = tsc.to_nodes([tsc.target])

bld.install_files('${BINDIR}/web/app/js', alljs)
'''

extras = []
dirs = [ 'app', 'Content', 'partials', 'Scripts', 'testdata' ]

for d in dirs:
	extras.extend(bld.path.ant_glob('%s/**/*' % d, excl = ['app/js/*', '**/*.ts']))

bld(
	name='Peach.Enterprise.Web',
	install_path = '${BINDIR}/web',
	install_644 = extras,
)
