== SDK

WARNING: This section still under construction.
Information provided is partial and may be out of date.

The SDK can be downloaded from {product} via "Help -> SDK".
The SDK contains:

 * Libraries for {product} API is various languages
 * CI Integrations
 * Test runner plugins and examples
 * Example targets

See the SDK README.txt for more information.

///////////////////////

[[webproxy_Examples]]
=== Examples


This section documents examples provided in the SDK.

==== Flask Rest Target

The flask rest target is a working example of a REST API backed by a SQLite database.
The example target contains one or more SQL injection vulnerabilities that can be 
identified by fuzzing the API.
This example is coded in Python using the Flask framework.

This example includes a configuration (.peach file) that has the correct monitors configured.

===== Important Files

_Target Rest Service_

rest_target.html::
	Very simple UI for Selenium demo

rest_target.py::
	Start target API service using 'http'

rest_ssl_target.py::
	Start target API service using 'https' with yourserver.crt and yourserver.key

_Example Peach Web Configurations_

rest_target.peach::
	Example Peach Web config For fuzzing http version of rest target

rest_ssl_target.peach::
	Example Peach Web config For fuzzing https version of rest target

_Traffic Generation_

test_target.py:: 
	Automated tests using pytest.  Suitable for testing with pytest-peach plugin.

hand_fuzz.py:: 
	Example of a traffic generator written by hand. Has support for http and https versions
	of rest target.  Must edit file to switch between them.

_Example TLS Certificates and Keys_

yourserver.crt::
	Example TLS certificate used by rest_ssl_target.py
	
yourserver.key::
	Example TLS private key used by rest_ssl_target.pyh
	
rootCA.pem::
	Example TLS CA certificate that can be used by Peach

rootCA.key::
	Example TLS CA Private key that can be used by peach
	
clientcert.crt::
	Example TLS Client Certificate that can be used to demo
	client cert authentication.
	
clientcert.key::
	Example TLS Client Private Key that can be used to demo
	client cert authentication.

===== Usage

 . Copy all _.peach_ files to _peach/Configs/Net_
 . Start a configuration
 . Run a traffic generator

*Automated Test Traffic Generator*

Use our pytest integration to generate traffic:

----
pytest --peach=auto test_target.py
----

*Hand Coded Traffic Generator*

An example of a custom traffic generator is _hand_fuzz.py_.

----
python hand_fuzz.py
----

===== Logging & Fault Detection

The Rest Target logs to the console and also syslog to host 127.0.0.1.
The provided Peach Web configurations all contain a Syslog monitor to
process logs generated by the target service.

.Example of SQL statement compile error:
----
<11>2016-04-27 18:28:57,431 [ERROR] Error creating user: near "PO": syntax error
----


///////////////////////