
:Doctitle: CDP Peach Pit Data Sheet
:Description: Cisco Discovery Protocol

 * Peach Pit: CDP
 * Direction: Announce
 * Supported Platforms: Linux

The Cisco Discovery Protocol (CDP) is a proprietary Data Link Layer and Network Layer protocol developed by Cisco Systems. Cisco's multicast announce based protocol is used for neighbor device discovery.
It is supported on numerous Cisco devices as well as many devices designed to inter-operate with Cisco hardware (primarily routers and switches).
This protocol provides similar functionality to vendor-neutral IEEE 802.1AB Link Layer Discovery Protocol designed to replace.

Cisco documentation (once found at http://www.cisco.com/univercd/cc/td/doc/product/lan/trsrb/frames.htm) was used to create this pit. This documentation has since been removed by Cisco; no official documentation is available for reference.

Specifications
--------------

[options="header"]
|========
|Specification | Title
|http://www.cisco.com/univercd/cc/td/doc/product/lan/trsrb/frames.htm | CDP Packet Format
|========

Use Cases
---------

[options="header"]
|========
|Messages | Specification
|Announce | http://www.cisco.com/univercd/cc/td/doc/product/lan/trsrb/frames.htm
|========
