<<<
[[Mutators_ArrayVarianceMutator]]
== ArrayVarianceMutator

This mutator will produce test cases in which the array has been expanded or contracted to produce sizes that are in a distribution with the center of the distribution the current count of the array. For example, if an array contains 100 elements, this mutator will produce test cases in which the array has grown to larger sizes and smaller sizes with the sizes clustered around 100.

NOTE: Currently this mutator is capped at producing 65K array elements. This restriction will change in future releases.

=== Supported Elements

This mutator supports any array element. Array elements are those that have the _occurs_, _minOccurs_, or _maxOccurs_ attributes set.

 * xref:occurs[occurs] attribute
 * xref:minOccurs[minOccurs] attribute
 * xref:maxOccurs[maxOccurs] attribute

=== Hints

This mutator does not support any hints.

NOTE: The an version of this mutator did support a hint. This hint is nolonger required as the underlying algorithm has been contructed to not require it.
