<<<
[[Mutators_ExtraValues]]
== ExtraValues

This mutator allows the user to supply additional values to use in new test cases. Each additional value will have its own test case, generated by this mutator. The additional values will be tested “as is”; that is they will not be altered.

If the _ExtraValues_ hint is not provided, this mutator will not be used.

NOTE: This mutator replaces the ValidValues mutator from previous versions of Peach. Peach will use the old hint, if found; however, you should convert the hint to use the new hint name: _ExtraValues_.

=== Supported Elements

 * xref:String[String]
 * xref:Number[Number]
 * xref:Blob[Blob]

=== Hints

ExtraValues:: Specify a semicolon-seperated list of the values to use in new test cases.

=== Examples

.Providing Extra Values for a String
=================

In this example, three test cases are added to the string _FirstName_.

[source,xml]
----
<String name="FirstName" value="Josh">
    <!-- This will add three test cases -->
    <Hint name="ExtraValues" value="O'Brian;O-Brian;Josh III" />
</String>
----

=================
