<<<
[[Data]]

// Update - 04/04/2014
//  Lynn: Major edits

== Data

At the start of Pit processing, all data sets are either empty or have their values defined in the data model (by the _value_ attributes). Peach uses the Data element to override a _value_ attribute or to assign a value in order to create and load the data into a DataModel.

To match the data into the correct elements, Peach will use the cracking subsystem. This will fail if the data does not fit. 

Data is cracked in a DataModel the same way that we crack an xref:Action_input[input] Action in a StateMode. 

There are currently three ways to load data: 

* a file
* via a python expression
* by setting values field by field

The Data element is a valid top level element (child of <Peach>) when defining sets of data to be referenced later on.  It is also valid as a child of xref:Action[Action] and xref:Param[Param] when used to both define data or reference an existing top level definition.


If multiple Data files xml blocks are specified, the attribute _switchCount_ with the xref:MutationStrategies[random strategy] can be used to specify the number of iterations performed before switching to the next data file.

=== Data and _switchCount_

If there are multiple data elements, after _switchCount_ number of fuzzing iterations, Peach will switch which data element it will use to populate the fuzzing file. 

The following example illustrates this. There are two data elements. Peach will fuzz with the first data element until it does this _switchCount_ number of times and then will switch to the second element and fuzz with that element.

[source,xml]
----

<DataModel name="MyDataModel">
   <Block name="FooBlock">
      <String name="Value" />
   </Block>
</DataModel>

<Data name="HelloWorldDataSet">
  <Field name="FooBlock.Value" value="Hello World!" />
</Data>

<Data name="LoadFromFile" fileName="sample.bin" />

----

=== Attributes

_Required:_

This element does not support any required attributes.

_Optional:_

xref:name[name]:: Name of the Data
xref:fileName[fileName]:: Name of file to load, or folder with files to cycle through

=== Child Elements

 * xref:Field[Field]
 
=== Examples

.Basic Usage Example
====================
Multiple Data elements switched after _switchCount_ iterations

[source,xml]
----

<StateModel name="TheState">
  <State name="initial">
    <Action type="output">
      <DataModel ref="TheDataModel" />
      <Data name="SampleData1">
        <Field name="Block1.Value" value="Hello World!" />
      </Data>
      <Data name="SampleData2">
        <Field name="Block1.Value" value="Good Afternoon World!" />
      </Data>
    </Action>
  </State>
</StateModel>
----
====================
