[[Iteration_fuzzing]]

// Updates:
//
// 03/31/2014 - Lynn: Major edits.

== Fuzzing Iteration

Fuzzing iterations are the most common iteration type. The majority of iterations are usually fuzzing iterations.

A fuzzing iteration mutates the models to produce a fuzz test case that is sent to the target. 

* During a fuzzing iteration we assume that the target will behave in unexpected ways such as errors from our I/O interface (time outs, short writes or reads). 

* After a fuzzing iteration, we probably won't be able to fully execute our state models or correctly crack the returned data. Because  error conditions generated by fuzzing iterations are likely to happen (even if no issue has occurred), they are usually ignored. 

An expected error seen during a fuzzing iteration will at most cause Peach to skip to the next iteration.

For targets that are long running (such as network services), configure the xref:Iteration_control[control iterations] to validate that the target can still correct operation.

See also xref:Iteration_record[record iterations] and xref:Iteration_control[control iterations].
