:images: ../images
<<<

[[JumpStart]]

// Updates
// - 12/30/2015 RAB: Original 

== Jump Starting Peach Fuzzer

Going through the Peach fuzzing workflow is the quickest way to begin fuzzing. 

The workflow is conceptual. It tells you what needs to be done; not how to do it. 
Yet,  when we can, we refer to the appropriate section of the Peach User Guide to perform that part of the workflow. 

NOTE: If you’re unfamiliar with a step of the workflow or if you’re interested in exploring a section, read it. Then, come back to the workflow for its next item.

The workflow includes the following steps. The first item in the workflow is your test target. You should have this item locked down, as it makes the other steps of the workflow easier to get through. 

1.	Pick your fuzzing target
2.	Install Peach
3.	Launch Peach
4.	Pick a Peach Pit (fuzzing definition for your test target)
5.	Specify a test configuration
6.	Running the fuzzing job
7.	Interpreting results.
8.	Fixing the issues and re-running the faulting test cases.

The following is a restatement of the workflow that includes descriptions and appropriate references. After you’ve been through the workflow once or twice, you shouldn’t need to access the details again. 

=== Step 1: Pick your fuzzing target.

A fuzzing target can be just about anything; but, typically it accepts and dispenses data through security boundaries. What’s your fuzzing target:

* An application that consumes files
* A protocol service
* A protocol client
* A device
* Other

Get a good idea of what you need to fuzz.

=== Step 2: Install Peach.

The xref:Installation[Installation] section includes instructions for installing 
Peach Fuzzer on Windows, three Linux implementations, and OS X. The scope of 
material includes downloading distribution images with your Peach license 
through launching the platform to ensure a correct installation. 

The installation also identifies other applications that Peach uses and where needed, provides installation on these items, too.

A video of the installation titled https://vimeo.com/148176046[Installing Your Peach Fuzzer Professional or Enterprise Software] is available at http://www.vimeo.com[vimeo.com].

=== Step 3: Launch Peach

The xref:Start_Peach_Web[Starting the {peachweb}] section describes how to launch Peach and the Peach Web UI. 

[NOTE]
=======

1.	A command processor or command shell at a heightened/administrative level is used to launch Peach due to requirements imposed by a debugger (PageHeap and gdb). 

2.	In the Windows environment, Peach automatically starts a browser and loads the Web UI. 
+
For other environments, you need to copy the URI generated by Peach, launch a browser, and connect to Peach by pasting the URI into the browser address bar.
=======

=== Step 4: Pick a Peach Pit 

From the Peach Web Home page, click the “Library” icon in the group of icons on the left side of the page that are above the menu entries. This action lets you start with a pit that is already installed on your system. 

If you need a Pit that is not in your library, visit the http://peachfuzzer.com[Peach Fuzzer] web page and browse the available http://www.peachfuzzer.com/products/peach-pits/[Pits and Pit Packs]. From the Peach Fuzzer homepage, click on  “Products" in the banner at the top of the page, then click the "Peach Pits” menu entry.

=== Step 5: Specify a Test Configuration 

Specifying a configuration consists of setting variables specific to the selected Pit and defining how to monitor the test subject. Many as the variables you already know or can obtain quickly. Sometimes, the value of a variable depends on the monitoring setup, so some tweaking might be appropriate once you select the monitors to use.

Several configuration recipes are included to provide base configurations for the different fuzzing targets. The recipes also are great starting points for developing your own configurations that precisely monitor the test target for your needs. 

See the section xref:Configuration_Recipes[Configuration Recipes] to view monitor setups for the various test targets on the supported OS platforms.

=== Step 6: Run the Fuzzing Job

Peach Fuzzer runs thousands and millions of test cases. In each fuzzing job, Peach generates test cases randomly with fresh data values. The Peach platform weights the mutations used to generate the most faults. 

Once your configuration is complete, or if you selected an existing configuration, you can start a fuzzing job by clicking a button at the bottom of the configuration page. A fuzzing job can take a long to run to completion.

For example, when fuzzing a new product, you might release criteria of 250,000 total fuzzing test cases to perform on the product with 150,000 of the test cases reporting no faults. Of course, you still need to assess and address the faults that surface. In the second year, the expectations are higher, with 500,000 total test cases performed and 250,000 of those test cases reporting no faults.

=== Step 7: Interpret Results

When the fuzzing job completes, Peach provides an overall status of the job: PASS or FAIL. 

* PASS indicates that the entire fuzzing job ran cleanly without any faults. 
* FAIL indicates one or more faults occurred. 

Hopefully, the Total Faults isn’t too large. But, the faults are where you need to focus, and the faults are where Peach Fuzzer adds value to the SDL. 

From here, look at the overall metrics and the buckets/categories of faults that occur. You should be able to see what worked well and where the issues are. After that, you'll need to investigate the faults, find the root cause of the fault, and then deal with it accordingly. 

You can access faults from the Dashboard page or from the home page, where you can access all of the stored fuzzing job results. 

See the sections xref:Report_Faults[Faults] and xref:Report_Metrics[Metrics] for a description of the information that Peach captures, and how Peach Fuzzer rolls up test case results to provide meaningful views into the fuzzing job.

=== Step 8. Fix Issues and Re-run Test Cases

The last step is to address the faults/issues uncovered during fuzzing, and verifying the fixes. 

* Address the faults +
This item is for the developer, who needs to edit the code where the fault occurred. Use your normal debugging practices here.
* Verifying fixes of issues +
When the fixes are in place, you can re-run a fuzzing job in whole or in part by selecting the Pit Configuration, and then specifying the Seed value of the fuzzing job that you found the fault, the Start Test Case (optional), and the End Test Case (optional).

NOTE: Specifying the same the seed value as in the original fuzzing job ensures that the same test cases are run in the same sequence and with the same order as in the original job.
