[[Param]]
== Param

// Reviewed:
//  - 01/30/2014: Seth & Mike: Outlined

// * valueType, value, name
// * What are they used for
// * cross link to things that take params
// * examples
//  * Different thigns using param
//  * valueType

// Reviewed:
// 04/07/2015 editing and cleanup

Param provides a key-value parameter pair to the parent element. It is used for configuration settings.

Params are common child-element for various xref:AgentsMonitors[Monitors], xref:Publisher[Publishers], and xref:Fixup[Fixups].

[source,xml]
----
<Publisher class="Tcp">
  <Param name="Host" value="127.0.0.1" />
  <Param name="Port" value="80" />
</Publisher>

<Fixup class="Crc32Fixup">
  <Param name="ref" value="MyDataStuff" />
</Fixup>

<Monitor class="WindowsDebugger">
    <Param name="CommandLine" value="CrashableServer.exe 127.0.0.1 4244" />
</Monitor>
----

_Attributes:_

_Required:_

xref:name[name]:: Name of parameter
xref:value[value]:: Default value.

_Optional:_

xref:valueType[valueType]:: Format of value attribute.

=== Child Elements

This element has no valid child elements.

=== _Param_ and the Call Action 

Param  can also be an argument to the xref:Action_call[call] Action. Call actions can have an array of parameters (defined by param) used in different ways by the Publisher.

In this example, the element is solely a container for a DataModel and Data. The Data described in Param will be fuzzed by Peach.

==== Syntax

[source,xml]
----
<Action type="call" method="Players[1].OpenUrl">
  <Param name="P1">
    <DataModel ref="TheDataModel" />
    <Data>
      <Field name="Value" value="video.mov"/>
    </Data>
  </Param>
</Action>
----

==== Attributes

_Required:_

xref:name[name]:: Name of parameter

_Optiona:_

There are no optional attributes for this element.

==== Child Elements

xref:DataModel[DataModel]:: Reference to a DataModel from which fuzzed data will be produced
xref:Data[Data]:: Set of initial data to be cracked into the above DataModel before fuzzing
