:toc!:
[[Publisher]]
== Publishers

// Reviewed:
//  - 02/20/2014: Seth & Mike: Outlined
// * Multible Publishers
// * Types of actions implemented by publishers
// * Stream vs. Stream with end (Tcp vs. File)
// * Stream vs. Call based (Tcp vs. Com)
// * Remote publishers
// * List all action types we utilize

//Updated:
//  - 03/04/2014: Lynn: Added additional Publishers and the note about changState

//Updated:
//  - 03/04/2014: Josh: Added...
// Syntax
// Examples:
// * Multible Publishers
// * Types of actions implemented by publishers
// * Stream vs. Stream with end (Tcp vs. File)
// * Stream vs. Call based (Tcp vs. Com)
// * Remote publishers
// * List all action types we utilize

Publishers are the I/O interfaces used by Peach to send and receive data.
Publishers support both stream and call based operations.

When the fuzzer is running, all xref:Action[Actions] with the exception of ChangeState and slurp use a publisher to
perform the action. Different publishers support a different set of Action types.  For
example, the File publisher supports input for reading from a file, output for writing to a file, but does not support accept or call. This differs from the COM publisher which supports call, but not input, output, or accept.

All fuzzing definitions must use at least one Publisher and can optionally use multiple
Publishers if needed.  When using multiple Publishers, each Action must specify which Publisher it is referencing by referencing to the Publisher's +name+ attribute in the Action's +publisher+ attribute. If the +publisher+ attribute is missing, the Action will be performed on the first Publisher defined in the Test.

|=========================================================================================================
|Publisher|accept|call|changeState|close|getProperty|input|open|setProperty|slurp|start|stop|output
|COM||x|||x|||x||x|x|
|ConsoleHex||||x|||x|||||x
|Console||||x|||x|||||x
|FilePerIteration||||x||x|x|||||x
|FilePublisher||||x||x|x|||||x
|Http||x||x||x|x|||x|x|x
|I2C||||x||x|x|||x|x|x
|Null||x||||||||||x
|RawEther||||x|x|x|x|x||x|x|x
|RawIPv4||||x|x|x|x|x||x|x|x
|RawIPv6||||x|x|x|x|x||x|x|x
|RawV4||||x|x|x|x|x||x|x|x
|Remote|x|x||x|x|x|x|x||x|x|x
|SerialPort||||x||x|x|||x|x|x
|SslClientPublisher||||||x|x|||x|x|x
|SslListenerPublisher|x|||x||x|x|||x|x|x
|Stream|Only base class|||||||||||
|TcpListener|x|||x||x|x|||x|x|x
|TcpClient||||x||x|x|||x|x|x
|Udp||||x|x|x|x|x||x|x|x
|WebService||x||||||||||
|WebSocket||||||||||x|x|x
|===========================================================================================================
.NOTE changeState and slurp cannot be called by any publishers

=== Network Publishers

When fuzzing network protocols, the publisher used is typically the protocol that encompasses the target protocol.
For example, when fuzzing the HTTP protocol the TCP publisher is used.  When fuzzing TCP, the IPv4 or IPv6 publisher is used. When fuzzing IPv4 the Ethernet publisher is used.

=== Custom Publishers

Peach supports the creation of custom Publishers. It is recommended that the code for some
of the existing Publishers be reviewed first to understand how Publishers are typically
implemented.

Creating a custom Publisher does not require changing the Peach source code.  Instead the
code is placed in a new .NET assembly (dll) that is added to the Peach bin folder.  Peach
will automatically use reflection to identify the new Publisher and make it available for
use.

=== Publishers

 * xref:Publishers_AndroidMonkey[AndroidMonkey]
 * xref:Publishers_Com[Com]
 * xref:Publishers_Console[Console]
 * xref:Publishers_ConsoleHex[ConsoleHex]
 * xref:Publishers_File[File]
 * xref:Publishers_FilePerIteration[FilePerIteration]
 * xref:Publishers_Http[Http]
 * xref:Publishers_I2C[I2C] 
 * xref:Publishers_Null[Null]
 * xref:Publishers_RawEther[RawEther]
 * xref:Publishers_RawIPv4[RawIPv4]
 * xref:Publishers_RawIPv6[RawIPv6]
 * xref:Publishers_RawV4[RawV4]
 * xref:Publishers_Remote[Remote]
 * xref:Publishers_SerialPort[SerialPort] 
 * xref:Publishers_SslClient[SslClient] 
 * xref:Publishers_SslListener[SslListener] 
 * xref:Publishers_TcpClient[TcpClient]
 * xref:Publishers_TcpListener[TcpListener]
 * xref:Publishers_Udp[Udp]
 * xref:Publishers_WebService[WebService]
 * xref:Publishers_WebSocket[WebSocket]
 
NOTE: A full list of publishers and parameter information for any
specific version can be found in the output of `peach --showenv`

=== Syntax

[source,xml]
----
<Test name="Default">
  <!-- ... -->
	<Publisher class="ConsoleHex">
	  <Param name="BytesPerLine" value="32"/>
	</Publisher>
  <!-- ... -->
</Test>
----

 
=== Examples

.Multiple Publishers
====================

Though many pits may use a single publisher there is no limit on the
number of publishers that can be used. Multiple publishers can be
defined and used. 

This could be used, for example, to communicate with a network service
that listens on multiple ports:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="Hello">
		<Blob value="Hello Server"/>
	</DataModel>

	<DataModel name="Goodbye">
		<Blob value="Goodbye Server"/>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output" publisher="FirstPort">
				<DataModel ref="Hello"/>
			</Action>
			<Action type="output" publisher="SecondPort">
				<DataModel  ref="Goodbye"/>
			</Action>
		</State>
	</StateModel>
	<Agent name="TheAgent" />
	<Test name="Default">
		<Agent ref="TheAgent"/>
		<StateModel ref="TheState"/>
		<Publisher class="Tcp" name="FirstPort">
			<Param name="Host" value="localhost"/>
			<Param name="Port" value="12345"/>
		</Publisher>
		<Publisher class="Tcp" name="SecondPort">
			<Param name="Host" value="localhost"/>
			<Param name="Port" value="54321"/>
		</Publisher>
		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

----
$ peach -1 --debug TwoPublisher.xml

[[ Peach Pro v3.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 9324.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher start()
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(12 bytes)
Peach.Core.Publishers.TcpClientPublisher 

00000000   48 65 6C 6C 6F 20 53 65  72 76 65 72               Hello Server    

Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher start()
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(14 bytes)
Peach.Core.Publishers.TcpClientPublisher 

00000000   47 6F 6F 64 62 79 65 20  53 65 72 76 65 72         Goodbye Server  

Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:12345
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:12345, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:12345
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:54321
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:54321, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:54321
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.TcpClientPublisher stop()
Peach.Core.Publishers.TcpClientPublisher stop()

[*] Test 'Default' finished.
----
