[[ReproducingFaults]]
== ReproducingFaults

A fault that occurs in a fuzzing session needs to be reproduced so that it can be investigated, understood, and  potentially corrected. 

Peach Pro has the following features that aid in recreating faults that occur during fuzzing:

* Replay the fuzzing session
* Let Peach search to reproduce the fault

:leveloffset: 1
== Replay the Fuzzing Session
This legacy behavior is present in the current edition of Peach Pro. You need the following items to implement this approach:

* The exact version of peach
* The pit used in the fuzzing session (the DataModel and the StateModel must be identical to that used in the fuzzing session)
* The seed value used in the fuzzing session
* The iteration that caused the fault

With this information, you can re-run the appropriate part of the fuzzing session. For an example, see example 9 listed in the the xref:Program_Peach[The Peach Command Line Interface].

If the command line does not specify an iteration range or a starting iteration, the entire fuzzing session runs. This is reasonable for small sessions and for faults that occur near the beginning of a fuzzing session. 

:leveloffset: 1
== Let Peach Search to Reproduce the Fault

This is new behavior. The idea is to automate the search. The following steps describe the major elements of the search:

. Replay the last iteration run (the most recent test). The typically is where the fault surfaces. +
If the fault reproduces, the system logs the information and the search finishes. Otherwise, continue with step 2.
. Replay the last 10 iterations, running them in the same sequence as in the fuzzing session. +
If the fault reproduces, the system logs the information and the search finishes. Otherwise, continue with step 3.
. Double the number of iterations, and run them in the same sequence as in the fuzzing session. +
If the fault reproduces, the system logs the information and the search finishes. If not, continue the search, each time doubling reaching further into the test iterations. The criteria for stopping follows: +
* reproducing the fault
* encountering a critical point in the data, the search to recreate the fault encountered another fualt that peach found and logged during the test session
* encountering a user-specified limit for the search

Using a search limit of 200, the following sets of iterations would run until the limit is reached: +
* 1 iteration +
* 10 iterations +
* 20 iterations +
* 40 iterations +
* 80 iterations +
* 160 iterations +
* 200 iterations (greater than 160 iterations and less than 320 iterations, which is the next cutoff point)

All told, a maximum of 511 iterations would run (1 + 10 + 20 + ... + 200) without human intervention; and some of the iterations would be repeated on subsequent passes.

Some additional considerations about automated fault reproduction include the following:

* If the test target restarts each iteration during fuzzing, the automated recreation feature runs the most recent iteration of the test to try to recreate the fault.
* Control iterations are treated as in a normal fuzzing session. That is, the results of a control iteration serves as a standard of comparison for the results of record iterations. Also, the requency of performaing a control iteration is determined by the _controlIteration_ attribute of the _Test_ element.
* Record iterations are still compared to control iterations. If the results of a record iteration matches the results of a control iteration, all is well and good, and processing advances to the next iterations. If the results of a record iteration do not match the results of a control iteration, the results are logged and the search to reproduce the fault ends.

:leveloffset: 1
== How to Implement the Automated Fault Reproduction

First, if you use a Pit from the current Peach Pit library, the appropriate automated settings are already included in the fuzzing definition. 

If you need to change the setting or if you are defining your own pit, the _Test_ element in the pit has two attributes that apply to Automated Fault Reproduction: _targetLifetime_ and _maxBackSearch_.

* _targetLifetime_ is an enumeration that indicates when the test target restarts. +
*session* means that the target restarts at the start of a session; and, when a fault occurs, Peach will perform the search to recreate the fault, going back several iterations as needed. +
*iteration* means that the target restarts each iteration and that the search consists of re-running the current iteration.
* _maxBackSearch_ indicates the maximum number of iterations to include in the search to to reproduce the fault. The default value is 80. In the previous example, the search reaces into the fuzzing session a maximum of 200 iterations that precede the fault in question.

TIP: If the test target restarts every iteration (as in file fuzzing), set _targetLifetime_ to "iteration".

