[[SampleNinja]]
== Sample Ninja

// 01/30/2014: Seth & Mike: Outlined
//  * Unit test please! - Peter
//  * Review current docs - Peter
//  * Target elements wrong
//  * Hint is wrong
//  * Expand description and how it works

The Sample Ninja mutation engine swaps elements among sample files to generate a new mutated file. Sample Ninja is made up of two components, a command line program that builds and maintains the database, and a mutator that is enabled when a sample ninja database exists.

=== Process

 . Generate a sample ninja database using the PeachSampleNinja.exe command line tool
 . The Sample Ninja Mutator automatically uses the database the next time Peach is run
 . As new sample files are added, re-run Sample Ninja to add the new files.

=== Creating Sample Ninja Database

To generate a new sample ninja database, you need a pit file (fuzzing definition), the name 
of the data model that can crack the sample files and a folder of sample files.  These three items
are passed as command line arguments to the PeachSampleNinja.exe command line tool.

 . Open a new terminal window
 . Change directories to the location of your pit file
 . Run "PeachSampleNinja.exe PITFILE DATAMODEL SAMPLEFOLDER" replacing PITFILE, DATAMODEL, SAMPLEFODLER
with the correct values.
 . Wait while each of your sample files is cracked and added to the sample ninja database
 . After running a new database called "pitfile.ninja" will exist.  If your pit file is "png.xml" then "png.xml.ninja"
will be the name of you sample ninja database.

The next time you run Peach with this pit file the sample ninja database will automatically be used.

=== Adding new sample files to an existing database

 . Open a new terminal window
 . Change directories to the location of your pit file
 . Run "PeachSampleNinja.exe PITFILE DATAMODEL SAMPLEFOLDER" replacing PITFILE, DATAMODEL, SAMPLEFODLER
with the correct values.
 . New files will be added

=== Syntax

Syntax: PeachSampleNinja.exe <pitfile> <datamodel> <samplefolder>

pitfile::
	Fuzzing definition that uses the sample files
datamodel::
	Datamodel able to crack sample file
samplefolder::
	Folder containing sample files

The generated database will be "pitfile.ninja", so if your pit file is "png.xml" you will get "png.xml.ninja".
