[[token]]
== Token Attribute ==

// Reviewed:
//  - 01/30/2014: Seth & Mike: Outlined

// * Discuss
// * Point out we still mutate
// * point out only used on cracking
// * Point out custom mutators can "see" that an element is a token (if they wish)
// * Common usage: Choice blocks, unsized elements
// * Talk about token vs. constraint
//  * Speed difference
//  * constraint doesn't allow length/size
// * Point out token will assign length
// expand description
// * Do we scan by bit or bytes?
//  * Will Number size="3" work?
//  * Will Number size="3" String token=true work?

A token is a data element that Peach will seek when parsing incoming data.  Tokens do not affect how elements are mutated.  If a token attribute is specified the element must have a default value specified in the XML.

// TODO

=== Examples

// Expand on examples with some working examples parsing text.
// Talk about token vs. constraint
// Common usages
//  * Choice statement
//  * Unsized elements
// Comma separated list
// HTTP

To parse and fuzz the header "length" and the value "42". Into the a data model peach can understand that header and value are two different parts tokenized by a ":". 

.Example Data to Crack
----
  length:42 
----

The following model will look for a ":" and put the value of "length" into the header string and a 42 into the val string.

If a ":" is not found in the data stream an exception will be raised and the cracking will fail.

[source,xml]
----
 <String name="header" />
 <String name="delimiter" value=":" token="true"/> 
 <String name="val" /> 
----

.Example Data
----
Host: www.peachfuzzer.com\r\n
----

.Example xml to parse
[source,xml]
----
 <String name="header" />
 <String name="delimiter" value=": " token="true"/>
 <String name="val" />
 <String name="CRLF" value="\r\n" token="true" />
----
