[[ReproducingFaults]]
== Reproducing Faults

A fault that occurs in a fuzzing session needs to be reproduceible so that it can be investigated, understood, and  mitigated.

Peach has the following features that aid in recreating faults that occur during fuzzing:

* Replay the fuzzing session
* Let Peach search to reproduce the fault

:leveloffset: 1
== Replay the Fuzzing Session
This legacy behavior is present in the current edition of Peach Pro. It's primary use is for a developer to investigate a fault and to understand what is happening in the fault.
You need the following items to implement this approach:

* The exact version of peach
* The pit used in the fuzzing session (the DataModel and the StateModel must be identical to those used in the fuzzing session)
* The seed value used in the fuzzing session
* The iteration that caused the fault

With this information, you can re-run the appropriate part of the fuzzing session. For an example, see example 9 listed in the xref:Program_Peach[The Peach Command Line Interface].

If the command line does not specify an iteration range or a starting iteration, the entire fuzzing session runs. This is reasonable for small sessions and for faults that occur near the beginning of a fuzzing session.

:leveloffset: 1
== Let Peach Search to Reproduce the Fault

When Peach detects a fault, it attempts to reproduce the fault. The idea is to automate the search to determine whether a fault consistently reproduces. The following steps describe the major elements of the search:

. Replay the last iteration, the most recent test. This typically is where the fault surfaces. +
If the fault reproduces, the system logs the information and the search finishes. +
If the test target restarts with each fuzzing iteration, the search finishes because the test started in a known, clean state.
Otherwise, continue with step 2.
. Replay the last 10 iterations, running them in the same sequence as in the fuzzing session. +
If the fault reproduces, the system logs the information and the search finishes. Otherwise, continue with step 3.
. Double the number of iterations, and run them in the same sequence as in the fuzzing session. +
If the fault reproduces, the system logs the information and the search finishes. If not, continue the search, each time doubling the number of iterations to run. The criteria for stopping follows: +
* Reproduce the fault.
* Encounter a critical point in the data; the effort to recreate the fault encountered another fault that peach found and logged during the test session.
* Encounter a user-specified limit for the search.

Using a search limit of 200, the following sets of iterations would run until the limit is reached:

* 1 iteration +
* 10 iterations +
* 20 iterations +
* 40 iterations +
* 80 iterations +
* 160 iterations +
* 200 iterations (greater than 160 iterations and less than 320 iterations, which is the next cutoff point)

All told, a maximum of 511 iterations would run (1 + 10 + 20 + ... + 200) without human intervention; and some of the iterations would be repeated on subsequent passes.

Some additional considerations about automated fault reproduction include the following:

* Control iterations are treated as in a normal fuzzing session. That is, the results of a control iteration serves as a standard of comparison for the results of record iterations. Also, the frequency of performing a control iteration is determined by the _controlIteration_ attribute of the _Test_ element.
* Record iterations are still compared to control iterations. If the results of a record iteration matches the results of a control iteration, all is well and good, and processing advances to the next iterations. If the results of a record iteration do not match the results of a control iteration, the results are logged and the search to reproduce the fault ends.

:leveloffset: 1
== How to Implement the Automated Fault Reproduction

First, if you use a licensed Peach Pit, the appropriate automated settings are already included in the fuzzing definition.

If you need to change the setting or if you are defining your own pit, the _Test_ element in the pit has two attributes that apply to Automated Fault Reproduction: _targetLifetime_ and _maxBackSearch_.

* _targetLifetime_ is an enumeration that indicates when the test target restarts. +
*session* means that the target restarts at the start of a session; and, when a fault occurs, Peach performs the search to recreate the fault, going back several iterations as needed. +
*iteration* means that the target restarts each iteration and that the search consists of re-running the current iteration.
* _maxBackSearch_ indicates the maximum number of iterations to include in the search to reproduce the fault. The default value is 80. In the previous example, the search reaches into the fuzzing session a maximum of 200 iterations that precede the fault in question.

TIP: If the test target restarts every iteration (as in file fuzzing), set _targetLifetime_ to "iteration".

// end
