#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'System.dll',
	'System.Core.dll',
	'System.Windows.Forms.dll',
	'System.Data.dll',
	'System.Drawing.dll',
]

pkgs = [
]

bld(
	name='PeachNetworkFuzzer.exe',
	features = 'cs paket',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = ['net45'],
	),
	bintype = 'winexe',
	source = bld.path.ant_glob('**/*.cs'),
)



