#!/usr/bin/env python

# Disable until we figure out what we want to include
'''
bld(
	name='peach-sdk',
	install_path = '${BINDIR}/sdk',
	install_755 = bld.path.ant_glob('**/*', excl='wscript_build')
)
'''
