#!/usr/bin/env python

deps = [
	'nunit.framework.dll',
	'NLog.dll',
	'System.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Drawing.dll',
	'System.Windows.Forms.dll',
	'System.ServiceProcess.dll',
	'Microsoft.CSharp.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'Peach.Core.Test.dll',
]

# Even though this should build via mono, this assembly causes mcs to segfault
# so noly build on windows fore the time being...

bld(
	features = 'cs test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'Peach.Pro.Test.OS.Windows.dll',
	ide_path = '../',
)
