#!/usr/bin/python

import sys
import zipfile

if len(sys.argv) != 2:
    print "Please provide only one zipfile to extract"
else:
    print "Extracting zipfile: ", sys.argv[1]

le_zip = sys.argv[1]
zf = zipfile.ZipFile(le_zip)
zf.extractall('.')
