#!/usr/bin/env python

import os.path
import sys
import zipfile

if len(sys.argv) != 2:
    print "Please provide only one zipfile to extract"
else:
    le_zip = sys.argv[1]
    filename = os.path.split(le_zip)[1]
    dirname = os.path.splitext(filename)[0]
    print "Extracting '%s' to '%s'" % (le_zip, dirname)

    zf = zipfile.ZipFile(le_zip)
    zf.extractall(dirname)
