
[[webproxy_Usage]]
=== Usage

This section provides some example usage patterns for Peach Web.

==== Development/Engineering Team

For teams building web services and web APIs, integration into the CI system or automated test system provides
a lot of advantages over traditional web testing processes.

 * Immediate feedback.
When security testing occurs with every build, security issues are found and fixed much faster.
 
 * Lowered cost of fixing security issues.
The cost to fix a security issue starts increasing as time between when it was authored and discovered grows.
By providing immediate feedback the time between write and fix is shortened.

 * Lowered Cost of Ownership.
Re purposing existing automated tests removes the need to maintain configurations for each API.
Re-using existing tests also quickly provides high test coverage with little effort.

A typical deployment includes the following components:

CI integration::
	CI system's pipeline is configured to include Peach Web testing with specific types of builds.
	For example, nightly builds might be configured to run Peach Web testing for 2 hours each night.
	If security testing fails during those 2 hours, the build would be marked as such, similar to failing
	automated tests.

Automated Test Integration::
	XXX
	
Issue Tracker Integration::
	XXX



==== Redteam or Penetration Tester

Use by individual testers such as redteam members or penetration testers can be achieved in several ways:

. Attack proxies can forward input into Peach for testing.
For example Burp Repeater can be used to forward requests through Peach multiple times.
. A custom traffic generator script can be written in a language known by the tester such as Python.
These scripts are easy and quick to author, in fact existing sample code can be used in many cases.
. Selenium Firefox plugin can be used to record a web session.
Selenium then exports to formats like JUnit that have Peach integrations.
