
[[webproxy_Scripts]]
=== Scripts

The _Script_ configuration option allows custom code to be run after fuzzing but prior to sending outgoing HTTP requests.
This is typically used to implement custom authentication required by the target web service.
When the script is imported, it registers a function with the peach.webproxy python module.
The function will then be called with every outgoing request after all fuzzing has taken place.
This allows arbitrary changes to be made on a per request basis.
Headers can be added/removed and the body can be altered if needed.


.Sample AWS Authentication Script
========================
This example demonstrates how to set the +Authorization+ header in every outgoing request.

----
from peach import webproxy <1>

import base64
import hmac

from hashlib import sha1
from email.Utils import formatdate

AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID'
AWS_SECRET_KEY = 'AWS_SECRET_KEY'

def aws_auth(ctx, req, body): <2>
    XAmzDate = formatdate()

    hdrs = '%s\n\n%s\n\nx-amz-date:%s\n/?policy' % (req.method, req.contentType, XAmzDate)
    h = hmac.new(AWS_SECRET_KEY, hdrs, sha1)
    authToken = base64.encodestring(h.digest()).strip()

    req.headers['x-amz-date'] = XAmzDate
    req.headers['Authorization'] = 'AWS %s:%s' % (AWS_ACCESS_KEY_ID, authToken) <3>

webproxy.register_event(webproxy.EVENT_ACTION, aws_auth) <4>
----
<1> Import peach.webproxy module to register for events
<2> Function has three arguments: Context, Request, Body
<3> Set the header value
<4> Register function with Peach Web
========================
