#!/usr/bin/env python

deps = [
	'NLog.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
	'IronPython.dll',
	'IronPython.Modules.dll',
	'Microsoft.Dynamic.dll',
	'Microsoft.CSharp.dll',
	'Microsoft.Scripting.dll',
	'Microsoft.Scripting.Metadata.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'SharpPcap.dll',
	'PacketDotNet.dll',
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Peach.Pro.ComContainer.exe',
)
