<<<
[[Asn1Tag]]
== Asn1Tag

// Reviewed:
//  - Not yet
//  Edited comments

The _Asn1Tag_ specifies the identifier tag of an ASN.1 data element. This element combines with the Asn1Type and Asn1Length data elements to provide a complete description of an ASN.1 data element. ASN.1 data elements can be primitive (pre-defined) or constructed. 

TIP: This element exists for manually coding ASN.1 data elements. An alternative is to use the ASN.1 analyzer that can generate an ASN.1 data model. 

=== Syntax

[source,xml]
----
<Asn1Tag />
----

=== Attributes
_Required:_

There are no required attributes.

_Optional:_

xref:constraint[constraint]:: Scripting expression that evaluates to true or false, default is "".

*forceMultiByteIdentifier*:: If "true", use multiple identifier octets to contain the identifer of the Asn.1 element. + 
If "false", store the entire tag in the last 5-bits of the first octet. The value of the tag must be 30 or less. + 
The default is "false".
xref:mutable[mutable]:: Is this element mutable, default is "true".
xref:name[name]:: Element name, default is "true".
xref:token[token]:: Is this element a token for parsing, default is "false".
xref:value[value]:: Default value of the Asn.1 identifier tag. If unspecified, the 
    default value of this attribute is "".
xref:valueType[valueType]:: Format of value attribute, default is "string".

=== Child Elements

xref:Fixup[Fixup]:: Performs dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provides information to mutators.
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.
xref:Relation[Relation]:: Identifies a type of relationship with another data element, such as count.
xref:Analyzers[Analyzer]:: Analyzes current element post cracking, can dynamically change model.

=== Mutators

Peach uses the Asn1Type, Asn1Tag, and Asn1Length data elements to create a data model 
that consists of elements such as strings, numbers, binary data and blocks. 
This "downstream" data model is data consumer and the target that Peach fuzzes. 

In short, Peach does not fuzz the Asn1Type, Asn1Ta, or Asn1Length elements.
{nbsp}
[[Asn1Tag_Examples]]
=== Examples

afdsd





