<<<
[[Asn1Length]]
== Asn1Length

// Reviewed:
//  - Not yet
//  Edited comments

The _Asn1Length_ specifies the number of content octets that comprise an ASN.1 data element. This element combines with the Asn1Tag and Asn1type data elements to provide a complete description of an ASN.1 data element. ASN.1 data elements can be primitive (pre-defined) or constructed. 

TIP: This element exists for manually coding ASN.1 data elements. An alternative is to use the ASN.1 analyzer that can generate an ASN.1 data model. 

=== Syntax

[source,xml]
----
<Asn1Length />
----

=== Attributes
_Required:_

There are no required attributes.

_Optional:_

xref:constraint[constraint]:: Scripting expression that evaluates to true or false, default is "".
*indefiniteLength*:: If "true", use the indefinite encoding form of the Asn.1 element. The indefinite 
form requires an end-of-content block. + 
If "false", use definite encoding form, where the number of content octets is known and the octets are available. + 
The default is "false".
*longLength*:: If "true", always use the long encoding form (that is, mulitple length octects) to express the length of the Asn.1 element. + 
If "false", also allow the short encoding form where the number of content octets is expressed in 7 bits (127 or less). +
The default is "false".
xref:mutable[mutable]:: Is this element mutable, default is "true".
xref:name[name]:: Element name, default is "".
xref:token[token]:: Is this element a token for parsing, default is "false".
xref:value[value]:: Default value of the number of Asn.1 content octets. If unspecified, the 
    default value of this attribute is "".
xref:valueType[valueType]:: Format of value attribute, default is "string"

=== Child Elements

xref:Fixup[Fixup]:: Performs dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provides information to mutators.
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.
xref:Relation[Relation]:: Identifies a type of relationship with another data element, such as count.
xref:Analyzers[Analyzer]:: Analyzes current element post cracking, can dynamically change model.


=== Mutators

Peach uses the Asn1Type, Asn1Tag, and Asn1Length data elements to create a data model 
that consists of elements such as strings, numbers, binary data and blocks. 
This "downstream" data model is data consumer and the target that Peach fuzzes. 

In short, Peach does not fuzz the Asn1Type, Asn1Ta, or Asn1Length elements.
{nbsp}
[[Asn1Length_Examples]]
=== Examples

asdfafsfd





