<<<
[[Blob]]
== Blob

// Reviewed:
//  - 03/06/2014: Lynn
//  Edited comments

A Blob footnote:[Blob stands for "binary large object" a term used by databases to represent a column of binary data.] is used to represent binary data (think array of bytes).

A Blob is always a child of a data element container such as xref:DataModel[DataModel] or xref:Block[Block]. Blobs are always sized in bytes, never bits. By default Blobs will be dumb fuzzed (see list of mutators below), as the internal data is unknown.

Blobs can be used to create simple dumb fuzzers in Peach, see xref:Blob_Examples[examples].

=== Syntax

[source,xml]
----
<Blob valueType="hex" value="01 06 22 03" />
----

=== Attributes

_Required:_

There are no required attributes.

_Optional:_

xref:name[name]:: Element name
xref:length[length]:: The length of data in this element.
xref:lengthType[lengthType]:: Units of the length attribute. Defaults to "bytes".
xref:value[value]:: Default value.
xref:valueType[valueType]:: Format of value attribute.
xref:occurs[occurs]::
	Actual occurrences of element. Defaults to 1.

	- Used to define arrays with a static size.
	- Adding this attribute, even with a value of 1 will
	convert it to an array.


xref:minOccurs[minOccurs]::
	The minimum number of times this blob must occur. Defaults to 1.

	- Used to define arrays with a variable size. Arrays defined by min/maxOccurs will generally have a relation
	defined.
	- Adding this attribute, even with a value of 1 will convert it to an array.

xref:maxOccurs[maxOccurs]::
	The maximum number of times this blob can occur. Defaults to 1.

	- Used to define arrays with a static size.
	- Adding this attribute, even with a value of 1 will convert it to an array.

xref:constraint[constraint]::
	A constraint in the form of an expression.  Used during data cracking.
xref:mutable[mutable]::
	Is the blob changeable (should it be fuzzed). Defaults to true.
xref:token[token]::
	This element should be treated as a token when parsing. Defaults to false.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyze current element post cracking, can dynamically change model.
xref:Fixup[Fixup]:: Dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provide information to mutators.
xref:Placement[Placement]:: Relocate an element after it has been cracked.
xref:Transformer[Transformer]:: Static transformations such as compression or encoding.

=== Mutators

The following mutators will operate on this element type.

xref:Mutators_BlobBitFlipperMutator[BlobBitFlipperMutator]:: Flips a percentage of the bits in a blob
xref:Mutators_BlobDWORDSliderMutator[BlobDWORDSliderMutator]:: This mutator will slide a DWORD through the blob
xref:Mutators_BlobMutator[BlobMutator]:: Grows, shrinks, and performs complex manipulations of data in blobs
xref:Mutators_DataElementDuplicateMutator[DataElementDuplicateMutator]:: Duplicates a node's value from 2x - 50x
xref:Mutators_DataElementRemoveMutator[DataElementRemoveMutator]:: Removes nodes from the data model
xref:Mutators_DataElementSwapNearNodesMutator[DataElementSwapNearNodesMutator]::
	Swaps two nodes in the data model that are neighboring each other

xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]::
	Uses the xref:SampleNinja[Sample Ninja] database to swap elements between different sample files

xref:Mutators_SizedDataNumericalEdgeCasesMutator[SizedDataNumericalEdgeCasesMutator]::
	Change the length of the size of a data	element to a range around numerical edge cases
	+
	This mutator is only applied when element is part of a size relationship.

xref:Mutators_SizedDataVarianceMutator[SizedDataVarianceMutator]::
	TODO
	+
	This mutator is only applied when element is part of a size relationship.

[[Blob_Examples]]
=== Examples

.Dumb file fuzzing
==========================
This is an example of dumb file fuzzing. The data from _sample.png_ will be cracked into our Blob. This is considered dumb fuzzing because the data model does not fully describe the structure of the data being fuzzed.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach>

	<DataModel name="TheDataModel">
		<Blob />
	</DataModel>

	<!-- Define a simple state machine that will write the file and
		then launch a program using the FileWriter and DebuggerLaucher publishers -->
	<StateModel name="State" initialState="Initial">
		<State name="Initial">

			<!-- Write out contents of file. -->
			<Action type="output">
				<DataModel ref="TestTemplate" />
				<Data fileName="sample.png" />
			</Action>

			<!-- Close file -->
			<Action type="close" />

			<!-- Launch the file consumer -->
			<Action type="call" method="ScoobySnacks" publisher="Peach.Agent"/>

		</State>
	</StateModel>

	<!-- Setup a local agent that will monitor for faults -->
	<Agent name="LocalAgent">
		<Monitor class="WindowsDebugger">

			<!-- The command line to run.  Notice the filename provided matched up
				to what is provided below in the Publisher configuration -->
			<Param name="CommandLine" value="c:\windows\system32\mspaint.exe fuzzfile.bin" />

			<!-- This parameter will cause the debugger to wait for an action-call in
				the state model with a method="ScoobySnacks" before running
				program.

				Note: You will also need to add a parameter to the publisher called
				    "debugger" and set it to "true"!
				-->
			<Param name="StartOnCall" value="ScoobySnacks" />

		</Monitor>
	</Agent>

	<Test name="Default">
		<Agent ref="LocalAgent" />
		<StateModel ref="State"/>

		<!-- Configure our publisher with correct filename to write too -->
		<Publisher class="File">
			<Param name="FileName" value="fuzzfile.bin" />
		</Publisher>

		<!-- Configure a logger to store collected information -->
		<Logger class="Filesystem">
			<Param name="Path" value="logtest" />
		</Logger>
	</Test>

</Peach>
----
==========================

.Defining a Blob with a default value
==========================
A blob with a default value. Providing a default value does not set a fixed length unless the token="true" attribute is used.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Ex1">
    <Blob name="Unknown1" valueType="hex" value="AA BB CC DD" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output" publisher="ConsolePub">
        <DataModel ref="Ex1" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex" name="ConsolePub"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v0.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 46616.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   AA BB CC DD                                        ????
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----

.Using a Blob as part of a size relationship

A blob with size-of relationship:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Ex1">
    <Number name="LengthOfData" size="32">
      <Relation type="size" of="Data" />
    </Number>

    <Blob name="Data" valueType="hex" value="AA BB CC DD" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output" publisher="ConsolePub">
        <DataModel ref="Ex1" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex" name="ConsolePub"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v0.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 18508.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   04 00 00 00 AA BB CC DD                            ????????
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================
