<<<
[[DataModel]]
== DataModel

The DataModel element is a child of the Peach root element.  A DataModel defines the structure of a data block by specifying additional child elements such as xref:Number[Number], xref:Blob[Blob], or xref:String[String].

=== Syntax

[source,xml]
----
<DataModel name="TheDataModel">
	<String value="Hello World" />
</DataModel>
----

=== Attributes

_Required:_

xref:name[name]:: Friendly name of the DataModel this is useful when referencing the model or debugging.

_Optional:_

xref:ref[ref]:: Reference to a DataModel to use as a template

=== Child Elements

xref:Analyzers[Analyzer]:: Analyze current element post cracking, can dynamically change model.
xref:Blob[Blob]:: Used to represent binary data (think array of bytes) to create simple dumb fuzzers in Peach.
xref:Block[Block]:: Group one or more data elements together into a logical structure.
xref:Choice[Choice]:: Indicate any of the sub-elements are valid but only one should be selected.
xref:Fixup[Fixup]:: Dynamic transformations such as checksums and CRCs.
xref:Flags[Flags]:: Defines a set of bit sized flags.
xref:Hint[Hint]:: Provide information to mutators.
xref:Number[Number]:: Defines a binary number of arbitrary bit size.
xref:Padding[Padding]:: Pad out variably sized blocks or data models.
xref:Placement[Placement]:: Relocate an element after it has been cracked.
xref:Transformer[Transformer]:: Static transformations such as compression or encoding.
xref:XmlElement[XmlElement]:: Defines an XML element, the basic building block of XML documents.

=== Mutators

The following mutators will operate on this element type:

xref:Mutators_DataElementDuplicateMutator[DataElementDuplicateMutator]:: Duplicates a node's value from 2x - 50x
xref:Mutators_DataElementRemoveMutator[DataElementRemoveMutator]:: Removes nodes from the data model
xref:Mutators_DataElementSwapNearNodesMutator[DataElementSwapNearNodesMutator]:: Swaps two nodes in the data model that are neighboring each other

=== Examples

.DataModel Example
===========================
Any number of DataModels can be specified in a Peach Pit file. However, each must each have a unique name. Break complex formats into smaller models by split them into logical parts. This makes DataModels easier to read, debug, and re-use.

A DataModel named "HelloWorld" contains a single string and outputs "Hello world!"

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="HelloWorld">
    <String value="Hello world!" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="HelloWorld" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 63002.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(12 bytes)
00000000   48 65 6C 6C 6F 20 77 6F  72 6C 64 21               Hello world!
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----

DataModels can reference other DataModels and inherit their child elements with the ref attribute.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="ParentModel">
    <String value="Hello " />
  </DataModel>

  <DataModel name="HelloWorldModel" ref="ParentModel" >
    <String value=" world!" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="HelloWorldModel" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug DocSample.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 35043.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(13 bytes)
00000000   48 65 6C 6C 6F 20 20 77  6F 72 6C 64 21            Hello  world!
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
===========================

.References (ref attribute)
===========================

When a reference (ref attribute) is supplied, the contents of the referenced DataModel are copied to create the base of the new DataModel.  Any child elements in the new DataModel will override elements from that base with the same name. In this example the child model Customized contains a String named Key. It's value will overwrite the parent's String "Key" which has no value.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Template">
    <String name="Key" />
    <String value=": " token="true" />
    <String name="Value" />
    <String value="\r\n" token="true" />
  </DataModel>

  <DataModel name="Customized" ref="Template">
    <String name="Key" value="Content-Length" />
    <String name="Value">
      <Relation type="size" of="HttpBody" />
    </String>
    <Blob name="HttpBody" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="Customized" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug DocSample.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

*] Test 'Default' starting with random seed 3945.

R1,-,-] Performing iteration
each.Core.Engine runTest: Performing recording iteration.
each.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
each.Core.Dom.Action ActionType.Output
each.Core.Publishers.ConsolePublisher start()
each.Core.Publishers.ConsolePublisher open()
each.Core.Publishers.ConsolePublisher output(4 bytes)
0000000   3A 20 0D 0A                                        : ?? <1>
each.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
each.Core.Dom.Action ActionType.Output
each.Core.Publishers.ConsolePublisher output(19 bytes)
0000000   43 6F 6E 74 65 6E 74 2D  4C 65 6E 67 74 68 3A 20   Content-Length: <2>
0000010   30 0D 0A                                           0??
each.Core.Publishers.ConsolePublisher close()
each.Core.Engine runTest: context.config.singleIteration == true
each.Core.Publishers.ConsolePublisher stop()

*] Test 'Default' finished.
----

----
<1> The output of "Template"   is " : \r\n"
<2> The output of "Customized" is "Content-Length: 100\r\n"
----

When parsed into a DataModel, Customized will look like the combination of both data models.

[source,xml]
----
<DataModel name="Customized" ref="Template">
  <String name="Key" value="Content-Length" />
  <String value=": " token="true" />
  <String name="Value">
    <Relation type="size" of="HttpBody" />
  </String>
  <String value="\r\n" token="true" />
  <Blob name="HttpBody"/>
</DataModel>
----
===========================
