<<<
[[Json]]
== Json

Json elements are used to organize Peach elements that will be represented as JSON. The output of a Json element will always be valid JSON strings.

If a name attribute is included on an element it will always be used as the "name" portion of the JSON data. If no name is included the elements default name will be used. If the element is included inside of a Sequence element no name will be used as a Sequence represents an array in JSON.

A Json element will always print a "{" at the beginning of the data and a "}" at the end of the data. The following is a list of Peach elements that have different output behavior when placed inside a Json element.

xref:Block[Block]:: When a Block is included within a Json element it is used to represent a new object.
xref:Bool[Bool]:: When a Bool is included within a Json element it is used to represent data that has the value of either 'true' or 'false'.
xref:Null[Null]:: When a Null is included within a Json element it is used to represent data that has the value of 'null'. 
xref:Sequence[Sequence]: When a Sequence is included within a Json element it is used to represent an array of values.

=== Syntax

[source,xml]
----
<Json>
  <String name="Foo" value="Hello world!" />
  <Number name="Num" value="101" />
</Json>
----

=== Attributes

_Required:_

There are no required attributes.

_Optional:_

xref:name[name]:: Name of the Json element.
xref:constraint[constraint]:: Scripting expression that evaluates to true or false. Default is null.
xref:minOccurs[minOccurs]:: The minimum number of times this Json element must occur.
xref:maxOccurs[maxOccurs]:: The maximum number of times this Json element can occur.
xref:occurs[occurs]:: The actual number of times this Json element occurs.
xref:mutable[mutable]:: Is data element changeable (should it be mutated), defaults to false.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyze current element post cracking, can dynamically change model.
xref:Blob[Blob]:: Used to represent binary data (think array of bytes) to create simple dumb fuzzers in Peach.
xref:Block[Block]:: Group one or more data elements together into a logical structure.
xref:Bool[Bool]:: Defines a boolean value.
xref:Choice[Choice]:: Indicate any of the sub-elements are valid but only one should be selected.
xref:Double[Double]:: Defines a floating point number of 32 or 64 bits.
xref:Fixup[Fixup]:: Dynamic transformations such as checksums and CRCs.
xref:Flags[Flags]:: Defines a set of bit sized flags.
xref:Hint[Hint]:: Provide information to mutators.
xref:Null[Null]:: Defines a null value element.
xref:Number[Number]:: Defines a binary number of arbitrary bit size.
xref:Padding[Padding]:: Pad out variably sized blocks or data models.
xref:Placement[Placement]:: Relocate an element after it has been cracked.
xref:Sequence[Sequence]:: Groups one or more data elements together into a logical structure.
xref:Stream[Stream]::  Group one or more data elements together into a logical structure.
xref:Transformer[Transformer]:: Static transformations such as compression or encoding.
xref:XmlElement[XmlElement]:: Defines an XML element, the basic building block of XML documents.

=== Mutators

The following mutators will operate on this element type:


_Enabled when element is marked as an array_

xref:Mutators_ArrayNumericalEdgeCasesMutator[ArrayNumericalEdgeCasesMutator]:: This mutator will grow and shrink an array to counts based on numerical edge cases.
xref:Mutators_ArrayRandomizeOrderMutator[ArrayRandomizeOrderMutator]:: This mutator will randomize the order of items in an array.
xref:Mutators_ArrayReverseOrderMutator[ArrayReverseOrderMutator]:: This mutator will reverse the order of items in an array.
xref:Mutators_ArrayVarianceMutator[ArrayVarianceMutator]:: This mutator will grow and shrink an array to a variance of counts based on the current size.

_Used for all data elements_

xref:Mutators_DataElementBitFlipper[DataElementBitFlipper]:: This mutator will produce test cases by flipping bits in the output value.
xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator will duplicate data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator will remove data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator will swap data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator will combine data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator will cause the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator will cause the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator will change both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator will change both sides of the relation (data and value) to match numerical variances of the current size.


=== Examples

.Empty Json
==========================
The simplest Json element has no children.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">
	<DataModel name="JsonExample">
		<Json>
			
		</Json>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="JsonExample"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>

		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 37920.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(0 bytes)
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================

.Single Child
==========================
The output of Json elements are valid JSON strings.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">
	<DataModel name="JsonExample">
		<Json>
			<Double name="Version" size="32" value="1.1"/>
		</Json>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="JsonExample"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>

		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 30169.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(15 bytes)
00000000   7B 22 56 65 72 73 69 6F  6E 22 3A 31 2E 31 7D      {"Version":1.1}
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================

.Naming A Json Element
==========================
Assign Json elements a friendly name to make them easier to understand and debug.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">
	<DataModel name="JsonExample">
		<Json>
			<Double name="Version" size="32" value="1.1"/>
			<Block name="Obj">
				<String name="City" value="Seattle"/>
				<Bool name="Cold" value="1"/>
			</Block>
		</Json>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="JsonExample"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>

		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 30169.

[*] Test 'Default' starting with random seed 37527.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(52 bytes)
00000000   7B 22 56 65 72 73 69 6F  6E 22 3A 31 2E 31 2C 22   {"Version":1.1,"
00000010   4F 62 6A 22 3A 7B 22 43  69 74 79 22 3A 22 53 65   Obj":{"City":"Se
00000020   61 74 74 6C 65 22 2C 22  43 6F 6C 64 22 3A 74 72   attle","Cold":tr
00000030   75 65 7D 7D                                        ue}}
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================
