#!/usr/bin/env python

tools = [
	'nunit.py',
]

bld.install_files('${BINDIR}', tools, chmod=Utils.O755)

files = [
	'nunit3-to-junit.xsl',
]

bld(
	name='nunit-tools',
	features = 'peach',
	install_path = '${BINDIR}',
	install_755 = tools,
	install_644 = files,
)
