#!/usr/bin/env python

doc = bld(name='peach-userguide-pdf')

doc.install_as(
  '${BINDIR}/peach_pro_v${BUILDTAG}_userguide.pdf',
  doc.path.find_resource('peach_professional.pdf'),
  chmod=Utils.O644,
)

"""
bld(
	features = 'asciidoc',
	source = bld.path.ant_glob('src/**/*.txt'),
	conf = bld.path.find_resource('website.conf'),
	path = bld.path.find_dir('src'),
	name='website',
	install_path='${DOCDIR}/website/',
	relative_trick = True,
)

bld(
	features = 'asciidoc',
	install=bld.path.ant_glob('css/**/*'),
	install_path='${DOCDIR}/website/',
)
"""
