= Peach Downloader

This is the download site for Peach Professional and Peach Enterprise. It requires the user to present a 
valid license file to access downloads and also accept the EULA for downloads.

The site will send the user on a different path depending on the license file path.

This site is intended to allow easy deployment of builds to the site using ssh.

== Builds

A build folder is configured in the web.config. This folder *MUST* live outside of the webroot, but be accessable by 
the web user (on Ubuntu this is www-data). Each build resides in a folder and contains a +release.json+ file.

The +release.json+ file contains information about the build and the available files.

NOTE: This is now the older v1 release.json format.

.release.json
[source,java]
----
{
  "product":"Peach Professional",
  "build":"3.2.15",
  "date":"07/04/2014",
  "nightly":true,
  "pits":"peach-pits-3.2.15.zip",
  "trial":"peach-pits-3.2.15-trial.zip",
  "files":[
    "peach-pro-3.2.15.zip",
    "peach-pro-3.2.15-linux-x86_64-release.zip",
    "peach-pro-3.2.15-linux-x86-release.zip",
    "peach-pro-3.2.15-osx-release.zip",
    "peach-pro-3.2.15-win-x64-release.zip",
    "peach-pro-3.2.15-win-x86-release.zip",
    ],
}
----

== Site Deployment

Peach Downloader is designed to run using Mono ASP.NET.

* Ubuntu Server 14.04 LTS
* Mono 3.2
* mono-fastcgi-server
* nginx

=== Folders

/var/www/dl.peachfuzzer.com:: Contians the ASP.NET files. The +web.config+ must be configured with correct builds path.
/var/www/builds:: Contains different available builds. Each sub-folder must contain a valid +release.json+ file.
/tmp:: Temp folder for creating zip files with pits in them.

=== Steps to deploy

. From Visual Studio publish to folder (right click on PeachDownloader project -> Publish)
. Backup existing +/var/www/dl.peachfuzzer.com+
. Upload/unzip files to +/var/www/dl.peachfuzzer.com+
. Configure build folder and temp folder in +web.config+ (or use existing last version)
. Verify correct permissions +sudo chown -R www-data.www-data+
. Restart mono server +sudo /etc/init.d/monoserve stop+  +sudo /etc/init.d/monoserve start+
.. NOTE: Do not use restart, it will not work correctly.
. Test site

=== nginx configuration

Verify +/etc/nginx/sites-available/default+ is linked to +/etc/nginx/sites-enabled/default+.

./etc/nginx/sites-available/default
----
# HTTPS server
#
server {
        listen 443;
        server_name dl.peachfuzzer.com;

        ssl on;
        ssl_certificate ssl/cert.pem;
        ssl_certificate_key ssl/cert.key;

        ssl_session_timeout 5m;

        ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
        ssl_prefer_server_ciphers on;


        location / {
                root /var/www/dl.peachfuzzer.com/;
                index index.html index.htm default.aspx Default.aspx;
                 fastcgi_index Default.aspx;
                 fastcgi_pass 127.0.0.1:9000;
                 include /etc/nginx/fastcgi_params;
         }
}

# end
----

./etc/nginx/fastcgi_params
----
fastcgi_param   QUERY_STRING            $query_string;
fastcgi_param   REQUEST_METHOD          $request_method;
fastcgi_param   CONTENT_TYPE            $content_type;
fastcgi_param   CONTENT_LENGTH          $content_length;

#fastcgi_param  SCRIPT_FILENAME         $request_filename;
fastcgi_param   SCRIPT_NAME             $fastcgi_script_name;
fastcgi_param   REQUEST_URI             $request_uri;
fastcgi_param   DOCUMENT_URI            $document_uri;
fastcgi_param   DOCUMENT_ROOT           $document_root;
fastcgi_param   SERVER_PROTOCOL         $server_protocol;

fastcgi_param   GATEWAY_INTERFACE       CGI/1.1;
fastcgi_param   SERVER_SOFTWARE         nginx/$nginx_version;

fastcgi_param   REMOTE_ADDR             $remote_addr;
fastcgi_param   REMOTE_PORT             $remote_port;
fastcgi_param   SERVER_ADDR             $server_addr;
fastcgi_param   SERVER_PORT             $server_port;
fastcgi_param   SERVER_NAME             $server_name;

fastcgi_param   HTTPS                   $https if_not_empty;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param   REDIRECT_STATUS         200;

fastcgi_param  PATH_INFO          "";
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
----

=== Mono Server

Link +/etc/init.d/monoserve+ to +/etc/rc2.d/S20monoserve+.

./etc/init.d/monoserve
----
#!/bin/sh

### BEGIN INIT INFO
# Provides:          monoserve.sh
# Required-Start:    $local_fs $syslog $remote_fs
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start fastcgi mono server with hosts
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/mono
NAME=monoserver
DESC=monoserver

MONOSERVER=$(which fastcgi-mono-server4)
MONOSERVER_PID=$(ps auxf | grep fastcgi-mono-server4.exe | grep -v grep | awk '{print $2}')

WEBAPPS="dl.peachfuzzer.com:443:/:/var/www/dl.peachfuzzer.com/"

case "$1" in
        start)
                if [ -z "${MONOSERVER_PID}" ]; then
                        echo "starting mono server"
                        ${MONOSERVER} /applications=${WEBAPPS} /socket=tcp:127.0.0.1:9000 &
                        echo "mono server started"
                else
                        echo ${WEBAPPS}
                        echo "mono server is running"
                fi
        ;;
        stop)
                if [ -n "${MONOSERVER_PID}" ]; then
                        kill ${MONOSERVER_PID}
                        echo "mono server stopped"
                else
                        echo "mono server is not running"
                fi
        ;;
esac

exit 0
----
