#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Configuration.dll',
	'System.Data.dll',
	'System.Drawing.dll',
	'System.Web.dll',
	'System.Web.Extensions.dll',
	'System.Xml.dll',

	'Telerik.Web.UI.dll',

	'NLog.dll',
	'Ionic.Zip.dll',

	'PeachFarm.Common.dll',

	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',

	'MySql.Data.dll',
	'System.Runtime.Serialization.dll'
]

bld(
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs', excl='ReportViewer.*'),
	name = 'PeachFarmMonitor.dll',
	platform = 'AnyCPU', # ASP.NET needs AnyCPU
	ide_path = '../../Peach Farm',
	ide_content = bld.path.ant_glob('dejavulogo.jpg **/*.aspx **/*.asax App_Themes/**/* *.wxs license.rtf'),
	ide_aspnet = True,
	csdoc = False,
)

msi_deps = [
	'PeachFarmMonitor.dll',
	'Telerik.Web.UI.dll',
	'NLog.dll',
	'Ionic.Zip.dll',
	'PeachFarm.Common.dll',
	'RabbitMQ.Client.dll',
	'MongoDB.Driver.dll',
	'MongoDB.Bson.dll',
	'MySql.Data.dll',
]

msi = bld(
	target = 'PeachFarmMonitor',
	features = 'msi',
	use = msi_deps,
	ide = False,
	source = 'WebSite.wxs UI.wxs',
	defines = [ 'WixUILicenseRtf=license.rtf' ],
	extensions = 'WixUIExtension WixIISExtension WixNetfxExtension WixUtilExtension',
	heat = {
		'AppThemeComponents' : 'App_Themes',
	},
)
