<<<
[[Monitors_Android]]
== Android Monitor

The _Android_ monitor monitors both targeted Android applications and the state of the Android OS. 

Two expected use cases are:

* Maintaining state while fuzzing native code
* Launching and monitor Android Java applications. 

This monitor can target both emulated and physical notes. 

The _Android_ monitor requires http://developer.android.com/sdk/index.html[Android Platform Tools] and either an emulator or a physical Android device.

=== Parameters

_Required:_

ApplicationName:: Android Application.

_Optional:_

ActivityName:: Application Activity.
AdbPath:: Directory Path to Adb.
ClearAppData:: Remove Application data and cache on every iteration. Defaults to false.
ClearAppDataOnFault:: Remove Application data and cache on fault iterations. Defaults to false.
CommandTimeout:: Max seconds to wait for adb command to complete (default 10). Defaults to 10.
ConnectTimeout:: Max seconds to wait for adb connection (default 5). Defaults to 5.
DeviceMonitor:: Android monitor to get device serial from.
DeviceSerial:: The serial of the device to monitor.
FaultRegex:: Regex to determine if a log entry triggers a fault. Defaults to `(^E/ActivityMonitor)|(^E/AndroidRuntime)|(^F/.*)`.
FaultWaitTime:: Milliseconds to wait when checking for a fault. Defaults to 0.
IgnoreRegex:: Regex to ignore potential false positive fault matches. Defaults to none.
MustStopRegex:: Trigger a fault and stop fuzzing when regex matches. Defaults to none.
ReadyTimeout:: Max seconds to wait for device to be ready. Defaults to 600.
RebootEveryN:: Reboot device every N iterations.
RebootOnFault:: Reboot device on fault. Defaults to false.
RestartEveryIteration:: Restart Application on Every Iteration. Defaults to false.
StartOnCall:: Start the application when notified by the state machine.
WaitForReadyOnCall:: Waits for the device to be ready when notified by the state machine.

=== Examples

.Basic Usage Example
======================
This example runs the BadBehaviorActivity, sending random taps

To run the Android emulator, set your AdbPath to the directory containing the adb (Android Debug Bridge) platform-tools directory and point the EmulatorPath to the adb tools directory.

The Avd parameter must also be the name of a valid AVD (Android Virtual Device). To create a new AVD:

. Open the 'android.bat' file located in the adb SDK tools directory. 
. From the GUI that opens up click on 'Tools' in the menu bar then 'Manage AVDS...'. 
. From the window that opens up click 'New...' and create a new AVD.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="TheDataModel">
		<Number size='32' signed="false" value="31337" />
	</DataModel>

	<DataModel name="X">
		<Number size='32' signed="false" value="100" />
	</DataModel>

	<DataModel name="Y">
		<Number size='32' signed="false" value="0" />
	</DataModel>

	<StateModel name="State" initialState="Initial" >
		<State name="Initial"  >
			<Action type="call" method="tap">
				<Param>
					<DataModel ref="X"/>
				</Param>
				<Param>
					<DataModel ref="Y"/>
				</Param>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent">
		<Monitor name="Emu" class="AndroidEmulator">
			<Param name="Avd" value="Nexus4" />
			<Param name="EmulatorPath" value="C:\adt-bundle-windows-x86_64-20131030\sdk\tools"/>
		</Monitor>

		<Monitor name="App" class="Android">
			<Param name="ApplicationName" value="com.android.development" />
			<Param name="ActivityName" value=".BadBehaviorActivity" />
			<Param name="AdbPath" value="C:\adt-bundle-windows-x86_64-20131030\sdk\platform-tools"/>
			<Param name="DeviceMonitor" value="Emu" />
		</Monitor>
	</Agent>

	<Test name="Default">
		<StateModel ref="State"/>
		<Agent ref="TheAgent" />

		<Publisher class="AndroidMonkey">
			<Param name="DeviceMonitor" value="App"/>
		</Publisher>

		<Logger class="File">
			<Param name="Path" value="logs"/>
		</Logger>
	</Test>
</Peach>
----

Output for this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 3054.
Peach.Core.Agent.Agent StartMonitor: Emu AndroidEmulator
Peach.Core.Agent.Agent StartMonitor: App Android
Peach.Core.Agent.Agent SessionStarting: Emu
Peach.Enterprise.Agent.Monitors.AndroidEmulator Starting android emulator
Peach.Enterprise.Agent.Monitors.AndroidEmulator Resolved emulator instance to android device 'emulator-5554'
Peach.Enterprise.Agent.Monitors.AndroidEmulator Android emulator 'emulator-5554' successfully started
Peach.Core.Agent.Agent SessionStarting: App
Peach.Enterprise.AndroidBridge Initializing android debug bridge.
Peach.Enterprise.AndroidBridge Android debug bridge initialized.
Peach.Enterprise.Agent.Monitors.AndroidMonitor Resolved device 'emulator-5554' from monitor 'Emu'.
Peach.Enterprise.AndroidDevice Waiting for device 'emulator-5554' to become ready
Peach.Enterprise.AndroidDevice Device 'emulator-5554' is now ready
Peach.Enterprise.AndroidDevice Executing command on 'emulator-5554': am start -W -S -n com.android.development/.BadBehaviorActivity

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Call
Peach.Enterprise.Publishers.AndroidMonkeyPublisher start()
Peach.Enterprise.Publishers.AndroidMonkeyPublisher call(tap, System.Collections.Generic.List`1[Peach.Core.Dom.ActionParameter])
Peach.Core.Agent.AgentManager Message: App => DeviceSerial
Peach.Enterprise.Publishers.AndroidMonkeyPublisher Resolved device 'emulator-5554' from monitor 'App'.
Peach.Enterprise.AndroidDevice Executing command on 'emulator-5554': input tap 100 0
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Enterprise.Publishers.AndroidMonkeyPublisher stop()
Peach.Core.Agent.Agent SessionFinished: App
Peach.Enterprise.AndroidBridge Terminating android debug bridge.
Peach.Core.Agent.Agent SessionFinished: Emu
Peach.Enterprise.Agent.Monitors.AndroidEmulator Sending stop command to emulator 'emulator-5554'
Peach.Enterprise.Agent.Monitors.AndroidEmulator Waiting for emulator 'emulator-5554' to exit
Peach.Enterprise.Agent.Monitors.AndroidEmulator Emulator 'emulator-5554' exited with code: 0
Peach.Enterprise.Agent.Monitors.AndroidEmulator Emulator 'emulator-5554' exited

[*] Test 'Default' finished.
----
======================
