<<<
[[Monitors_ButtonClicker]]
== ButtonClicker Monitor

The _ButtonClicker_ monitor provides mouse click events for popup windows during fuzzing. This monitor runs in the Windows environment. 

The intent of this monitor is to keep a fuzzing session active, regardless of whether popup windows display during fuzzing. 

For example, if an application crashes and restarts, it might display a popup window asking whether to recover a document that was open when the crash occurred. The _ButtonClicker_ monitor could provide a button click in response to the popup window either that would result in discarding the file in question or in recovering the file.

=== Parameters

_Required:_

WindowText:: Text to find in the popup window. Peach performs a string search to determine whether matching text occurs in the popup window.
ButtonName:: Label displayed to the user that is on or near the button that will receive the click.

_Optional:_

None.

=== Examples

.Basic Usage Example
=======================
//TODO: Please provide example

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">
</Peach>
----

//Output for this example.

//----
//>peach -1 --debug example.xml
//
//
//[*] Test 'Default' finished.
----
=======================
