<<<
[[Monitors_CleanupFolder]]
== CleanupFolder Monitor

The _CleanupFolder_ monitor removes the contents created by a target during runtime. The assets are removed prior to every iteration.

When beginning a fuzzing run, Peach creates a list of contents in the directory and removes any new files created.  _CleanupFolder_ cleans up after target execution so your hard drives are not filled with temporary, recovery, and scratch files.

=== Parameters

_Required:_

Folder:: Folder to clean

_Optional:_

None.

=== Examples

ifdef::peachug[]

.Remove contents of a folder +

==============================
This parameter example is from a setup that uses the CleanupFolder monitor to remove a fuzzed file created by the File publisher. At the beginning of each test iteration, the File publisher creates a fuzzed file; at the end of each test iteration, the CleanupFolder monitor deletes all files from the specified folder.

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Folder   |C:\\cleanme
|==========================================================


Output from the setup for this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 43073.
Peach.Core.Agent.Agent StartMonitor: Monitor CleanupFolder
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----
==============================

endif::peachug[]


ifndef::peachug[]

.Remove contents of a folder +

==============================
Run this example from the folder specified using the _folder_ parameter. 

During each iteration, the file +fuzzed.txt+ is created by the File publisher. At the end of each iteration, +fuzzed.txt+ is deleted by the CleanupFolder monitor.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>

      <Action type="output" publisher="FilePub">
          <DataModel ref="TheDataModel"/>
      </Action>

    </State>
  </StateModel>

  <Agent name="TheAgent">
    <Monitor class="CleanupFolder">
      <Param name="Folder" value="C:\\cleanme"/>
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="TheAgent" />

    <Publisher class="ConsoleHex"/>

    <Publisher name="FilePub" class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 43073.
Peach.Core.Agent.Agent StartMonitor: Monitor CleanupFolder
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----
==============================

endif::peachug[]