<<<
[[Monitors_CleanupRegistry]]
== CleanupRegistry Monitor (Windows)

The _CleanupRegistry_ monitor removes a specified registry key, or removes the child keys of a specified registry key.

=== Parameters

_Required:_

Key::
	Registry key to remove. The following *key prefixes* are used:  +
    *HKCU* - Current user  +
	*HKCC* - Current configuration  +
	*HKLM* - Local machine  +
	*HKPD* - Performance data  +
	*HKU* - Users

_Optional:_

ChildrenOnly:: Delete from the registry all subkeys of the specified key. Yet, the specified key and all values attached to the specified key are retained in the registry. Defaults to false.

NOTE: This parameter prunes the registry beneath the specified key, removing all child keys at all levels beneath the specified key. Values attached to child keys are removed as well.

=== Examples

ifdef::peachug[]

.Clean up after office +
This parameter example is from a setup that uses the CleanupRegistry monitor to remove a specified key from the Windows Registry. As shown in the fuzzing output, the registry key is removed at the beginning of a fuzzing session as part of the control iteration.

==================================================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Key   |HKLM\SOFTWARE\Office13\Recovery
|==========================================================

Output for this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 28078.
Peach.Core.Agent.Agent StartMonitor: Monitor CleanupRegistry
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.OS.Windows.Agent.Monitors.CleanupRegistry Removing key: SOFTWARE\Office13\Recovery <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----

<1> Deleting the registry key

==================================================


endif::peachug[]


ifndef::peachug[]


.Clean up after office +
This uses the CleanupRegistry monitor to remove a specified key from the Windows Registry at the beginning of a fuzzing session as part of the control iteration.

========================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="TheAgent">
	<Monitor class="CleanupRegistry">
		<Param name="Key" value="HKLM\SOFTWARE\Office13\Recovery" />
	</Monitor>
 </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="TheAgent" />

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output for this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 28078.
Peach.Core.Agent.Agent StartMonitor: Monitor CleanupRegistry
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.OS.Windows.Agent.Monitors.CleanupRegistry Removing key: SOFTWARE\Office13\Recovery <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----

<1> Deleting the registry key

========================

endif::peachug[]