<<<
[[Monitors_CrashWrangler]]
== CrashWrangler Monitor (OS X)

The _CrashWrangler_ monitor will launch a process and monitor it for crashes. 

This monitor uses Apple's Crash Wrangler tool which can be downloaded from the developer website. The tool must be compiled on each machine it is used to monitor. 

This is the preferred method of catching faults on OS X.

=== Parameters

_Required:_

Command:: Command to execute

_Optional:_

Arguments:: Command line arguments, defaults to none.
StartOnCall:: Start command on state model call, defaults to none.
UseDebugMalloc:: Use OS X Debug Malloc (slower), defaults to false.
ExecHandler:: Crash Wrangler execution handler program, defaults to +exc_handler+.
ExploitableReads:: Are read a/v's considered exploitable? Defaults to false.
NoCpuKill:: Disable process killing by CPU usage, Defaults to false.
CwLogFile:: CrashWrangler Log file, defaults to +cw.log+.
CwLockFile:: CrashWrangler Lock file, defaults to +cw.lock+.
CwPidFile:: CrashWrangler PID file, defaults to +cw.pid+.
FaultOnEarlyExit:: Trigger fault if process exists, defaults to false.
WaitForExitOnCall:: Wait for process to exit on state model call and fault if timeout is reached, defaults to none.
WaitForExitTimeout:: Wait for exit timeout value in milliseconds, -1 is infinite, defaults to 10000.
RestartOnEachTest:: Restart process for each iteration, defaults to false.

=== Examples

.Fuzzing Safari
==================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/> 
      </Action>
      <Action type="close"/> 
    <Action type="call" method="ScoobySnacks" publisher="Peach.Agent"/>

    </State>
  </StateModel>

<Agent name="Local">
	<Monitor class="CrashWrangler">
		<Param name="Command" value="/Applications/Safari.app/Contents/MacOS/Safari" />
			<Param name="Arguments" value="fuzzed.bin" />
			
			<Param name="UseDebugMalloc" value="true" />
			<Param name="ExploitableReads" value="true" />
			<Param name="ExecHandler" value="./exc_handler" />
			
			<Param name="StartOnCall" value="ScoobySnacks" />
	</Monitor>
</Agent>

<Test name="Default">
	<StateModel ref="State"/>
	<Agent ref="TheAgent" />

	<Publisher class="File">
		<Param name="FileName" value="fuzzed.bin"/> 
	</Publisher>
</Test>
</Peach>	
----
==================
