<<<
[[Monitors_CrashReporter]]
== CrashReporter Monitor (OS X)
//needs better more fleshed out example pit

The _CrashReporter_ monitor collects information from crashes detected by the OS X System Crash Reporter.

[IMPORTANT]
====
Before fuzzing, make sure to disable the Apple crash report dialog window, and when the fuzzing session ends, make sure to enable the crash report dialog window. 

* Disable the crash report dialog, using the following command: 
+
defaults write com.apple.CrashReporter DialogType none+. 

* Enable the crash report dialog when you are done fuzzing with the following command: 
+
defaults write com.apple.CrashReporter DialogType crashreport.
====


=== Parameters

_Required:_

None.

_Optional:_

ProcessName:: Name of the process to watch (optional, defaults to all)

=== Examples

ifdef::peachug[]

.Catch all crashes +
====================

This parameter example

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|SerialPort   |COM5
|RelayNumber  |1
|ResetEveryIteration  |false
|==========================================================
====================

endif::peachug[]


ifndef::peachug[]

.Catch all crashes
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="TheAgent">
    <Monitor class="CrashReporter"/>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="TheAgent" />

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----
====================

endif::peachug[]
