<<<
[[Monitors_IpPower9258]]
== IpPower9258 Monitor

The _IpPower9258_ monitor controls a IP Power 9258 Network Power Controller (or Switch). This allows devices plugged into the IP Power 9258 switch to be powered on/off during fuzzing. 

NOTE: IP Power 9258 is the only networked power switch that Peach supports. If you wish to fuzz another networked power controller or switch, you will need to write your own monitor.

Each _IpPower9258_ monitor switches an individual port. To control multiple ports, use multiple _IpPower9258_ monitors. 

You can purchase "IP Power 9258" Remote Network (or Network AC) Power Controllers (or switches) from a variety on online retailers. 

=== Parameters

_Required:_

Host:: Host or IP address (can include HTTP interface port e.g. :8080)
User:: Username
Password:: Password
Port:: Port to reset (1..4)

_Optional:_

ResetEveryIteration:: Reset power on every iteration, default false.
PowerOnOffPause:: Pause in milliseconds between power off/power on, default is 500.

=== Examples

.Reset power on port 1
========================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="Local">
   	<Monitor class="IpPower9258">
    	<Param name="Host" value="192.168.1.1:8080" />
    	<Param name="User" value="peach" />
    	<Param name="Password" value="power" />
    	<Param name="Port" value="1" />
    	<Param name="ResetEveryIteration" value="true" />
  	</Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----
========================
