<<<
[[Monitors_MemoryMonitor]]
== Memory Monitor

The _Memory_ monitor checks the process memory usage and initiates a fault when the memory usage exceeds a specified limit.  This monitor can detect non-crashing extraneous memory usage.

=== Parameters

_Required:_

Must use _MemoryLimit_, and either _Pid_ or _ProcessName_.

MemoryLimit:: Fault when memory usage surpasses limit
Pid:: Process ID to monitor
ProcessName:: Name of the process to monitor


_Optional:_

StopOnFault:: Stop fuzzing if a fault is triggered, defaults to false.

=== Examples

ifdef::peachug[]

.Monitor memory usage of Notepad
====================

This parameter example is from a setup that monitors memory usage of Notepad.

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|MemoryLimit  |10000000
|ProcessName  |Notepad
|==========================================================
====================

endif::peachug[]


ifndef::peachug[]

.Monitor memory via PID
========================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="Memory">
      <Param name="ProcessName" value="Notepad"/>
      <Param name="MemoryLimit" value="10000000" />
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 54974.
Peach.Core.Agent.Agent StartMonitor: Monitor Memory
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----
========================

endif::peachug[]
