<<<
[[Monitors_Pcap]]
== Pcap Monitor

The _Pcap_ monitor performs network captures during the fuzzing iteration. When a packet 
arrives, this monitor writes the content into a file, increments the received packet count, 
and then waits for the next packet to arrive. If a filter is used, the captured packets 
and associated packet count are for packets that pass the filtering criteria.  

The captured data begins afresh for each iteration. If a fault occurs, the captured data is 
logged as a pcap file and returned with the fault data. 

NOTE: The pcap file contains captured data that is compatible with Wireshark and tcpdump.

NOTE: On Windows platforms, the +ipconfig+ utility lists the network devices by name and IP address..

=== Parameters

_Required:_

Device:: Device name or port where the packet capture takes place.

_Optional:_

Filter:: PCAP style filter string. If present, the filter restricts capture to packets that match 
the filter string. For information on filter strings, see www.tcpdump.org, maintained by the TCPDUMP developers, and look for the “Main pcap man page”.

=== Examples

ifdef::peachug[]

.Show the network devices from ipconfig
====================

This example uses ipconfig from the command line to list the available network devices on the 
system. The device names follow:

* Local Area Connection* 2
* Wi-Fi
* Ethernet
* VMware Network Adapter VMnet1
* VMware Network Adapter VMnet8
 
Type the following command and press ENTER.

-----------------------------------------------------------------

>ipconfig

The list of devices follows:

Windows IP Configuration

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : int.dejavusecurity.com
   Link-local IPv6 Address . . . . . : fe80::d0ef:e30b:2d5c:12c5%3
   IPv4 Address. . . . . . . . . . . : 10.0.1.47
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.1.1

Ethernet adapter VMware Network Adapter VMnet1:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::7859:6e2f:6816:4c38%14
   IPv4 Address. . . . . . . . . . . : 192.168.47.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VMware Network Adapter VMnet8:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::9185:c8de:2e72:1855%15
   IPv4 Address. . . . . . . . . . . : 192.168.127.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Tunnel adapter isatap.int.dejavusecurity.com:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : int.dejavusecurity.com

Tunnel adapter isatap.{F82EF77C-E794-48F2-B588-30E9A54BF97D}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Tunnel adapter isatap.{144CE73D-88A3-4AE6-A26A-6D3F8ADCC960}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

-----------------------------------------------------------------

====================

.Capture output to CrashableServer on port 4244
====================

This parameter example is from a setup that captures all network traffic using the pcap monitor when a fault occurs. When running the fuzzing definition for this example, a crash occurs after few iterations. When Peach logs the fault, a pcap file is created inside the fault record.

*Pcap monitor settings*
[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Device       |Local Area Connection
|Filter       |port 4244
|==========================================================

The setup for this example uses asecond monitor, the xref:Monitors_WindowsDebugger[Windows Debugger] monitor, to launch the CrashableServer executable, normally located in the Peach directory. The following table lists the parameters for that monitor.

*Windows Debugger monitor settings*
[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Executable   |CrashableServer.exe
|Arguments    |127.0.0.1 4244
|==========================================================


====================

endif::peachug[]


ifndef::peachug[]


.Capture output to CrashableServer on port 4244
==================
This example runs CrashableServer.exe and capture all network traffic using the pcap monitor when a fault occurs. 

To run this example, point to the CrashableServer location (normally the Peach directory).

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <String value="Hello World!" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="Pcap">
      <Param name="Device" value="Local Area Connection" />
      <Param name="Filter" value="port 4244" />
    </Monitor>

    <Monitor class="WindowsDebugger">
      <Param name="Executable" value="CrashableServer.exe" />
      <Param name="Arguments" value="127.0.0.1 4244" />
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="TcpClient">
      <Param name="Host" value="127.0.0.1"/>
      <Param name="Port" value="4244"/>
    </Publisher>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 10470.
Peach.Core.Agent.Agent StartMonitor: Monitor Pcap
Peach.Core.Agent.Agent StartMonitor: Monitor_1 WindowsDebugger
Peach.Core.Agent.Agent SessionStarting: Monitor
Peach.Core.Agent.Agent SessionStarting: Monitor_1
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid SessionStarting
Establishing the listener...

[R1,-,-] Performing iteration
Waiting for a connection...
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher start()
Peach.Core.Publishers.TcpClientPublisher open()
Accepted connection from 127.0.0.1:51784.
Peach.Core.Publishers.TcpClientPublisher output(12 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   48 65 6C 6C 6F 20 57 6F  72 6C 64 21               Hello World!

Received 12 bytes from client.
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:4244
Connection closed by peer.
Shutting connection down...
Connection is down.
Waiting for a connection...
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:4244, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:4244
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid DetectedFault()
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid DetectedFault() - No fault detected
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.TcpClientPublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor_1
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid SessionFinished
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _FinishDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Agent SessionFinished: Monitor
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _FinishDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger

[*] Test 'Default' finished.
----

Running this example for a few iterations will produce a crash. When Peach is logging the fault, a pcap file is created inside the fault record.

==================

endif::peachug[]
