<<<
[[Monitors_Ping]]
== Ping Monitor

The _Ping_ monitor verifies whether a device is functioning by sending a packet to a target location, 
and waiting for a response from the device. _Ping_ continues to monitor until either a _Timeout_ occurs 
or it receives a response from the device at the target location. 

_Ping_ can validate that a target is still up or is waiting to restart. This is useful when fuzzing 
embedded devices that do not have easily discernible crashes.

Also, by using the FaultOnSuccess parameter, you can use _Ping_ can verify whether a a new device at 
a specific address becomes available, or that a nonfunctioning device starts to function. For example, 
if you are fuzzing a device that programmatically turns other computers on, you can use _Ping_ with 
*FaultOnSuccess=true* to determine whether the computers are off (an uninteresting result) or on 
(an interesting result). 

The Peach command line option +--showdevices+ causes Peach to generate a list of all available network interfaces. For a sample device listing, see the the xref:Monitors_Pcap[Pcap Network] monitor.

=== Parameters

_Required:_

Host:: Host name or IP address to ping.

_Optional:_

Data:: Data to send in the ping packet.
FaultOnSuccess:: Fault if ping is successful, defaults to false.
Timeout:: Timeout value expressed in milliseconds, defaults to 1,000.

=== Examples

ifdef::peachug[]

.Ping Host
====================

This parameter example is from a setup that pings the Deja vu Security website.

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Host         |www.dejavusecurity.com
|Timeout      |10000
|==========================================================
====================

endif::peachug[]


ifndef::peachug[]

.Ping Host
==============
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="Ping">
      <Param name="Host" value="www.dejavusecurity.com" />
      <Param name="Timeout" value="10000"/>
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="TcpClient">
      <Param name="Host" value="www.dejavusecurity.com"/>
      <Param name="Port" value="80"/>
    </Publisher>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 26777.
Peach.Core.Agent.Agent StartMonitor: Monitor Ping
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher start()
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(4 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   69 7A 00 00                                        iz··

Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 198.185.159.135:80
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 198.185.159.135:80, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 198.185.159.135:80
Peach.Core.Agent.Monitors.PingMonitor DetectedFault(): www.dejavusecurity.com replied after 10000ms
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.TcpClientPublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----
==============

endif::peachug[]
