<<<
[[Monitors_Process]]
== Process Monitor

The _Process_ monitor controls a process during a fuzzing run.  It has a number of features:

 * Restart a process when it dies
 * Log a fault if a process exits early
 * Restart a process on every iteration
 * Terminate a process is the CPU usage is low
 * Interact with StateModel to allow waiting for process exit
 * Interact with StateModel to allow for delayed starting of a process

=== Parameters

_Required:_

Executable:: Executable to launch

_Optional:_

Arguments:: Command line arguments
RestartOnEachTest:: Restart process on each iteration, defaults to false.
FaultOnEarlyExit:: Trigger fault if process exits, defaults to false.
NoCpuKill:: Disable process killing when CPU usage nears zero, defaults to false.
StartOnCall:: Start process on a call action from the StateModel (this value and the method value must match)
WaitForExitOnCall:: Wait for process to exit on state model call (this value and the method value must match)
WaitForExitTimeout:: Wait timeout value.  Triggers fault when timeout hit. Defaults to 10000. Use -1 for infinite.

=== Examples

.Start Process
=================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337"/>
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/> 
      </Action>
      <Action type="close"/>
      <Action type="call" method="launchProgram" publisher="Peach.Agent"/>
    </State>
  </StateModel>

  <Agent name="Local">
	<Monitor class="Process">
		<Param name="Executable" value="notepad.exe" />
		<Param name="Arguments" value="fuzzed.txt" />
	</Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----
=================

.Restart Process on Each Test
=================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/> 
      </Action>
      <Action type="close"/>
      <Action type="call" method="launchProgram" publisher="Peach.Agent"/>
    </State>
  </StateModel>

  <Agent name="Local">
	<Monitor class="Process">
		<Param name="Executable" value="notepad.exe" />
		<Param name="Arguments" value="fuzzed.txt" />
		<Param name="RestartOnEachTest" value="true" />
	</Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----
=================

.Start Process From State Model
=================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>

<StateModel name="State" initialState="Initial" >
  <State name="Initial">
    <Action type="call" method="ScoobySnacks" publisher="Peach.Agent" />
  </State>
</StateModel>

<Agent name="Local">
  <Monitor class="Process">
    <Param name="Executable" value="notepad.exe" />
    <Param name="Arguments" value="fuzzed.txt" />
    <Param name="StartOnCall" value="ScoobySnacks" />
  </Monitor>
</Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----
=================

.Wait for process to exit in state model
=================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>


  <StateModel name="State" initialState="Initial">
    <State name="Initial">
      <!-- This action will block until process exits -->
      <Action type="call" method="ScoobySnacks" publisher="Peach.Agent" />
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="Process">
      <Param name="Executable" value="notepad.exe" />
      <Param name="Arguments" value="fuzzed.txt" />
      <Param name="WaitForExitOnCall" value="ScoobySnacks" />
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----
=================
