[[Monitors_Process]]
== Process Monitor

The _Process_ monitor controls a process during a fuzzing run.  It has a number of features:

 * Restart a process when it dies
 * Log a fault if a process exits early
 * Restart a process on every iteration
 * Terminate a process is the CPU usage is low
 * Interact with StateModel to allow waiting for process exit
 * Interact with StateModel to allow for delayed starting of a process

=== Parameters

 * _Executable_ -- Executable to launch
 * _Arguments_ -- Command line arguments (optional)
 * _RestartOnEachTest_ -- Restart process on each iteration (optional, defaults to false)
 * _FaultOnEarlyExit_ -- Trigger fault if process exits (optional, defaults to false)
 * _NoCpuKill_ -- Disable process killing when CPU usage nears zero (optional, defaults to false)
 * _StartOnCall_ -- Start process on a call action from the StateModel (this value and the method value must match), (optional)
 * _WaitForExitOnCall_ -- Wait for process to exit on state model call (this value and the method value must match), (optional)
 * _WaitForExitTimeout_ -- Wait timeout value.  Triggers fault when timeout hit.  (optional, default 10000, -1 infinite)

=== Examples

.Start Process
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337"/>
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/> 
      </Action>
      <Action type="close"/>
      <Action type="call" method="launchProgram" publisher="Peach.Agent"/>
    </State>
  </StateModel>

  <Agent name="Local">
	<Monitor class="Process">
		<Param name="Executable" value="notepad.exe" />
		<Param name="Arguments" value="fuzzed.txt" />
	</Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----

.Restart Process on Each Test
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/> 
      </Action>
      <Action type="close"/>
      <Action type="call" method="launchProgram" publisher="Peach.Agent"/>
    </State>
  </StateModel>

  <Agent name="Local">
	<Monitor class="Process">
		<Param name="Executable" value="notepad.exe" />
		<Param name="Arguments" value="fuzzed.txt" />
		<Param name="RestartOnEachTest" value="true" />
	</Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----

.Start Process From State Model
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>

<StateModel name="State" initialState="Initial" >
  <State name="Initial">
    <Action type="call" method="ScoobySnacks" publisher="Peach.Agent" />
  </State>
</StateModel>

<Agent name="Local">
  <Monitor class="Process">
    <Param name="Executable" value="notepad.exe" />
    <Param name="Arguments" value="fuzzed.txt" />
    <Param name="StartOnCall" value="ScoobySnacks" />
  </Monitor>
</Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----

.Wait for process to exit in state model
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="TheDataModel">
    <String length="32" value="31337" />
  </DataModel>


  <StateModel name="State" initialState="Initial">
    <State name="Initial">
      <!-- This action will block until process exits -->
      <Action type="call" method="ScoobySnacks" publisher="Peach.Agent" />
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="Process">
      <Param name="Executable" value="notepad.exe" />
      <Param name="Arguments" value="fuzzed.txt" />
      <Param name="WaitForExitOnCall" value="ScoobySnacks" />
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>
    <Agent ref="Local" />

    <Publisher class="File">
      <Param name="FileName" value="fuzzed.txt"/>
    </Publisher>  
  </Test>
</Peach>
----
