<<<
[[Monitors_Ssh]]
== Ssh Monitor

The _Ssh_ monitor connects to a remote host over SSH. The monitor supports password, keyboard, and private key authentication methods. The monitor runs a given command on the remote system. A regular expression can be applied to the result of the command to determine if a Fault has occurred.

The Monitor holds a persistent connection open to the system over the course of the fuzzing run. 

=== Parameters

_Required:_

Host:: Host to ssh too
Username:: Username for ssh
Command:: Command to check for fault 

_Optional:_

Password:: Password for ssh account, defaults to "".
KeyPath:: Path to ssh key, defaults to "".
CheckValue:: Regex to match command response, defaults to "".
FaultOnMatch:: Trigger a fault if the regex matches, defaults to true.

=== Examples

.Example
==========
[source,xml]
----
<Agent name="LocalAgent">
	<Monitor class="Ssh">
		<Param name="Host" value="my.target.com" />
		<Param name="Username" value="tester" />
		<Param name="Password" value="Password!" />
		<Param name="Command" value="ls /var/cores/*.core" />
		<Param name="CheckValue" value="target.*?.core" />
		<Param name="FaultOnMatch" value="true" />
	</Monitor>
</Agent>
----
==========
