<<<
[[Monitors_Ssh]]
== Ssh Monitor

The _Ssh_ monitor connects to a remote host over SSH (Secure Shell).

_Ssh_ runs a given command on the remote system. To determine if a Fault has occurred, apply a regular expression to the result.  

_Ssh_ holds a persistent connection open to the system over the course of the fuzzing run and supports password, keyboard, and private key authentication methods. 

=== Parameters

_Required:_

Host:: Host to SSH too
Username:: Username for ssh
Command:: Command to check for fault

_Optional:_

Password:: Password for SSH account, defaults to "".
KeyPath:: Path to SSH key, defaults to "".
CheckValue:: Regex to match command response, defaults to "".
FaultOnMatch:: Trigger a fault if the regex matches, defaults to true.

=== Examples

.Checking for core dump files
==========
For this example we SSH into the target machine at the end of each iteration to check if any core files exist and fault if one does exist.

In order to run this example a valid Host, Username, and Password need to be specified.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
    <Number size="32" signed="false" value="31337" />
  </DataModel>

  <StateModel name="State" initialState="Initial" >
    <State name="Initial">
      <Action type="output">
          <DataModel ref="TheDataModel"/>
      </Action>
    </State>
  </StateModel>

  <Agent name="Local">
    <Monitor class="Ssh">
      <Param name="Host" value="my.target.com" />
      <Param name="Username" value="tester" />
      <Param name="Password" value="Password!" />
      <Param name="Command" value="ls /var/cores/*.core" />
      <Param name="CheckValue" value="target.*?.core" />
      <Param name="FaultOnMatch" value="true" />
    </Monitor>
  </Agent>

  <Test name="Default">
    <StateModel ref="State"/>

    <Agent ref="Local" />

    <Publisher class="ConsoleHex"/>

    <Logger class="File">
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output for this example.

----
>peach -1 --debug example.xml

[[ Peach Pro v3.0.0.0
[[ Copyright (c) Deja vu Security

[*] Test 'Default' starting with random seed 63850.
Peach.Core.Agent.Agent StartMonitor: Monitor Ssh
Peach.Core.Agent.Agent SessionStarting: Monitor

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   69 7A 00 00                                        iz??
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor

[*] Test 'Default' finished.
----

To verify that Peach is checking for a file on the remote machine, create a file named target.testing.core in /var/cores. When Peach logs in and finds that file, a fault occurs.

==========
