<<<
[[Monitors_Vmware]]
== Vmware Monitor

The _Vmware_ monitor can control a VMware virtual machine (VM).  

_Vmware_ can start a VM and, optionally, reset the VM to a snapshot configuration each iteration.  When a fault occurs, _Vmware_ resets the VM to the specified snapshot.

TIP: When using with vSphere/ESXi, prefix the VM image name with the storage location in brackets.  For example, "[ha-datacenter/datastore1] guest/guest.vmx"

=== Parameters

_Required:_

Vmx:: Path to the virtual machine

_Optional:_

Host:: Name of the host machine
Login:: Username for authentication on the remote machine
Password:: Password for authentication on the remote machine
HostType::
	Type of remote host, defaults to _Default_
	+
	[horizontal]
	Default;; Default
	VIServer;; vCenter Server, ESX/ESXi hosts, VMWare Server 2.0
	Workstation;; VMWare Workstation
	WorkstationShared;;  VMWare Workstation (Shared Mode)
	Player;; VMWare Player
	Server;; VMWare Server 1.0.x

HostPort::
	TCP/IP port on the remote host

SnapshotIndex:: VM snapshot index
SnapshotName:: VM Snapshot name
ResetEveryIteration:: Reset VM to snapshot on every iteration. Defaults to false.
ResetOnFaultBeforeCollection:: Reset VM after we detect a Fault during data collection. Defaults to false.
WaitForToolsInGuest:: Wait for tools to start in guest. Defaults to true.
WaitTimeout:: How many seconds to wait for guest tools. Defaults to 600.

=== Examples

.Start Virtual Machine
======================
[source,xml]
----
<Agent name="Local">
	<Monitor class="Vmware">
		<Param name="Vmx" value="D:\VirtualMachines\OfficeWebTest\OfficeWebTest.vmx" />
		<Param name="HostType" value="Workstation" />
		<Param name="SnapshotName" value="Fuzzing" />
	</Monitor>
</Agent>
----
======================

.Start Virtual Machine hosted on ESXi
======================
[source,xml]
----
<Agent name="Local">
	<Monitor class="Vmware">
		<Param name="Vmx" value="[ha-datacenter/datastore1] guest/guest.vmx" />
		<Param name="SnapshotName" value="Fuzzing" />
	</Monitor>
</Agent>
----
======================
