<<<
[[Monitors_WindowsDebugger]]
== WindowsDebugger Monitor (Windows)

The _WindowsDebugger_ monitor controls a windows debugger instance. 

The source code can be found in peach\Peach.Core.Test.OS.Windows\Agent\Monitors.

*Main Usages*

 * Process debugging
 * Service debugging
 * Kernel debugging

=== Parameters

_Exactly one of the four required parameters is needed for each instance of this monitor. The other three required parameters are not used._

Executable:: Executable to launch via the debugger. If the executable has command-line arguments,  specify these in the "Arguments" paramter.
ProcessName:: Name of the process that the debugger attaches to.
KernelConnectionString:: Connection string for kernel debugging.
Service::  Name of the Windows process or service that the debugger attaches to. If the service crashes or is stopped, this monitor will restart the service.
 
_Optional:_

Arguments:: Command-line arguments for the executable file specified with the "Executable" parameter. 

SymbolsPath:: Path to the debugging symbol files. The default value is Microsoft public symbols server,
SRV*http://msdl.microsoft.com/download/symbols.

WinDbgPath:: Path to the windbg installation. If undeclared, Peach attempts to locate a local installation of the debugger.

StartOnCall:: Defers debugging until the state model issues a call to the monitor to begin. Upon receiving the call, the debugger attaches to the process, or starts the process or executable. 

IgnoreFirstChanceGuardPage:: Ignores faults from the first chance guard page. These faults are sometimes false positives 
or anti-debugging faults, defaults to false.

IgnoreSecondChanceGuardPage:: Ignores faults from the second chance guard page. These faults are sometimes false positives 
or anti-debugging faults, defaults to false.

NoCpuKill:: Allows or disallows the CPU to idle. If true, the CPU can idle without termination. If false, Peach polls and then terminates the process if it is caught idling. The default value is false.

CpuPollInterval:: Specifies the time interval that the monitor waits between successive polls of the process. This argument is used when NoCpuKill is false. 

FaultOnEarlyExit:: Triggers a fault if the process exits prematurely, defaults to false.

WaitForExitOnCall:: Exits the process upon receiving a call from the state model. If the call fails to occur within an 
acceptable  waiting period, issue a fault and then exit. The WaitForExitTimeout parameter specifies the waiting period.

WaitForExitTimeout:: Specifies the WaitForExitOnCall timeout value, expressed in milliseconds, defaults to 10000. The value -1 
specifies an infiniate waiting period.

RestartOnEachTest:: Restarts the process for each iteration, defaults to false.


=== Examples

ifdef::peachug[]

.Commandline Configuration +

This parameter example is from a setup that launches an application with command-line arguments from the Windows Debugger. The setup also supplies the path where the Windows Debugger resides.

==========================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Executable   |CrashableServer.exe
|Arguments    |127.0.0.1 4244
|WinDbgPath   |C:\Program Files (x86)\Debugging Tools for Windows (x86) 

|==========================================================

==========================

.Kernel Configuration +

This parameter example is from a kernel debugging setup.

==========================
[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter               |Value
|KernelConnectionString  |npipe:server=Server, pipe=PipeName [,password=Password] 
|==========================================================

==========================

.Service Configuration +

This parameter example attaches the debugger to a service.

==========================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter  |Value
|Service    |WinDefend
|==========================================================

==========================

.Process Configuration +

This parameter example attaches the debugger to a process name.

==========================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|ProcessName  |CrashableServer.exe
|==========================================================

==========================

.StartOnCall Configuration  +

This parameter example uses the debugger to launch an application with command-line arguments. Further, the launch starts after the monitor receives a call request from the state model to initiate the launch.

==========================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter    |Value
|Executable   |CrashableServer.exe
|Arguments    |127.0.0.1 4244
|StartOnCall  |launchProgram
|==========================================================

==========================

.Exit Configurations  +

This parameter example uses the debugger to launch an application with command-line arguments. Further, the monitor polls the application for idleness, and terminates the application if it finds an idle CPU. At the end of each iteration, Peach waits a maximum of 250ms for the application to close of its own accord before terminating the application.

==========================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter           |Value
|Executable          |CrashableServer.exe
|Arguments           |127.0.0.1 4244
|NoCpuKill           |true
|FaultOnEarlyExit    |false
|WaitForExitTimeout  |250
|==========================================================

==========================

.WaitForExitOnCall Configuration  +

This parameter example uses the debugger to launch an application with command-line arguments. Further, the monitor defers closing the application until receiving the notice from the state model. 

==========================

[cols="2,4" options="header",halign="center"] 
|==========================================================
|Parameter          |Value
|Executable         |CrashableServer.exe
|Arguments          |127.0.0.1 4244
|WaitForExitOnCall  |exitProgram
|==========================================================

==========================

endif::peachug[]


ifndef::peachug[]


.Commandline Configuration
==========================
[source,xml]
----
<Agent name="Local">
	<Monitor class="WindowsDebugger">
		<Param name="Executable" value="CrashableServer.exe" />
		<Param name="Arguments" value="127.0.0.1 4244" />
		<!--<Param name="WinDbgPath" value="C:\Program Files (x86)\Debugging Tools for Windows (x86)" />-->
	</Monitor>
</Agent>
----
==========================

.Kernel Configuration
==========================
[source,xml]
----
<Param name="KernelConnectionString" value="npipe:server=Server, pipe=PipeName [,password=Password]" />
----
==========================

.Service Configuration
==========================
[source,xml]
----
<Param name="Service" value="WinDefend" />
----
==========================

.Process Configuration
==========================
[source,xml]
----
<Param name="ProcessName" value="CrashableServer.exe" />
----
==========================

.StartOnCall Configuration
==========================
[source,xml]
----
<StateModel name="TheState" initialState="initial">
    <State name="initial">
        <Action type="call" method="launchProgram" publisher="Peach.Agent"/>
    </State>
</StateModel>


<Agent name="Local">
    <Monitor class="WindowsDebugger">
        <Param name="Executable" value="CrashableServer.exe"/>
        <Param name="Arguments" value="127.0.0.1 4244"/>
        <Param name="StartOnCall" value="launchProgram"/>
    </Monitor>
</Agent>
----
==========================

.Exit Configurations
==========================
[source,xml]
----
<Agent name="Local">
    <Monitor class="WindowsDebugger">
        <Param name="Executable" value="CrashableServer.exe"/>
        <Param name="Arguments" value="127.0.0.1 4244"/>
        <Param name="NoCpuKill" value="true"/>
        <Param name="FaultOnEarlyExit" value="false"/>
        <Param name="WaitForExitTimeout" value="250"/>
    </Monitor>
</Agent>
----
==========================

.WaitForExitOnCall Configuration
==========================
[source,xml]
----
<StateModel name="TheState" initialState="initial">
    <State name="initial">
        <Action type="call" method="exitProgram" publisher="Peach.Agent"/>
    </State>
</StateModel>


<Agent name="Local">
    <Monitor class="WindowsDebugger">
        <Param name="Executable" value="CrashableServer.exe"/>
        <Param name="Arguments" value="127.0.0.1 4244"/>
        <Param name="WaitForExitOnCall" value="exitProgram"/>
    </Monitor>
</Agent>
----
==========================

endif::peachug[]