=== Create Instance

This section covers how to create an instance in various virtual machine software or cloud providers.
It assumes prior knowledge of the technologies and basic usage.

==== VMWare vSphere

Use the following steps to create a new instance through vSphere:

. Connect to a vSphere server with the vSphere client.
. Select File -> Deploy OVF Template.
. Follow the wizard and optionally change the resource allocation for the virtual appliance.
The defaults provided are safe to use for most installations.

==== VMWare vCenter

Use the following steps to create a new instance through vCenter:

. Connect to a vCenter server with the vSphere client.
. Select an inventory object that is a valid parent object of a virtual machine, 
such as a datacenter, folder, cluster, resource pool, or host.
. Select Actions -> All vCenter Actions -> Deploy OVF Template.
. Specify the source location and click Next.
. Optionally change the resource allocation for the virtual appliance.
The defaults provided are safe to use for most installations.

==== VMWare Workstation

Use the following steps to create a new instance using VMWare Workstation:

. Open VMWare Workstation
. Select File -> Open
. Select the downloaded OVA file
. Optionally change the resource allocation for the virtual appliance.
The defaults provided are safe to use for most installations.

==== Virtual Box

Creating a new instance in Virtual Box is very simple.

Import the virtual appliance::
    This is done via the File menu and the 'Import Virtual Appliance' option.
    Select the +.ova+ file that was downloaded from the Peach API Security
    customer portal at {portalurl}.
    The default values can be used during import.

Start Instance::
    The instance is now ready to be started and configured.

==== Amazon AWS

Two methods currently exist for starting {product} instances.
The first method requires importing the machine image (OVA) file, while 
the second requires purchasing Peach API Security through the Amazon
Marketplace.

===== Import Image

Amazon provides good documentation about importing VM images, including OVAs.
See the following section of the VM Import/Export User Guide: 
http://docs.aws.amazon.com/vm-import/latest/userguide/import-vm-image.html[Step 3: Import Your VM as an Image]

Once imported, an instance of the AMI can be launched.  
See the xref:Install_ResourceRequirements[Resource Requirements] section for recommendations on instance type.

===== Marketplace

New instances can also be purchased/launched via the Amazon Marketplace.
See the xref:Install_ResourceRequirements[Resource Requirements] section for recommendations on instance type.
